### ISSUE TITLE
Add options to debounce / throttle to `o-autocomplete` component

### ISSUE THREAD

**Issue by KevinNTH** [oruga-ui/oruga#10]
### Description
Add options to debounce / throttle to `o-autocomplete` component in order to reduce number of requests sent to the backend when the user types very fast.

### Why Oruga need this feature

Moreover, the method called when `@typing` is triggered is added to the call stack asynchronously so the second call is triggered before the first one has finished, resulting in incoherent data combined from both calls instead of having data from the very last call.

**Comment by jtommy** [comment]
Usually should be the user to add a denounce function but I might add an internal implementation

**Comment by KevinNTH** [comment]
Yes, agreed! I added a debounce wrap by my end and it works perfectly!
