### ISSUE TITLE
How to overwrite scss variable

### ISSUE THREAD

**Issue by cyberfly** [oruga-ui/oruga#100]
Inside `app.js`

```
import { Button } from '@oruga-ui/oruga';
import '@oruga-ui/oruga/dist/oruga-full.css';
```

Inside my `app.scss`

```
$primary: black;
@import "@oruga-ui/oruga/src/scss/utilities/_variables";
```
On template

```
<o-button @click="true">Click Me</o-button>
```

The button still using default color

Trying with this also doesnt seems to work

```
$button-background-color: black;
@import "@oruga-ui/oruga/src/scss/oruga-full.scss";
```

How to fix this?

**Comment by jtommy** [comment]
You have to remove the CSS import from `app.js` and take a look at https://github.com/oruga-ui/oruga/issues/87#issuecomment-777111354
