### ISSUE TITLE
Table: add `centered` column prop

### ISSUE THREAD

**Issue by mlmoravek** [oruga-ui/oruga#1001]
### Description

Add a `centered` property to `TableColumn` that can be used to centee the column content.
The property will add a class to the column.
The styling implementation must then come from the themes.

Otherwise, add a property like `orientation` (or `align`/`alignment`) with the values `left`, `centered`, `right` to align the column content. This could be an extension of the `centered` property.`. 

### Why Oruga need this feature

This is a  feature which is available in Buefy.

**Comment by pflirae** [comment]
I like the idea of a property, maybe `position` is a more descriptive name for the property, with the proposed values

**Comment by mlmoravek** [comment]
Nevermind, there is already a `position` prop...
