### ISSUE TITLE
has-detailed-visible prop on table not working as expected

### ISSUE THREAD

**Issue by gciclo** [oruga-ui/oruga#1036]
### Overview of the problem

**Oruga** version: [v0.9.0-pre.2]
**Vuejs** version: [3.4.21]
**OS/Browser**: Chrome

### Description

Table component prop hasDetailedVisible has no effect on the visibility of the detail icon. It's always visible and does not seem to reflect the prop.

### Steps to reproduce

Construct a table with detailed element.
`<o-table
          narrowed
          bordered
          striped
          hoverable
          checkable 
          detailed
          :has-detailed-visible="(row) => false"> ...`

### Expected behavior
Expect to not see any detail row icons on the table.

### Actual behavior

detail icons are visible for all rows.

**Comment by mlmoravek** [comment]
Hey, thanks for checking out the pre-release version! 

This prop has been renamed to `isDetailedVisible`. Try this one :)

Let us know if you find any other bugs.

**Comment by gciclo** [comment]
Thank you so much!

**Comment by gciclo** [comment]
Another related quick question - is there a way to programatically trigger opening a detail row (like how you would in buefy with `this.$refs.table.openDetailRow(row);` ?
I tried using `update:openedDetailed` but I could not get it to work.

**Comment by mlmoravek** [comment]
If you have specified the `rowKey` prop or given the `customCompare` function prop, you can specify `v-model:detailedRows` (`openedDetailed` has been renamed `detailedRows` to match `checkedRows`).

A detailed list of changes will be in the release nodes when the main 0.9 release is made (I would expect early next month). 

If you want the updated docs for the 0.9 pre-release, I would suggest cloning the `develop` branch of the oruga repo, installing the dependencies (`npm i`) and running the docs for 0.9 locally with `npm run dev:watch`.
