### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'mobile') with @oruga-ui/oruga-next 0.9.0-pre.2 and @oruga-ui/theme-bulma ^0.3.0 in Vue 3.3.13/3.4.38

### ISSUE THREAD

**Issue by isamu** [oruga-ui/oruga#1037]
### Overview of the problem

**Oruga** version: 0.9.0-pre.2  
**Vuejs** version: 3.3.13, 3.4.38  
**OS/Browser**: macOS / Chrome

### Description

When using the combination of:

- "@oruga-ui/oruga-next": "0.9.0-pre.2"
- "@oruga-ui/theme-bulma": "^0.3.0"

an error occurs during Vue browser console:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'mobile')
at mobileClass (@oruga-ui_theme-bulma.js?v=f8c54995:425:17)
at computeClass (@oruga-ui_oruga-next.js?v=1baf2177:369:19)
at getClassBind (@oruga-ui_oruga-next.js?v=1baf2177:299:29)
```

As a result, the application does not render anything in the browser.

### Steps to reproduce

1. Install `@oruga-ui/oruga-next@0.9.0-pre.2` and `@oruga-ui/theme-bulma@^0.3.0` in a Vue project.
2. Start the Vue application.
3. Observe the browser console for the above error.

### Expected behavior

The Vue application should start successfully, and the UI should render correctly without errors.

### Actual behavior

The application throws the `TypeError: Cannot read properties of undefined (reading 'mobile')` error, and nothing is displayed in the browser.

Thanks.

**Comment by mlmoravek** [comment]
Hey @isamu, I appreciate you checking out the new pre-release version!
Unfortunately the Bulma theme is not quite ready for this new version due to some breaking changes. 
The Oruga and Bootstrap themes are already updated. Try them out.

Updating the Bulma theme is one of the last open steps we have to do, but it is already in progress!

**Comment by isamu** [comment]
Thank you for sharing the information.
I don't want it soom but I'm looking forward to them being updated.
I am always grateful for your great work.

**Comment by mlmoravek** [comment]
The bulma-theme v0.4 now supports oruga v0.9.

**Comment by isamu** [comment]
I try it and it is working!!

Thank you so much!!
