### ISSUE TITLE
vue-component-type-helpers not listed as dependency, dependent types all resolve to any

### ISSUE THREAD

**Issue by IlyaSemenov** [oruga-ui/oruga#1038]
### Overview of the problem

**Oruga** version: 0.9.0-pre.1
**Vuejs** version: 3.4.37

### Description

`vue-component-type-helpers` is naturally a direct dependency of oruga, e.g.:

https://github.com/oruga-ui/oruga/blob/67f7ac7d51ba3009f3142efb7aeecc95681fc503/packages/oruga/src/components/modal/types.ts#L1

however, it's not listed in `package.json` as a dependency (only as a dev dependency), and is thus not installed to user's `node_modules` when they install oruga.

As such, all dependent types, such as `ModalProgrammaticProps`, resolve to `any`:

<img width="722" alt="image" src="https://github.com/user-attachments/assets/45af54df-f9b7-45cc-904d-9343e12254ac">

### Steps to reproduce

1. Install `"@oruga-ui/oruga-next": "0.9.0-pre.1"` in empty project.
2. Open `node_modules/@oruga-ui/oruga-next/dist/types/components/modal/ModalProgrammatic.d.ts`
3. See how `ModalProgrammaticProps` resolves.

### Expected behavior

`vue-component-type-helpers` should be a direct dependency of `oruga-next`, it should be installed in user's `node_modules`, and then `ModalProgrammaticProps` should resolve to the proper type.

### Actual behavior

`vue-component-type-helpers` is not installed in user's `node_modules`, and `ModalProgrammaticProps` (and other similar types) resolve to `any` as Typescript's fallback measure.

**Comment by mlmoravek** [comment]
Oh yeah right! I've encountered the `any` type too, but I couldn't find the reason why this happens. 
Even though I would like to stay with zero dependencies, I will consider adding the dependency or rewiring these parts.
Thanks alot!

**Comment by IlyaSemenov** [comment]
I suppose you could just borrow it from there, it's not a big deal really:

```ts
export type ComponentProps<T> =
	T extends new (...angs: any) => { $props: infer P; } ? NonNullable<P> :
	T extends (props: infer P, ...args: any) => any ? P :
	{};
```

Also, just a heads up, in `tsup` one can mark certain external packages to be bundled (inlined) with `noExternal` option: https://tsup.egoist.dev/#excluding-packages. This way, the type will be inlined automatically on `.d.ts` build.

I'm not sure what's the counterpart in raw vite/rollup/babel setup that you use in Oruga, but there could be one as well (after all, tsup uses rollup under the hood).

**Comment by mlmoravek** [comment]
This project uses [vite-plugin-dts](https://github.com/qmhc/vite-plugin-dts) to build the types.
Even though vite-plugin-dts builds on [api-extractor](https://api-extractor.com), which has a [`bundledPackages`](https://api-extractor.com/pages/configs/api-extractor_json/#bundledpackages) config to include external types, there seems to be a problem within vite-plugin-dts to do it right: https://github.com/qmhc/vite-plugin-dts/issues/302

So I would decide to add ["vue-component-type-helpers"](https://github.com/vuejs/language-tools/tree/master/packages/component-type-helpers) as a dependency to solve this problem.
