### ISSUE TITLE
Doc site crashing on Slider

### ISSUE THREAD

**Issue by wrabit** [oruga-ui/oruga#104]
Happening in Chrome + Safari (Mac M1)

I have only seen it happen in the Slider area. I try a couple of the sliders, refresh and it crashes. Page becomes impossible to use. 

![image](https://user-images.githubusercontent.com/5918271/111274266-180fa800-8635-11eb-986a-ba1f9bfb8783.png)

![image](https://user-images.githubusercontent.com/5918271/111274425-43929280-8635-11eb-9847-3ad12e5fc352.png)

**Comment by astagi** [comment]
Fixed by https://github.com/oruga-ui/oruga/commit/b27b93431605177f4383838a680fbb921b7fc7e2
