### ISSUE TITLE
modal.promise typed incorrectly

### ISSUE THREAD

**Issue by IlyaSemenov** [oruga-ui/oruga#1043]
### Overview of the problem

**Oruga** version: 0.9.0-pre.1
**Vuejs** version: 3.4.37

### Description

Oruga programmatic modal response promise type is incorrect. It's typed as `Promise<void>` while in fact it's `Promise<unknown>` where unknown is the result as emitted by `emit("close", result)`.

Being able to retrieve `modal.promise` result is a documented feature:
https://github.com/oruga-ui/oruga/blob/67f7ac7d51ba3009f3142efb7aeecc95681fc503/packages/oruga/src/components/modal/examples/programmatically-async.vue#L44

### Steps to reproduce

```ts
const modal = oruga.modal.open(params)
typeof modal.promise // Promise<void>
const result = await modal.promise // typeof result is void
```

<img width="598" alt="image" src="https://github.com/user-attachments/assets/ebf04757-96d7-4520-9974-3068b1487b24">

### Expected behavior

`modal.promise` should be typed as `Promise<unknown>`, representing the actual case.

### Actual behavior

`modal.promise` is typed as `Promise<void>`.

**Comment by IlyaSemenov** [comment]
The return type could be even automatically inferred from the respective component `emits` with something like:

```ts
type ModalProgrammaticProps<C> = Readonly<string | (Omit<ModalProps, "component"> & OrugaOptions["modal"] & {component: C})>;

type CloseArg<C> = C extends { emits?: infer CEmits }
  ? CEmits extends { close: infer CEmitsClose }
    ? CEmitsClose extends { (arg: infer CEmitsCloseArg): void }
      ? CEmitsCloseArg
      : never
    : never
  : never

export interface ProgrammaticExpose<T = unknown> {
    close(...args: any[]): void;
    promise: Promise<T>;
}

declare const ModalProgrammatic: {
    open<C>(params: ModalProgrammaticProps<C>): ProgrammaticExpose<CloseArg<C>>;
    closeAll(...args: any[]): void;
};
```

I am using a wrapper around `useOruga` / `oruga.modal.open` which does that successfully (I can share full code if needed).

I suppose I can also come up with a PR for Oruga if that has chances to be accepted.

**Comment by mlmoravek** [comment]
Hey, yeah, there could be some type enhancements for the programmatic components. I'm currently working on some unification of the programmatic implementation. I will take a closer look at the types while doing so. 

However, I am thankful for any feedback I can get :)
