### ISSUE TITLE
Default sort on table not working

### ISSUE THREAD

**Issue by papyreno** [oruga-ui/oruga#106]
### Overview of the problem

**Oruga** version: 0.3.5
**Vuejs** version: 2.6.12
**OS/Browser**: Windows 10 64 bits / Chrome 87.0.4280.141 64 bits

### Description

When one sets a default sort on a table, whether as a string (`default-sort="user.first_name"`) or an array (`:default-sort="['user.first_name', 'asc']"`), this sort is not applied.

### Steps to reproduce

You can see the bug in the official documentation for the table component, in the pagination example (https://oruga.io/components/table.html#pagination) where a default sort is set on the `user.first_name` column:
```
<o-table
      :data="data"
      :paginated="isPaginated"
      :per-page="perPage"
      :current-page.sync="currentPage"
      :pagination-simple="isPaginationSimple"
      :pagination-position="paginationPosition"
      :default-sort-direction="defaultSortDirection"
      :sort-icon="sortIcon"
      :sort-icon-size="sortIconSize"
      default-sort="user.first_name"
      aria-next-label="Next page"
      aria-previous-label="Previous page"
      aria-page-label="Page"
      aria-current-label="Current page"
    >
```

### Expected behavior

Rows should be sorted by user first name.

### Actual behavior

Rows aren't sorted by user first name, as you can see on the screenshot below:
![Table-Oruga-default-sort-ko](https://user-images.githubusercontent.com/4242654/111440005-34c7e080-8706-11eb-94d6-c3001e2001b5.png)

In the table component source code, I've noticed that the `checkSort` method is never called.
Moreover, the `firstTimeSort` data is set to `false`:
```
data() {
    return {
        // ...

        // firstTimeSort: true, // Used by first time initSort
        firstTimeSort: false,

        // ...
    }
}
```

### Workaround
In the `mounted` hook of the component where I put a table, I've added this:

```
<template>
  <o-table :data="data" :default-sort="['default-sort-column', 'asc']" />
</template>

<script>
export default: {
  // ...

  mounted() {
    this.$children.filter((c) => /otable/gi.test(c._name))[0].initSort()
  },

  // ...
}
</script>
```

**Comment by jtommy** [comment]
@papyreno oruga-next (Vue 3,) or oruga (Vue 2) ?

**Comment by papyreno** [comment]
> @papyreno oruga-next (Vue 3) or oruga (Vue 2) ?

@jtommy oruga (Vue 2)

**Comment by bagaskarala** [comment]
in my case it still working, but the arrow doesn't show up in header at first time.
in buefy example, the arrow is shown https://buefy.org/documentation/table/#async-data

**Comment by astagi** [comment]
@papyreno @bagaskarala my PR should fix your issues with default sorting
