### ISSUE TITLE
Textarea Autosize Prop

### ISSUE THREAD

**Issue by bradley-varol** [oruga-ui/oruga#107]
### Description

It might be a good idea to implement automatic resizing for textareas!
Having tried several packages for this, i highly recommend the following:
https://github.com/devstark-com/vue-textarea-autosize

I am happy to implement this as a feature :)

### Why Oruga need this feature

It's a common request and is not difficult to implement. Having this as part of Orgua will save users the need to search for a working implementation.

**Comment by astagi** [comment]
Sounds great @bradley-varol , thank you! I'll insert it in the backlog

**Comment by astagi** [comment]
Sorry @bradley-varol I missed this part

```
I am happy to implement this as a feature :)
```

so you want to implement this and send a PR? That would be awesome, I can assign it to you!

**Comment by bradley-varol** [comment]
> Sorry @bradley-varol I missed this part
> 
> ```
> I am happy to implement this as a feature :)
> ```
> 
> so you want to implement this and send a PR? That would be awesome, I can assign it to you!

Absolutely! I'll get it done this weekend :)

**Comment by astagi** [comment]
Sounds great @bradley-varol!! If you have any question let us know! (we're also active on [Discord](https://discord.gg/RuKuBYN) ✌🏻)

**Comment by bradley-varol** [comment]
Sorry, I didn't get a chance to do this over the weekend! I did take a look at the codebase - do you mind sharing briefly in which files you'd do the height maths and onInput handling for this? Usually I'd stick this in a textarea component but in this case i'd be extending the Input component. Would you suggest creating a new Mixin in utils?

**Comment by jtommy** [comment]
@bradley-varol you might add all to FormElementMixin 😉

**Comment by astagi** [comment]
Hey @bradley-varol any updates on this? Let us know if you need help with this feature :)
