### ISSUE TITLE
[bug] arrow on table header not showing when default sort applied

### ISSUE THREAD

**Issue by bagaskarala** [oruga-ui/oruga#109]
### Overview of the problem

**Oruga** version: [0.3.5]
**Vuejs** version: [2.6.12]
**OS/Browser**: chrome

### Description

Sorted header doesnt showed up at first, when we use `default-sort` prop

### Steps to reproduce

Set `default-sort` on table

### Expected behavior

Sorted header work and arrow icon will showed up.

This is the reference https://buefy.org/documentation/table/#async-data.
`vote count` header get sorted at first load, when we set `default-sort` prop

### Actual behavior

Header sorted state not shown

**Comment by jtommy** [comment]
Double https://github.com/oruga-ui/oruga/issues/106
