### ISSUE TITLE
checkbox disabled style overrides the background-image when checked

### ISSUE THREAD

**Issue by fahdaddi** [oruga-ui/oruga#114]
### Overview of the problem

**Oruga** version: 0.3.4
**Vuejs** version: 2.6.12
**Nuxtjs** version: 2.15.0
**OS/Browser**: MacBook Pro/Chrome

### Description

**checkbox** `disabled` style overrides the `background-image` when checked

### Steps to reproduce

1. create checkbox component with value true
2. add the disabled prop

### Expected behavior

checked svg icon should be displayed with a grayscale filter

### Actual behavior

disabled prop adds a background style which overrides the checked svg img

```
<template>
  <o-checkbox v-model="checkboxCustom" true-value="Yes" false-value="No" disabled>23</o-checkbox>
</template>

<script>
export default {
  data() {
    return {
      checkboxCustom: "Yes",
    };
  },
};
</script>
```
<img width="81" alt="Capture d’écran 2021-03-29 à 14 53 27" src="https://user-images.githubusercontent.com/23249370/112850959-69428180-90a2-11eb-931d-21bf87ef286f.png">

<img width="327" alt="Capture d’écran 2021-03-29 à 14 56 45" src="https://user-images.githubusercontent.com/23249370/112850984-6f386280-90a2-11eb-997d-d185bdafe1b9.png">

**Comment by astagi** [comment]
Uhm `input:disabled` is a css rule with a high specificity, it overrides Oruga defaults. @fahdaddi could you try to check your custom css and remove that rule? then try to add a class for OCheckbox when disabled using Oruga config.

**Comment by fahdaddi** [comment]
> Uhm `input:disabled` is a css rule with a high specificity, it overrides Oruga defaults. @fahdaddi could you try to check your custom css and remove that rule? then try to add a class for OCheckbox when disabled using Oruga config.

just had a talk with @jtommy, it's a normalizeCss rule, I removed it.
will close this issue
