### ISSUE TITLE
Bug: Table `mobileCards` not working as expected

### ISSUE THREAD

**Issue by mlmoravek** [oruga-ui/oruga#1141]
### Overview of the problem

**Oruga** version: [0.9.X]

### Expected behavior

 `mobileCards: false` disable the cards behavior.

### Actual behavior

When using the Table component with `mobileCards: false', the the Table will be displayed as cards anyway.

**Comment by akhileshverma92** [comment]
hey I want to work on this issue can you assign this to me @mlmoravek

**Comment by mlmoravek** [comment]
Hey @akhileshverma92, 
just open a PR if you have something finished :)
