### ISSUE TITLE
Autocomplete textbox content is not cleared when the clear button is clicked

### ISSUE THREAD

**Issue by balping** [oruga-ui/oruga#1149]
### Overview of the problem

**Oruga** version: 0.9.2
**Vuejs** version: 3.5.13
**OS/Browser**: Firefox 133

### Description

The contents of an autocomplete box should be cleared when `clearable` is enabled and the clear button is clicked.

https://github.com/user-attachments/assets/0c634093-f0c6-4e42-97c6-2c448324b665

[Sandbox](https://codesandbox.io/p/sandbox/oruga-test-forked-vxygqv?workspaceId=ws_VU5aYQ1zKAsEdbKNBYw2Zk)

### Steps to reproduce

1. Create autocomplete box that is `clearable`

```
<o-autocomplete
      v-model="selected"
      clearable
      open-on-focus
      :options="options"
    >
    </o-autocomplete>
```

2. Select an item

3. Click on the clear button.

### Expected behaviour

The `selected` variable should be cleared and the textbox should also be cleared.

### Actual behaviour

Only the  `selected` variable is cleared.

**Comment by balping** [comment]
Thanks for the quick fix!

**Comment by mlmoravek** [comment]
Will be released soon :)
