### ISSUE TITLE
Update on vue 3 and Documentation!

### ISSUE THREAD

**Issue by folamy** [oruga-ui/oruga#137]
The current components' document is targeted to vue 2! Is there Documentation for vue 3?

**Comment by astagi** [comment]
Hey @folamy 👋 no, I'm sorry, Vue3 documentation is still in progress, we're working hard to make documentation available both for Vue2 and Vue3. I'll keep this issue open in order to track progresses.

**Comment by folamy** [comment]
Thank you for your response! I look forward to see that.

**Comment by folamy** [comment]
In light of this discussion, I want to solicit for support with ViteJs(SSR).

**Comment by astagi** [comment]
Sure, we haven't tried Oruga with Vite yet! Did you have a chance to run a project combining Oruga and ViteJS?

**Comment by folamy** [comment]
Yes, I tried vite SSR but there was a  bunch of error!

**Comment by folamy** [comment]
> Sure, we haven't tried Oruga with Vite yet! Did you have a chance to run a project combining Oruga and ViteJS?

Yes, I tried vite SSR but there was a  bunch of error

**Comment by astagi** [comment]
ok! @folamy do you have any example with Vite you can share? so we can start from that point to fix issues

**Comment by folamy** [comment]
> ok! @folamy do you have any example with Vite you can share? so we can start from that point to fix issues

I will share a repo here today.

**Comment by astagi** [comment]
thank you very much @folamy 🙏

**Comment by folamy** [comment]
> ok! @folamy do you have any example with Vite you can share? so we can start from that point to fix issues

Here is the demo repository:
https://github.com/folamy/viteSSR-Oruga/tree/master

A huge notice was that the base style/css is not properly applied to the components.

**Comment by jtommy** [comment]
@folamy it's not an issue about vite and Oruga.
You are using oruga.css and as mentioned in the docs it contains only minimal CSS (https://oruga.io/documentation/#customization).
You should add your custom classes or integrated a CSS framework or use oruga-full.css.

**Comment by folamy** [comment]
Oh, really!

**Comment by folamy** [comment]
> @folamy it's not an issue about Vite and/or Oruga.
> 
> You are using oruga.css and as mentioned in the docs it contains only minimal CSS (https://oruga.io/documentation/#customization).
> You should add your custom classes or integrated a CSS framework or use oruga-full.css.

Oh, really! Lemme try that!

**Comment by dheimoz** [comment]
hey @folamy, did your experiment work?

I believe that the community will benefit from this. Vite + Oruga = MORE AWESOME.

**Comment by jtommy** [comment]
@dheimoz Oruga works very well with Vite.
We are internally testing next version using it.

**Comment by dheimoz** [comment]
hey @jtommy thanks for heads up.
Kudos to the team.

**Comment by jtommy** [comment]
New docs is working progress https://github.com/oruga-ui/oruga/pull/340 and all examples will show code with Vue 3 composition api

**Comment by NarekMeliksetyan** [comment]
good morning! how can I  use Oruga for SSR with Vite, without nuxt js? @jtommy

**Comment by jtommy** [comment]
What do you mean? What's the problem?
