### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by bobmcallan** [oruga-ui/oruga#142]
I'm switching / upgrading from Vue 2 and Buefy. A key (and great) feature for n Buefy was/is the table component however I'm receiving an error with Vue 3.

**Error**
The vue warning : [Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at...

**Console Error**
`
runtime-core.esm-bundler.js:4818 Uncaught (in promise) TypeError: Cannot read property 'type' of null
`

I'm raising the issue here, as this appears to only occur with the Oruga table component.

**Setup**

"@oruga-ui/oruga-next": "^0.4.1",
"vue": "^3.0.5",
"vue-router": "^4.0.8"
"vite": "^2.3.6",

Error appears on chrome/edge/firefox

**Console Error**
`
runtime-core.esm-bundler.js:4818 Uncaught (in promise) TypeError: Cannot read property 'type' of null
`

**Offending Code**
`
const unmountComponent = (instance, parentSuspense, doRemove) => {
        if ((process.env.NODE_ENV !== 'production') && instance.type.__hmrId) {
            unregisterHMR(instance);
        }
`

**Setup**

I'm using the code provided in the examples as much as possible.

`
app.use(Oruga, {
        icon: {
            override: true,
            rootClass: 'icon',
        },
        button: {
            override: true,
            rootClass: 'btn',
            variantClass: 'btn-',
            roundedClass: 'btn-rounded',
            outlinedClass: 'btn-outlined-',
            disabledClass: 'btn-disabled'
        },
        dropdown: {
            override: true,
            menuClass: 'dropdown-menu',
            itemClass: 'dropdown-item',
            itemActiveClass: 'dropdown-item-active'
        },
        table: {
            override: true,
            wrapperClass: 'table-wrapper',
            tableClass: 'table',
            stripedClass: 'is-striped',
            hoverableClass: 'is-hoverable',
        }
    })
`

<o-table :data="data" :columns="columns" narrowed striped hoverable></o-table>

**Steps to Reproduce**
1. Load the app, page.
2. If the error does not appear first time, switch routes and then back to the initial
3. Switching to 'blank' routes is fine, on when the template contains the table comp, does the error appear.

**Suspicion**
 From the error it looks like vue/vite is attempting to unload the component however is failing.

Thanks,
Bob

**Comment by jtommy** [comment]
@coreyworrell can you share the code of table too?

**Comment by bobmcallan** [comment]
If you mean the data I was using.. nothing more than the example code on the website. i.e. same data and column arrays.

This is the full page.

`
<template>

    <section class="dashboard">

        

        <div class="b-table">
            <o-table :data="data" :columns="columns" narrowed striped hoverable></o-table>
        </div>

        <hr />

        <span v-if="isDebug">

            <highlight title="state" :data="userstate" />

        </span>

    </section>

</template>

<script>

    import { defineComponent, computed } from "vue";
    import { userStore } from "@matrak/store/user";
    import { newlogger } from '@matrak/lib/vue/vue-logger';

    export default defineComponent({

        name: "dashboardCntrl",

        setup() {
            const logger = newlogger({ name: 'dashboardCntrl', level: 'debug' });
            const user = userStore();

            return {
                userstate: computed(() => user.$state),
                username: computed(() => user.username),
                updateUsername: user.updateUsername,
            };
        },

        data() {
            return {
                data: [
                    {
                        id: 1,
                        first_name: 'Jesse',
                        last_name: 'Simmons',
                        date: '2016-10-15 13:43:27',
                        gender: 'Male'
                    },
                    {
                        id: 2,
                        first_name: 'John',
                        last_name: 'Jacobs',
                        date: '2016-12-15 06:00:53',
                        gender: 'Male'
                    },
                    {
                        id: 3,
                        first_name: 'Tina',
                        last_name: 'Gilbert',
                        date: '2016-04-26 06:26:28',
                        gender: 'Female'
                    },
                    {
                        id: 4,
                        first_name: 'Clarence',
                        last_name: 'Flores',
                        date: '2016-04-10 10:28:46',
                        gender: 'Male'
                    },
                    {
                        id: 5,
                        first_name: 'Anne',
                        last_name: 'Lee',
                        date: '2016-12-06 14:38:38',
                        gender: 'Female'
                    }
                ],
                columns: [
                    {
                        field: 'id',
                        label: 'ID',
                        width: '40',
                        numeric: true
                    },
                    {
                        field: 'first_name',
                        label: 'First Name'
                    },
                    {
                        field: 'last_name',
                        label: 'Last Name'
                    },
                    {
                        field: 'date',
                        label: 'Date',
                        position: 'centered'
                    },
                    {
                        field: 'gender',
                        label: 'Gender'
                    }
                ]
            }
        },

        methods: {

            clickMe() {
                this.$logger.debug("HERE");
            }


        }

    });


</script>
`

**Comment by jtommy** [comment]
@bobmcallan in the meanwhile try using `table-column` component instead of `columns` prop

**Comment by bobmcallan** [comment]
Thanks that works.. in fact that was how i will implement anyways.. I'm building out a full site over the next few weeks.. happy to keep you informed of progress if that helps.

**Comment by olufemioyedepo** [comment]
> 
> 
> @bobmcallan in the meanwhile try using `table-column` component instead of `columns` prop

could you please update the docs if anything property has been deprecated. the official doc encourages the use of **columns** prop

**Comment by Velome** [comment]
> > @bobmcallan in the meanwhile try using `table-column` component instead of `columns` prop
> 
> could you please update the docs if anything property has been deprecated. the official doc encourages the use of **columns** prop. Thanks...

Hi all, 
I just lost 2 hours figuring out what was happening before reading this post and go the "o-table-column" way instead of the "columns prop" way.
The doc is still giving the "columns prop" way as exemple...
