### ISSUE TITLE
Input / Password Reveal

### ISSUE THREAD

**Issue by bobmcallan** [oruga-ui/oruga#143]
Implementing with Bulma, does not align the reveal icon. 

**logon.vue**
'
        <div class="field">

            <p class="control has-icons-right">

                <input class="input is-warning" type="password" placeholder="Password">

                <span class="icon is-small is-right">
                    <i class="fas fa-lock"></i>

                </span>

            </p>

        </div>

        <o-field>

            <o-input type="password" class="is-warning" :iconClickable="true"
                v-model="credentials.password" password-reveal />

        </o-field>
'
**oruga_plugin.vue**

'
field: {
      override: true,
      rootClass: 'field',
      variantClass: 'is',
  },
  input: {
      override: true,
      rootClass: 'control',
      inputClass: 'input',
      iconRightClass: 'has-icons-right',
      iconLeftClass: 'has-icons-left',
      variantClass: 'is-',
  },
'

**Output**

![image](https://user-images.githubusercontent.com/8773580/120880426-d11ac880-c60d-11eb-8137-a9dc34eb5550.png)

![image](https://user-images.githubusercontent.com/8773580/120880437-e7288900-c60d-11eb-8a46-19ad41fd2e9a.png)

**Setup**
Vue 3/Vite
Vanilla Bulma.css (no oruga css)

**Question / Suggestion**
Can you pass (add) the class prop to the control output. i.e. bulma needs "is-warning" on the control, easier to add as a class

Thanks,
Bob

**Comment by jtommy** [comment]
I'm working on a plugin that integrates Bulma with Oruga (and some Buefy styles).
About input you cannot apply in this way the classes because the internal structure of html elements is a little different.
You can do it it in two ways:
- add your classes
- add Bulma classes on the same html element

About the last one I mean something like:

```
input: {
        override: true,
        rootClass: (_: string, { props, computed }: any) => {
            const classes = ['control']
            if (props.icon) classes.push('has-icons-left')
            if (computed.hasIconRight) classes.push('has-icons-right')
            return classes.join(' ').trim()
        },
        inputClass: 'input',
        roundedClass: 'is-rounded',
        variantClass: 'is-',
        sizeClass: 'is-',
        expandedClass: 'is-expanded',
        // iconLeftSpaceClass: 'has-icons has-icons-left',
        iconLeftClass: 'is-left',
        iconRightClass: 'is-right',
        // iconRightSpaceClass: 'has-icons has-icons-right',
        counterClass: 'help counter'
    },
```
I'm very happy to see you are working in the right direction and if you want you can help me to continue the official plugin (it's in a private repository at the moment).

**Comment by bobmcallan** [comment]
Thanks for the details. That's a great idea to use a function to add to the base class (or any class). I actually ended up using straight html/bulma to achieve the form as it is a fairly simple. 

Happy to help, the idea/structure of oruga is great, maybe some 'cheat sheets' or as you suggested (?) having some framework specific plugins, would assist in some areas.

As I'm working through, I find that I need to edit/touch specific component classes.. anyways anything I can do.

Bob
