### ISSUE TITLE
Pagination Links

### ISSUE THREAD

**Issue by bobmcallan** [oruga-ui/oruga#145]
I've loaded the 'Table' component with service side pagination. However the pagination links are marked with [disabled="false"], which results in a no link mouse over (the link works, however is there a reason the attribute is added?)

![image](https://user-images.githubusercontent.com/8773580/120892166-28418d00-c650-11eb-9b41-454301ea4fdb.png)

Is there a setting/prop I'm missing? 

Manually removed [disabled="false"] on page 2
![image](https://user-images.githubusercontent.com/8773580/120892110-eca6c300-c64f-11eb-8762-bb485bd6e059.png)
![image](https://user-images.githubusercontent.com/8773580/120892125-f5979480-c64f-11eb-9232-c7406be35979.png)

Bob

**Comment by jtommy** [comment]
Yes, I already fixed it.
Available in the next release!!

**Comment by bobmcallan** [comment]
Thanks.. to good.
