### ISSUE TITLE
Custom icons packs: documentation on internal icons

### ISSUE THREAD

**Issue by rubjo** [oruga-ui/oruga#148]
### Overview of the problem

**Oruga** version: 0.4.1
**Vuejs** version: 3.1.1
**OS/Browser**: macOS/Chrome

### Description

Thank you for your work on this library, it looks very promising!

For adding a custom icon pack, "close-circle" is missing from list of internal icons in documentation on
https://oruga.io/components/Icon.html#custon-icon-pack

Maybe other internal icons as well, I'm not sure how to get a complete list of all used. I tested changing the "times" for closing notifications, but that didn't seem to be overridable.

Meanwhile, in
https://oruga.io/components/Icon.html#custom-icon-component,
"faUpload" is listed as an internal icon, but is it internally used anywhere?
https://oruga.io/components/Upload.html#props
looks like it lists several props which belongs to a typical component needed inside the upload (eg. a button) and has no effect on the upload component itself (eg. icon)

### Reproduced on

https://codesandbox.io/s/dreamy-rgb-yv426?file=/src/main.js

**Comment by jtommy** [comment]
Yes, you are right. We'll review current icon docs
