### ISSUE TITLE
Add property for close icon in Inputitem

### ISSUE THREAD

**Issue by OskarKinomoto** [oruga-ui/oruga#150]
### Description

Add `closeItemIcon` (or somthing like that) property to Inputitem. It will allow to change icon which is now always set as `times`. 

### Why Oruga need this feature

For example Material Design Icon pack dosn't have icon named times, but event without that problem additional customization will be nice :)

**Comment by jtommy** [comment]
@OskarKinomoto you are right!!
it's missing `both` prop too (an internal prop that allows to configure times icon name to your icon pack as described https://oruga.io/components/Icon.html#examples).

Waiting for the improvement you might use `selected` slot https://oruga.io/components/InputItems.html#custom-selected

**Comment by OskarKinomoto** [comment]
Thanks for accepting it and for workaround (somehow I didn't saw selected slot).

**Comment by jtommy** [comment]
https://github.com/oruga-ui/oruga/commit/5205c2cd9fe48458e279b981c90d4c3b32d73c81
