### ISSUE TITLE
Table Sort / Bulma / Mobile style 

### ISSUE THREAD

**Issue by bobmcallan** [oruga-ui/oruga#152]
I'm using @next and bulma, however I've not able to achieve the same style as Buefy with the mobile table sort. 

![image](https://user-images.githubusercontent.com/8773580/122020560-363d9d80-ce08-11eb-892f-d500ae7a39bd.png)

vs.

![image](https://user-images.githubusercontent.com/8773580/122020678-54a39900-ce08-11eb-8066-bdd56856a426.png)

Is this possible? Oruga generates html, with a number of elements that are not required/expected (?) and cannot be edited from vie the component.

eg.
![image](https://user-images.githubusercontent.com/8773580/122022862-5bcba680-ce0a-11eb-94f6-d657055fd090.png)

Thanks,
Bob

**Comment by jtommy** [comment]
@bobmcallan we are working on Bulma integration as you can see https://github.com/oruga-ui/oruga-bulma

Probably the Buefy style has to edited in order to work well with Oruga as I did with other components (steps).

At this point we came discuss about in the other repository.
