### ISSUE TITLE
Used wrong css variable for tooltip color

### ISSUE THREAD

**Issue by OskarKinomoto** [oruga-ui/oruga#153]
### Overview of the problem

**Oruga** version: 0.4.2
**Vuejs** version: 2.6.14
**OS/Browser**:

### Description

`.o-tip__content` class incorectly uses same css variable for both color and background `--oruga-tooltip-background-color`

![obraz](https://user-images.githubusercontent.com/4709922/122165061-f57d6d00-ce77-11eb-8bc0-3191239c7353.png)

I assume same problem can happen with scss variables

### Steps to reproduce

Use style with css variables enabled.

### Expected behavior

It will use `--oruga-tooltip-color` for color.

### Actual behavior

It uses `--oruga-tooltip-background-color` for color.

**Comment by jtommy** [comment]
You are right, please make a PR ;)
