### ISSUE TITLE
[Vue3]  Adding new data to table produces an error 

### ISSUE THREAD

**Issue by OskarKinomoto** [oruga-ui/oruga#157]
### Overview of the problem

**Oruga** version: 0.4.2
**Vuejs** version: 3.1.1
**OS/Browser**:

### Description

Adding new data to table produces an error 

### Steps to reproduce

https://codesandbox.io/s/blissful-allen-3w04s

### Expected behavior

New row appears

### Actual behavior

Exception is thrown

**Comment by jtommy** [comment]
It's an issue with Vue 3 version and so in the next version we don't support `columns `prop.

You might change your code to:

```
<template 
      v-for="column in columns"
      :key="column.field">
      <o-table-column
        :field="column.field"
        :label="column.label">
        <template v-slot="{ row }">
          {{ row[column.field] }}
        </template>
      </o-table-column>
    </template>
```

**Comment by OskarKinomoto** [comment]
Thank you, it solves all my problems with tables :)
