### ISSUE TITLE
Distribute scss files in oruga-next builds

### ISSUE THREAD

**Issue by OskarKinomoto** [oruga-ui/oruga#159]
### Description

Distribute scss files in oruga-next builds

### Why Oruga need this feature

Now using oruga with Vue 3 and wanting to use scss files as style source one must use both `oruga` and `oruga-next` packages

**Comment by astagi** [comment]
Sure @OskarKinomoto you're right, at the moment scss files are missing in the package, sorry for that! I'll fix it asap!

**Comment by astagi** [comment]
@OskarKinomoto this feature will be released in the next version
