### ISSUE TITLE
[Vue 3] Slider sets 0 to model on mounting 

### ISSUE THREAD

**Issue by OskarKinomoto** [oruga-ui/oruga#161]
### Overview of the problem

**Oruga** version: 0.4.2
**Vuejs** version: 3.1.1
**OS/Browser**:

### Description

Slider resets value on initialization (mounting or something) 

### Steps to reproduce

```
<template>
  <o-slider v-model="x" />
  {{ x }}
</template>

<script>
export default {
  name: "App",
  data: () => ({
    x: 100,
  }),
  watch: {
    x(to, from) {
      console.log("x changed", from, to);
    },
  },
};
</script>
```

### Expected behavior

Model value stays as initialized

### Actual behavior

Value is set to 0

**Comment by jtommy** [comment]
Already fixed! https://github.com/oruga-ui/oruga/commit/a4670ffdec39a1a8109e2a1a7fe53c91b2892f36
