### ISSUE TITLE
Tabs should make the button tag optional for tabitems

### ISSUE THREAD

**Issue by mat813** [oruga-ui/oruga#162]
### Description

Tabs should make the button tag optional for tabitems.

### Why Oruga need this feature

Right now, there is no way to change the default tag, even when using the header slot.
Some css frameworks, like, say, Bulma, are much more cute when using a `a` tag instead.

**Comment by jtommy** [comment]
Why do you need `a` element?

**Comment by astagi** [comment]
@mat813 PR #177 should satisfy your request
