### ISSUE TITLE
Add a carousel component

### ISSUE THREAD

**Issue by pmerienne** [oruga-ui/oruga#167]
### Description
Carousels are quite used in many website. 
Here's some link and screenshots of carousels found in some popular library :

**Boostrap**
https://getbootstrap.com/docs/4.0/components/carousel/
![boostrap](https://user-images.githubusercontent.com/739495/124917106-ba440900-dff3-11eb-9a5e-246951f13339.png)

**Bulma (with a special lib)**
https://bulma-carousel.onrender.com/
![bulma](https://user-images.githubusercontent.com/739495/124917982-c41a3c00-dff4-11eb-922e-cb3c8977c327.png)

**Vuetify**
https://vuetifyjs.com/en/components/carousels/
![vuetify](https://user-images.githubusercontent.com/739495/124916953-88cb3d80-dff3-11eb-8a0a-5046f4fe0c8d.png)

### Why Oruga need this feature
I'm quite surprised many components' framework don't provide Carousel !
This will surely be a great addition to differentiate Oruga from the competition.

**Comment by jtommy** [comment]
Sure, probably it will be the same of https://buefy.org/documentation/carousel

**Comment by coreyworrell** [comment]
@jtommy I think you may have meant to tag someone else here?

**Comment by jtommy** [comment]
@coreyworrell i'm sorry 😸 

Yes I meant @pmerienne

**Comment by pmerienne** [comment]
Hi @jtommy 
https://buefy.org/documentation/carousel/ is exactly what I have in mind.
