### ISSUE TITLE
Vue3  "provide" and / or composable for programmatic usage

### ISSUE THREAD

**Issue by cimchd** [oruga-ui/oruga#168]
### Description

With Vue 2 Options-API programmatic usage of oruga was possible with a global $-instance (this.$oruga). In Vue 3 in combination with Composition-API the provide/inject pattern and / or some composables would be better.

### Why Oruga need this feature

Using the Composition-API a lot of code has no access to the this-context of the component. Therefore the $oruga-instance is not accessible in those situations.

**Comment by jtommy** [comment]
@cimchd can you make an example?
Btw there is in plan to rewrite using composition API but I don't think it's a mandatory way given that Vue 3 support options API too

**Comment by cimchd** [comment]
Sure, here is an example:

**OptionsAPI:**
```vue
<script>
export default {
  mounted() {
    // this context available
    this.$oruga.modal.open(...);
  }
}
</script>
```

**CompositionAPI:**
```vue
<script>
import { onMounted } from 'vue';

export default {
  setup() {
    onMounted(() => {
      // no this context
      this.$oruga.modal.open(...); // fails
    })
  }
}
</script>
```

**CompositionAPI with povide/inject:**
```vue
<script>
import { inject, onMounted } from 'vue';

export default {
  setup() {
    const oruga = inject('oruga');
    onMounted(() => {
      oruga.modal.open(...);
    })
  }
}
</script>
```

**CompositionAPI with composable:**
```vue
<script>
import { onMounted } from 'vue';
import { useProgrammatic } from '@oruga-ui/oruga-next'

export default {
  setup() {
    const oruga = useProgrammatic();
    onMounted(() => {
      oruga.modal.open(...);
    })
  }
}
</script>
```

I found a working solution with a named import of ModalProgrammatic for the modal. But I would prefer one of the solutions above.

**Comment by jtommy** [comment]
Do you want to make a PR about it?

**Comment by cimchd** [comment]
> Do you want to make a PR about it?

Sure, just give me some time... :-)

**Comment by cimchd** [comment]
If this is ok for you, it was just a one-liner. I reused the `$oruga` instance in `app.config.globalProperties` for provide.

**Comment by jtommy** [comment]
Great!!
And what about programmatically components https://github.com/oruga-ui/oruga/blob/f7456e215c413b6b9ab79c8053e53b84f7712157/packages/oruga-next/src/components/notification/index.ts#L56?

**Comment by cimchd** [comment]
> Great!!
> And what about programmatically components
> 
> https://github.com/oruga-ui/oruga/blob/f7456e215c413b6b9ab79c8053e53b84f7712157/packages/oruga-next/src/components/notification/index.ts#L56
> 
> ?

This would need the described reafctoring of the registerComponentProgrammatic function. Something like this?
```ts
export const registerComponentProgrammatic = (app: App, property: string, component: any) => {
  // use composable for unified access to global state object
  const { oruga, addProgrammatic } = useProgrammatic();

  // add component (manipulates the reactive oruga object)
  addProgrammatic(property, component);

  // provide oruga object, only needed once if oruga object stays reactive
  if (!app._context.provides?.oruga) app.provide('oruga', oruga);

  // add $-instance, only needed once if oruga object stays reactive
  if (!app.config.globalProperties.$oruga) app.config.globalProperties.$oruga = oruga;
  
  // possibly not needed anymore if oruga object stays reactive
  // app.config.globalProperties.$oruga[property] = component
}
```

**Comment by jtommy** [comment]
It looks correct

**Comment by cimchd** [comment]
Should I make another PR or is it better to wait for your rewrite using composition API?
