### ISSUE TITLE
`allowDuplicates` check not work when `createItem` function is passed as a prop

### ISSUE THREAD

**Issue by mscalessio** [oruga-ui/oruga#172]
Hi there, 
as mentioned in the title the `allowDuplicates` check doesn't work when custom `createItem` function is passed.
 
https://github.com/oruga-ui/oruga/blob/e1cd63bc4f17657c56ac520b0a7ac54236a87f13/packages/oruga/src/components/inputitems/Inputitems.vue#L364

You should changes this line 
```
const add = !this.allowDuplicates ? this.items.indexOf(itemToAdd) === -1 : true
```

to 

```
const add = !this.allowDuplicates ? this.items.indexOf(this.createItem(itemToAdd)) === -1 : true
```

in order to check the same format of the object pushed into the array.

Hope this can help.
Thank you!

**Comment by jtommy** [comment]
Good catch!
Do you want to submit a PR?

**Comment by astagi** [comment]
Hi @mscalessio thanks for this! I'd like to include this fix in the next release, do you prefer to submit a PR or I'll include your fix in the code by myself?

**Comment by astagi** [comment]
@mscalessio I'm going to release a new version, I added this line by myself. Thank you for your contribution!
