### ISSUE TITLE
Button component styles not working on Safari if tag is router-link/nuxt-link

### ISSUE THREAD

**Issue by adrianogiannacco** [oruga-ui/oruga#173]
Hello,
when using the Button component, I found out that the attribute `type="button"` stays on the anchor tag even if the specified tag is a `router-link`, or a `nuxt-link` (in case you're on Nuxt JS).
The presence of this attribute causes troubles with the style of the anchor tag on Safari.

I think that a change could be done on line 170 of the Button component, changing this:

```
computedNativeType() {
  if (this.tag === 'a') {
      return
  }
  return this.nativeType
}
```

to this:

```
computedNativeType() {
  if (this.tag === 'a' || this.tag === 'router-link' || this.tag === 'nuxt-link'  ) {
      return
  }
  return this.nativeType
}
```

I hope this can help.
Thank you very much,

Adriano

**Comment by jtommy** [comment]
@adrianogiannacco you're right, probably we should invert the condition to

```
computedNativeType() {
  if (this.tag === 'button' || this.tag === 'input'  ) {
      return this.nativeType
  }
  return
}
```
