### ISSUE TITLE
Modal overlay sometimes lingers after modal is closed quickly

### ISSUE THREAD

**Issue by lsnow99** [oruga-ui/oruga#174]
### Overview of the problem
Sometimes when using a modal, the overlay continues to cover the page, even after the modal is closed. Most frequently seems to occur if the modal is quickly closed after opening.

**Oruga** version: 0.4.3
**Vuejs** version: 3.1.5
**OS/Browser**: Linux/Firefox

### Description

The page no longer responds to clicks in some cases if the modal is closed to quickly. 

### Steps to reproduce

The best way to reproduce this is to just quickly open and close a modal. This can happen if the user accidentally double clicks something that opens the modal. The modal overlay should not respond to clicks to close the modal until after the animation is completed 

### Expected behavior

Page is interactable

### Actual behavior

Cannot interact with page

**Comment by astagi** [comment]
Hi @lsnow99 I'm not able to reproduce your issue as you can see in the following screen recording


https://user-images.githubusercontent.com/537363/128765584-d96c89cf-caae-4eab-a473-f9f6b56dc76d.mov


Could you please share your code or deploy it somewhere in order to test it?
