### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by miladmeidanshahi** [oruga-ui/oruga#176]
### Description
Most popular UI frameworks nowadays support RTL.

### Why Oruga need this feature

Because Oruga will save RTL users and i think oruga has potential to grow up fast.

**Comment by jtommy** [comment]
@miladmeidanshahi you should be able to do it by yourself. Are there some things to change in the default style CSS (lite) ?

**Comment by astagi** [comment]
@miladmeidanshahi any update?
