### ISSUE TITLE
Filter classes, rather than add or override them individually

### ISSUE THREAD

**Issue by sambedingfield** [oruga-ui/oruga#184]
I found myself in a position where I love the Oruga functionality and depth of components, but I didn't want to add anymore CSS or SCSS to my app (I already have base styles and animations), and I just wanted to include the components as truly naked! 👀

I was planning on using Oruga's override method so that I can use my own CSS naming methodology, but I then had to write hundreds of lines of code to achieve this, whilst the default class names of Oruga only needed tweaking. 

### Description

When using Oruga and using your own CSS classes you can either:
- Add classes to each component and their children and variants.
- Override classes to each component and their children and variants.

If you are adding Oruga to a project which has a different CSS naming methodology, both of the current solutions require that you lookup and manipulate all classes independently through the config or component props.

### Possible solution

A "filter" method within the configuration, could allow you to pass a function that returns the class name.
This would allow you to use simple replace or regex against all Oruga class names, once.

### Example
 
Here's three examples demonstrating the above:

https://gist.github.com/sambedingfield/e1766e97a79fbb123941cea1e22375de

1. Default Oruga class names.
2. Overriding the Oruga class names.
3. Filtering the Oruga class names.

### Pros and cons
(+) Can easily update methodology of all components at once.
(+) Can continue to use Oruga documents for functionality and classes.
(+) Allows for truly naked components, but unlike `override: true`, you have all custom classes already set.
(+) I _think_ it should be a relatively small change to implement and have no impact if not used
(-) Performance hit if complex regex used.
(-) It's only within Oruga's scope to use "Default CSS" or "Full CSS", not "No CSS".

**Comment by jtommy** [comment]
@sambedingfield the Oruga's scope is to allow you an easy way to style a component without knowing the structure of itself (HTML tags) and to help you to do it, as you can see in the docs, there is an **Inspector** for each component.

- Of course, you'll be lucky customizing a simple component (button, input) but looking forward to dropdown, datepicker?
- Are you sure that your "base style" is compliant with the structure of a component?
- Also are you sure to cover all default classes in order to support the same features (all or a part of them)? 
- Probably you'll be forced to read the SCSS/CSS file of each Oruga component, then what's the added value?

Your implementation of the filter is probably right for Oruga core but looking at your need it's like a "postcss" plugin and you might use it with no matter UI library, don't you?

I don't mean to trash your need and idea 😃 but I would like to discuss about it in order to understand what's the right direction.

**Comment by sambedingfield** [comment]
@jtommy my intent was to simply wrap each premade Oruga component in a Vue file, so that I could then include any additional functionality and _all_ dependant styles within that single file. Those files then sit neatly beside my custom ones too, so that I can lazy load and configure them per project.

I understand that isn't the original intent of Oruga, but it has worked very well for me and having a filter has proven to be a much better alternative than using `override: true` - which is why I think it's worth discussing.

> you'll be lucky customizing a simple component (button, input) but looking forward to dropdown, datepicker?

The same could be said with `override: true`, which you support. A filter is a step forward, because your classes are already set - you now only need to write your styles.

> Are you sure that your "base style" is compliant with the structure of a component?

My base style is component agnostic. I choose to include _all_ component style dependencies (including the equivalent to Oruga's default CSS) within the same component file so that they only get included when tree-shaking - something I can see that's on your roadmap.

> Also are you sure to cover all default classes in order to support the same features (all or a part of them)?

I do! We're getting a bit off topic here, but I like to replace all my Oruga default styles with the equivalent of Tailwinds `@apply`, which then includes my Tailwind's theme extended colours and variations. This removes the need to use any SCSS variables or convert them (ie: `$primary: theme('colors.primary')`).

> Probably you'll be forced to read the SCSS/CSS file of each Oruga component, then what's the added value?

Yes, it does take time to research and style components, but I only ever need to do this once for all future projects, and I get to learn about each Oruga's component thoroughly!

The added value of using Oruga like this, is that I get the depth of functionality and structure that it provides, which happily sits outside of my Vue app, so that I can focus on styling components - like the beautiful butterfly Oruga wants to be! 🦋

**Comment by jtommy** [comment]
@sambedingfield Although we don't understand well your approach and the advantage we are going to add that feature in the core code because we really appreciate your energy and motivation.
We'll add a filter method global and for each component but probably we won't use "filter" as name, any hints?

**Comment by sambedingfield** [comment]
> we won't use "filter" as name, any advices?

How about `metamorphosis`? 😂

Maybe `classFilter` or something?

I did start to think what would happen if instead of introducing a new variable, you could just pass a function to `override` instead of a Boolean? Or is that a bad idea?

**Comment by astagi** [comment]
@sambedingfield allowing `override` to support functions might lead users to confusion, `override` is used to remove or keep default Oruga's classes, `metamorphosis` function (it sounds cool 😁 ) should allow users to rename applied classes.

**Comment by astagi** [comment]
@sambedingfield #193 implements your request, please check it out and let me know 😃
