### ISSUE TITLE
Custom notification with a component with dependencies doesn't work

### ISSUE THREAD

**Issue by astagi** [oruga-ui/oruga#189]
### Overview of the problem

**Oruga** version: [0.4.X]
**Vuejs** version: [2.X.X]
**OS/Browser**: All

### Description

If you instantiate a component that customizes notifications, it doesn't load all dependencies (ie $i18n)

### Steps to reproduce

1. Customize a notification with a component that has dependencies
2. Fire notification programmatically

### Expected behavior

Custom notification doesn't throw errors

### Actual behavior

Custom notification throws errors (can't find dependencies)

**Comment by jtommy** [comment]
It works, only missing `parent: this` in the example
