### ISSUE TITLE
Fast clicking breaks modal

### ISSUE THREAD

**Issue by ymebrugts** [oruga-ui/oruga#190]
https://github.com/oruga-ui/oruga/issues/174

See video below

**Overview of the problem**
Sometimes when using a modal, the overlay continues to cover the page, even after the modal is closed. Most frequently seems to occur if the modal is quickly closed after opening.

Oruga version: 0.4.4
Vuejs version: 3.2.11
OS/Browser: Windows/Chrome

**Description**
The page no longer responds to clicks in some cases if the modal is closed to quickly.

**Steps to reproduce**
The best way to reproduce this is to just quickly open and close a modal. This can happen if the user accidentally double clicks something that opens the modal. The modal overlay should not respond to clicks to close the modal until after the animation is completed

`

		<o-modal v-model:active="isImageModalActive" scroll="clip" contentClass="modal-popup">

			<h2 style="color: #000; font-weight: bold; font-size: 22px">Why TAU?</h2>
			<p style="color: #000">
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dapibus elementum molestie. Aliquam erat volutpat. Phasellus ultricies nunc et faucibus maximus. Pellentesque sed
				ligula faucibus, dapibus diam vitae, bibendum sem.
			</p>
			<p style="color: #000">Nullam lacinia tortor a venenatis ullamcorper. Nam vulputate lacus nibh, ut accumsan nunc aliquam in. Nam congue vitae diam nec viverra.</p>
			<Button text="Close" style="display:block; margin:0 auto;" :color="lamdenblue"></Button>
		</o-modal>
`

[Example video](https://www.youtube.com/watch?v=cm4w_gggB9E)

Expected behavior
Page is interactable

Actual behavior
Cannot interact with page

**Comment by jtommy** [comment]
@ymebrugts oruga or oruga-next (vue 3) ?

**Comment by ymebrugts** [comment]
Oruga next because I use Vue3
