### ISSUE TITLE
disabled="false" html attr breaks `.button[disabled]` selector

### ISSUE THREAD

**Issue by neon64** [oruga-ui/oruga#191]
### Overview of the problem

**Oruga-Next** version: 0.4.4
**Vuejs** version: 3.2.8
**OS/Browser**: Firefox 92 on Linux

### Description

As can be seen in this code, the `<o-button>` component passes the `disabled` prop onto the underlying element.

https://github.com/oruga-ui/oruga/blob/180e8b0515205cbf8f926d9cbcc5051ee225f8d4/packages/oruga-next/src/components/button/Button.vue#L2-L8

This interacts badly with stylesheets which use selectors like `.button[disabled]` to show a "disabled" look for the button. In particular, it appears to break https://github.com/oruga-ui/oruga-bulma (though I'm not sure oruga-bulma is at fault, since using `[disabled]` as a CSS selector is fairly common.

### Steps to reproduce

1. Using Oruga-Next and Vue3, and, in my particular case, using https://github.com/oruga-ui/oruga-bulma (though I don't believe that is necessary to encounter this issue)
2. The following code
```html
<o-button tag="a" href="/">Go back to homepage...</o-button>

<!-- or equivalently... -->
<o-button tag="router-link" to="/">Go back to homepage...</o-button>
```
3. html attributes contain `disabled="false"`
4. selectors like `.button[disabled]` get triggered even though the button is not disabled

### Expected behavior

`disabled="false"` should not be set when the button's `tag` is just a plain HTML tag. Since `disabled` is a boolean attr, it should just be left off, so then `[disabled]` CSS-selector won't match.

### Actual behavior

the `.button[disabled]` selector matches, so the button looks greyed-out as shown below:

![2021-09-13T19:53:36,032107319+10:00](https://user-images.githubusercontent.com/7961339/133063636-06dacedf-b00f-4142-838d-fbbb9b63c11e.png)

**Comment by jtommy** [comment]
@neon64 you are right, there is something different between Vue 2 and Vue 3 because the same code generates a different DOM. In the first case it doesn't add the attribute disabled when value is false.
I'll take a look in order to set undefined value when is false or check if is a common issue/change on Vue 3.

**Comment by jtommy** [comment]
https://v3.vuejs.org/guide/migration/attribute-coercion.html#overview
