### ISSUE TITLE
Formatting DateTime objects on the table component

### ISSUE THREAD

**Issue by Code-Hell** [oruga-ui/oruga#192]
Hello there!

I'm using the table component to display products data, which has some date fields. Oruga is great and suits my needs very well.

**Before Oruga**, these objects used to be formatted on demand using a method (using Luxon 2.0.2):
`formattedDate(date) {return DateTime.fromISO(date).toFormat("HH:mm dd/MM/yy")}`
And displayed on the template like this:
`<td>{{ formattedDate(product.creationDate) }}</td>`

This is the **current state** of the display, without formatting:
![image](https://user-images.githubusercontent.com/90486687/133611493-4c3c9847-7fa8-4607-8196-c95c13dcda96.png)

Is possible to format these objects impromptu, for display purposes only?

**Oruga 3**: v.0.4.4
**Nuxt**: 2.15.7
**OS/Browser**: Ubuntu 20.04.3 LTS

Thank you in advance.

**Comment by astagi** [comment]
hey @Code-Hell really happy to hear that you like Oruga! [Async-data example in Table documentation](https://oruga.io/components/table.html#async-data) may help you, it formats date fields for the column "Release date".

Hope it helps! Let me know

**Comment by Code-Hell** [comment]
I changed from the [Base example ](https://oruga.io/components/table.html#base) syntax to your example and solved my issue.

Thank you very much @astagi!

**Comment by astagi** [comment]
Sounds great @Code-Hell 🙌 

Happy coding with Oruga 🐛
