### ISSUE TITLE
HOW CAN I RUN THE PROJECT LOCALLY?

### ISSUE THREAD

**Issue by mouadTaoussi** [oruga-ui/oruga#197]
### Description

When I cloned the project last month, I cannot figure out how to run it locally in my computer.
the docs should include the steps to run it successfully.
### Why Oruga need this feature

To allow new contributors integrate into the project.

**Comment by jtommy** [comment]
@mouadTaoussi https://github.com/oruga-ui/oruga/blob/develop/.github/CONTRIBUTING.md

Thanks for the future contributions 😉

**Comment by mouadTaoussi** [comment]
Thanks!
