### ISSUE TITLE
Feature: add types for programmatic components

### ISSUE THREAD

**Issue by jtommy** [oruga-ui/oruga#205]
Add types for programmatic components:

- Loading
- Modal
- Notification

**Comment by mouadTaoussi** [comment]
@jtommy Nice! I'm gonna start work on **Oruga** Framework after PR one in buefy

**Comment by astagi** [comment]
@mouadTaoussi are you going to take care of this task? in that case I can assign it to you

**Comment by astagi** [comment]
Any help would be really appreciated :) feel free to work on that and increment your PRs collection for #hacktoberfest 🎃

**Comment by mouadTaoussi** [comment]
@astagi Thanks for the assignment and for any future Help!
I might ask you If I found something weird, because it's gonna be my first contribution 😁

**Comment by jtommy** [comment]
@mouadTaoussi did you read https://github.com/oruga-ui/oruga/blob/develop/.github/CONTRIBUTING.md? 

I meant types like https://github.com/buefy/buefy/tree/dev/types

**Comment by mouadTaoussi** [comment]
@jtommy  How you run it locally ?

**Comment by jtommy** [comment]
You should try it on your local project with TS
