### ISSUE TITLE
App already provides property with key "oruga". It will be overwritten with the new value.

### ISSUE THREAD

**Issue by neon64** [oruga-ui/oruga#206]
### Overview of the problem

**Oruga** version: Oruga-Next v0.4.5
**Vuejs** version: 3.2.20
**OS/Browser**: Firefox on Linux, or through Vue Test Utils v2.0.0

### Steps to reproduce

1. load Oruga into app using `Vue.use(Oruga)` or inside tests using:

```
import Oruga from "@oruga-ui/oruga-next";

let wrapper = mount(SomeComponentWhichNeedsOruga, { global: { plugins: [Oruga] } });
```

2. A warning should be emitted

### Expected behavior

No warnings from loading Oruga into a Vue.js application

### Actual behavior

A warning message is emitted to the console:

```
[Vue warn]: App already provides property with key "oruga". It will be overwritten with the new value.
```

This appears to be harmless, but it just adds to the noise of the console, especially when running component tests using Vue Test Utils
![2021-10-12T14:38:42,324373442+11:00](https://user-images.githubusercontent.com/7961339/136887328-ce237652-528c-4736-a684-1b3950998035.png)

I'm fairly new to Oruga in general though, so its possible that I have just misconfigured it within my application. (the warning seems to imply Oruga is being loaded more than once, perhaps?)

**Comment by jtommy** [comment]
You are right, there is a duplicated "provide"

Just fixed: https://github.com/oruga-ui/oruga/commit/ded8c6db45f8f3960606241d7672397111872a9a

**Comment by modularcoder** [comment]
@jtommy thanks! This warning was polluting my jest test a lot! Looking forward to the new release! :)

**Comment by jtommy** [comment]
@modularcoder hey mate, happy to know you are using it 😉
