### ISSUE TITLE
Can't get autocomplete component to work

### ISSUE THREAD

**Issue by hugohabicht01** [oruga-ui/oruga#207]
### Overview of the problem

**Oruga** version: ^0.4.5
**Vuejs** version: ^3.2.16
**OS/Browser**: Mac OS Big Sur / Brave

### Description

I just tried to get the autocomplete component working and it wouldn't display any suggestions as well as log a bunch of warnings in the console. To narrow down the issue I tried the same with the example code from the documentation in a newly generated vitejs vue 3 project and it didn't work either. Therefore I relatively certain that the issue lies within oruga itself. 

### Steps to reproduce
I pushed the not working code in a temporary repo within a newly generated vite project, therefore you can just clone [https://github.com/hugohabicht01/tmp](https://github.com/hugohabicht01/tmp), run `yarn`, then `yarn dev` and visit [http://localhost:3000](http://localhost:3000).
The code provided there is basically just the first example from the documentation about the autocomplete component,
```js
<template>
  <section>
    <p class="content"><b>Selected:</b> {{ selected }}</p>
    <o-field label="Find a JS framework">
      <o-autocomplete rounded expanded v-model="name" :data="filteredDataArray" placeholder="e.g. jQuery" icon="search" clearable @select="option => selected = option">
        <template slot="empty">No results found</template>
      </o-autocomplete>
    </o-field>
  </section>
</template>

<script>
  export default {
    data() {
      return {
        data: ['Angular', 'Angular 2', 'Aurelia', 'Backbone', 'Ember', 'jQuery', 'Meteor', 'Node.js', 'Polymer', 'React', 'RxJS', 'Vue.js'],
        name: '',
        selected: null
      }
    },
    computed: {
      filteredDataArray() {
        return this.data.filter(option => {
          return (
            option
              .toString()
              .toLowerCase()
              .indexOf(this.name.toLowerCase()) >= 0
          )
        })
      }
    }
  }
</script>
```
### Expected behavior
When typing `jquery` into the input field, a bunch of suggestions should show up, just like in the documentation [https://oruga.io/components/autocomplete.html](https://oruga.io/components/autocomplete.html).

### Actual behavior
Instead no suggestions showed up and the following warnings were logged in the console: 
```
[Vue warn]: App already provides property with key "oruga". It will be overwritten with the new value.
Vue warn]: Property "ariaAutocomplete" was accessed during render but is not defined on instance. 
  at <OAutocomplete rounded="" expanded="" modelValue=""  ... > 
  at <OField label="Find a JS framework" > 
  at <App>
[Vue warn]: Property "ariaAutocomplete" was accessed during render but is not defined on instance. 
  at <OAutocomplete rounded="" expanded="" modelValue="j"  ... > 
  at <OField label="Find a JS framework" > 
  at <App>
runtime-core.esm-bundler.js:6568 [Vue warn]: Property "ariaAutocomplete" was accessed during render but is not defined on instance. 
  at <OAutocomplete rounded="" expanded="" modelValue="jq"  ... > 
  at <OField label="Find a JS framework" > 
  at <App>
```

I'm looking forward to any suggestions how this could be fixed (in case its an issue on my side...)

**Comment by jtommy** [comment]
They are only warnings and we fixed it right now (available in the next release).
I checked your project and there is an error, you have to use `<template #empty>`.

**Comment by jtommy** [comment]
The docs works with Vue 2 at the moment.
There is already an issue to update it.
