### ISSUE TITLE
Icon not displayed on any components (Table, Button) with oruga-next and Vue3

### ISSUE THREAD

**Issue by loutfina** [oruga-ui/oruga#209]
### Overview of the problem

**Oruga** version: [0.4.5]
**Vuejs** version: [3.0.0]
**OS/Browser**: Chrome

### Description

I use @oruga/oruga-next with my Vue3 project. I use the components Table, Button and Icon. With Icon and pack  it works (<o-icon pack="fas" icon="power-off" /> --> display icon power-off) but none of theinternal icons appear ...nor Icon inside a button doesn't appears (<o-button variant="primary" v-on:click="search" icon-left="plus">Rechercher</o-button>) eather the sort or loading icon in the Table component.

    <o-table
      :data="result ? result.coverages : []"
      :paginated="false"
      :per-page="perPage"
      :current-page="currentPage"
      :pagination-simple="false"
      :pagination-position="'bottom'"
      :default-sort-direction="'asc'"
      :sort-icon="'arrow-up'"
      :sort-icon-size="'medium'"
      :loading="status=='pending'"
      :narrowed="true"
      :striped="true"
      default-sort="creationDate">
      <o-table-column field="creationDate" label="Date" sortable position="centered" v-slot="props">
        {{ new Date(props.row.creationDate).toLocaleDateString() }}
      </o-table-column>
      <o-table-column field="name" label="Name" sortable position="centered" v-slot="props">
        {{ props.row.name }}
      </o-table-column>
    </o-table>

### Steps to reproduce

1- create projet with Vue-cli and chose version 3.0 of vue, typescript, vuex, router
2- add oruga-next (using yarn add) and font awesome
Here is my final package.json
`{
  "name": "MyOruga-front",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.36",
    "@fortawesome/free-brands-svg-icons": "^5.15.4",
    "@fortawesome/free-regular-svg-icons": "^5.15.4",
    "@fortawesome/free-solid-svg-icons": "^5.15.4",
    "@fortawesome/vue-fontawesome": "^2.0.2",
    "@mdi/js": "^6.2.95",
    "@oruga-ui/oruga-next": "^0.4.5",
    "@popperjs/core": "^2.10.2",
    "bootstrap": "^5.0.0-beta3",
    "core-js": "^3.6.5",
    "mdi-vue": "^3.0.7",
    "vue": "^3.0.0",
    "vue-class-component": "^8.0.0-0",
    "vue-router": "^4.0.0-0",
    "vuex": "^4.0.0-0"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^4.18.0",
    "@typescript-eslint/parser": "^4.18.0",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-typescript": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "@vue/eslint-config-typescript": "^7.0.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0",
    "node-sass": "^4.12.0",
    "sass-loader": "^8.0.2",
    "typescript": "~4.1.5"
  }
}`
3- import oruga and font-awesome in the application
Here is my main.ts file
`import { createApp } from 'vue'
import App from './App.vue'
import router from './router'
import store from './store'

import Oruga from '@oruga-ui/oruga-next'
import '@oruga-ui/oruga-next/dist/oruga-full-vars.css'

import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { fas } from '@fortawesome/free-solid-svg-icons'
library.add(fas);
import { fab } from '@fortawesome/free-brands-svg-icons';
library.add(fab);
import { far } from '@fortawesome/free-regular-svg-icons';
library.add(far);
import { dom } from "@fortawesome/fontawesome-svg-core";
dom.watch();

import 'bootstrap/dist/css/bootstrap.css';

const app = createApp(App).use(store).use(router);
app.component("vue-fontawesome", FontAwesomeIcon);
app.use(Oruga)
app.mount('#app')

import 'bootstrap/dist/js/bootstrap.js';`

4- Create a page with a button having a icon or a table with sortable colomn.
 

### Expected behavior

Normaly, sortable colomn have a arrow-up icon to show the sorting direction.
Normaly, a Loading spinner appear on the backdrop of the table
Normaly, Button show an icon insead

### Actual behavior

The sortable colomns doesn't have any icon to show the sorting direction.
When data is lodaing, the backdrop appear on the table but without the spinner
Button don't have any icon

**Comment by jtommy** [comment]
Looking your code you are not setting FontAwesome component into Oruga config https://oruga.io/components/Icon.html#custom-icon-component
