### ISSUE TITLE
[Feature Request]: Colors Palette are not cool for the framework

### ISSUE THREAD

**Issue by mouadTaoussi** [oruga-ui/oruga#210]
### Description
Dark colors are not good for the Framework since many of them are using light colors for attractiveness and good UI look (Excluding Primary)

### Why Oruga need this feature
a good color palette might attracts you to use a UI Framework

Here are the chosen color palettes (variants **danger-warning-success-info** are ordered **respectively**)
**Note:** You can create your own palette if you like from the following colors from each palette, by your choice! if you didn't liked the combinations.

# A
![Web capture_20-10-2021_13470_color adobe com](https://user-images.githubusercontent.com/50294614/138099988-9aa71c22-f53a-468c-80ff-dc7ff57e86e9.jpeg)

# B
![Web capture_20-10-2021_13498_color adobe com](https://user-images.githubusercontent.com/50294614/138100043-a2f18861-38d8-486f-ad47-0f68c4f96420.jpeg)

# C 
**Note:** I Have changed the variant of the **primary** one to brighter one, **You can add it to the above ones**
![Web capture_20-10-2021_135140_color adobe com](https://user-images.githubusercontent.com/50294614/138100218-171ac4d0-36fc-4813-a6b9-13e5bbee00e2.jpeg)

# Here is a preview of the colors on Noticication;Button Components:
![Web capture_23-10-2021_211216_localhost](https://user-images.githubusercontent.com/50294614/138570180-0ac04157-1723-437f-81e9-292c79e4705a.jpeg)
![Web capture_23-10-2021_205246_localhost](https://user-images.githubusercontent.com/50294614/138569734-9ff70a9a-8ae4-4f04-be79-fcc5aa906f6b.jpeg)

**Comment by mouadTaoussi** [comment]
@jtommy in my opinion in the scope would be better, **many of the components would looks cool**, and when the developer use it with no need to touch variables.
he can change them by him color palette

**Comment by jtommy** [comment]
Ok, let us see your palette and we'll think to add it

**Comment by mouadTaoussi** [comment]
@jtommy  I'm gonna find good variants for (success-danger-info-warning)
