### ISSUE TITLE
Documentation error for CDN 

### ISSUE THREAD

**Issue by pac0rro** [oruga-ui/oruga#213]
Hi all.

First: awesome UI library for Vue!!! Congratulations.

Documentation says that oruga script and css is located at these CDN URLs:

```css
<link rel="stylesheet" href="//unpkg.com/oruga/dist/oruga.min.css" />
<script src="//unpkg.com/oruga/dist/oruga.min.js"></script>
```

However the links are broken.

Its possible to use https://oruga.io/cdn/oruga.js but it seems like the Vue2 version.

Is there any valid URL for Vue3 Oruga CSS and JS?

Regards.

**Comment by jtommy** [comment]
@pac0rro thanks a lot 😃 

> https://unpkg.com/@oruga-ui/oruga-next/dist/oruga.min.js
> 
> https://unpkg.com/@oruga-ui/oruga-next/dist/oruga.min.css
