### ISSUE TITLE
Comments in horizontal fields render empty inner fields

### ISSUE THREAD

**Issue by MaTTze** [oruga-ui/oruga#226]
### Overview of the problem

**Oruga** version: oruga-next@0.4.6
**Vuejs** version: 3.2.20
**OS/Browser**:

### Description

A html-comment in a horizontal field leads to an additional empty inner field. 
![grafik](https://user-images.githubusercontent.com/4118302/139496029-dac09f6e-64dc-47f4-89f8-a141b5884ccb.png)
I think this came with commit 5338da4.
My local fix is a `if (element.type.description === "Comment") {return element;}` in `OFieldBody::render()`. 
That works, but I'm not sure this I a bulletproof fix.

### Steps to reproduce

```
<template>
  <div id="app">
    <o-field horizontal  variant="danger" message="Selected subject is wrong">
      <!-- Label left empty for spacing -->
      <o-button variant="primary">
        Send message
      </o-button>
    </o-field>
  </div>
</template>
```

### Expected behavior

Horizontal field should ignore comments.

### Actual behavior

Horizontal field render a empty field for each comment.

**Comment by jtommy** [comment]
Good catch, we have to find a better way to skip comment like Vue 2
