### ISSUE TITLE
Add event for modal fully opening

### ISSUE THREAD

**Issue by jcs224** [oruga-ui/oruga#227]
### Description

When opening a modal, fire an event that states the modal is completely open and the open animation has completed. The following is a screenshot of my ultimate desired behavior. Note the auto-focus after modal is loaded.

![Dockertron example](https://raw.githubusercontent.com/jcs224/dockertron/master/promo/dockertron.gif)

### Why Oruga need this feature

For example, in the case where a form is inside of a modal, it would be nice to automatically set the input focus on the first form field of the modal. I can't figure out how to do this with current events or props. 

I think simply forwarding the `after-enter` transition event would be enough. Maybe call the event `opened` or something?

**Comment by jtommy** [comment]
Why don't you set the focus using onMounted hook on your form component?

**Comment by jcs224** [comment]
Just tried those things, now it works, thanks.
