### ISSUE TITLE
o-input search box icon overlap placeholder

### ISSUE THREAD

**Issue by tanhs** [oruga-ui/oruga#228]
### Overview of the problem

**Oruga** version: [0.4.6]
**Vuejs** version: [3.2.20]
**OS/Browser**: Firefox 93.0

input search box icon overlap placeholder

### Steps to reproduce

```
<o-input
	v-model="search"
	placeholder="Search..."
	type="search"
	icon="search"
	icon-clickable
	@icon-click="searchIconClick"
>
</o-input>
```

### Expected behavior

1.  Search icon should not overlap placeholder

### Actual behavior

The search icon is overlapping the placeholder
picture attached.
--
![Screen Shot 10-31-21 at 10 56 PM](https://user-images.githubusercontent.com/1995229/139589535-2d5babb9-d091-4c8c-85ce-de56926250fd.PNG)
![Screen Shot 10-31-21 at 10 55 PM](https://user-images.githubusercontent.com/1995229/139589540-22cf4f87-ff22-4685-887b-82ba221d2f62.PNG)
![Screen Shot 10-31-21 at 10 56 PM 001](https://user-images.githubusercontent.com/1995229/139589541-a8d2186f-ff61-43b6-9257-2d9b95e75097.PNG)
>

**Comment by jtommy** [comment]
The default oruga.css is really minimal so you have manage padding as you prefer, check out https://oruga.io/documentation/#examples
