### ISSUE TITLE
Center icon in .o-notification__close

### ISSUE THREAD

**Issue by rubjo** [oruga-ui/oruga#231]
### Suggestion

Horizontally and vertically center notification close button.

From:
<img width="125" alt="Skjermbilde 2021-11-05 kl  10 16 21" src="https://user-images.githubusercontent.com/42270947/140487173-891df84f-4f69-4cbf-a46c-0df5f7f5cfe8.png">
```CSS
display: inline-block;
```

To:
<img width="125" alt="Skjermbilde 2021-11-05 kl  10 16 00" src="https://user-images.githubusercontent.com/42270947/140487195-bd6d1429-471c-446c-a227-8f8e6265e32b.png">
```CSS
display: flex;
justify-content: center;
align-items: center;
```

**Comment by jtommy** [comment]
@rubjo sure, you can make a PR!
