### ISSUE TITLE
Modal doesn't cover full screen and can't reopen

### ISSUE THREAD

**Issue by tanhs** [oruga-ui/oruga#233]
### Overview of the problem

**Oruga** version: [0.4.6]
**Vuejs** version: [3.2.20]
**OS/Browser**: Firefox 93.0

### Description
1.  Modal dialog not over the full screen
2.  Upon opening the dialog, Close doesn't change the prop "active" doesn't change to "false"

### Steps to reproduce
App.vue
```
<template>
    <div class="container">
        <MenuMain />
        <router-view />
    </div>
</template>
```
MenuMain
```
<template>
	<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
        .....
        <div class="d-flex flex-row-reverse">
      <o-button size="medium" variant="primary" @click="isImageModalActive = true">
        Open modal
      </o-button>

   <o-modal :active.sync="isImageModalActive">
      <p style="text-align: center">
        <img src="https://avatars2.githubusercontent.com/u/66300512?s=200&v=4" />
      </p>
    </o-modal>
```

### Expected behavior

1.  Modal dialog should cover full screen including the MenuMain
2.  Modal close should able to open again

### Actual behavior

1.  MenuMain seems to be in front of modal screen
2.  Close open Modal not able to Open again
![Screen Shot 11-06-21 at 02 16 PM 001](https://user-images.githubusercontent.com/1995229/140600484-4beba6af-3237-41a6-b5d8-5591b6d1db52.PNG)
![Screen Shot 11-06-21 at 02 16 PM](https://user-images.githubusercontent.com/1995229/140600485-6e064df7-e620-4281-ac92-582a8c4501bc.PNG)

**Comment by jtommy** [comment]
@tanhs can you reproduce on codepen or similar?
Are you using oruga.css?

**Comment by tanhs** [comment]
I am using oruga-full-vars.css
I tried to get the Oruga works in codepen but failed, may be I not something right.
The codes are almost there.
https://codepen.io/tan-hai-shi/pen/jOLzwXe

**Comment by jtommy** [comment]
Where is the modal?
Try to codesandbox because on codepen you can't write in this way

**Comment by tanhs** [comment]
https://codesandbox.io/s/magical-mountain-uwrtk?file=/src/components/MainMenu.vue

**Comment by jtommy** [comment]
@tanhs i don't understand well, where is the modal?
Anyway a quick hint: import oruga css before bootstrap CSS as described in the docs 😉 (it will be helpful during components customisation)

**Comment by tanhs** [comment]
https://codesandbox.io/s/magical-mountain-uwrtk?file=/src/components/MainMenu.vue
Sorry, the changes are not saved.  
1.  Click "Open Modal2" it open the Modal but I can still click on "Link" dropdown from menu
2.  I click any place to close the Modal, I click again on "Open Modal2" it doesn't open anymore
![Screen Shot 11-07-21 at 08 54 PM](https://user-images.githubusercontent.com/1995229/140645781-8e035f76-8b3a-4984-bc16-41c96690ae7d.PNG)

**Comment by jtommy** [comment]
You cannot use `.sync` because it has been removed in Vue 3, you have to use `v-model:active`
