### ISSUE TITLE
Exception when using Orgua Modal with composition API

### ISSUE THREAD

**Issue by amir20** [oruga-ui/oruga#240]
### Overview of the problem

**Oruga** version: [0.4.7] (oruga-next)
**Vuejs** version: [3.2.21]
**OS/Browser**:

### Description

When using Oruga Modal API, I get the following exception: 

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at Proxy.<anonymous> (Autocomplete-4b6f6b73.js:496)
```

### Steps to reproduce

```
const { oruga } = useProgrammatic();

oruga.modal.open({
    // parent: this,
    component: FuzzySearchModal,
    animation: "false",
    width: 600,
    active: true,
  });

```

Some debugging showed that `this.$refs.dropdown` is null. 

<img width="667" alt="Screen Shot 2021-11-12 at 1 57 23 PM" src="https://user-images.githubusercontent.com/260667/141539673-670016c6-b067-4ac5-8556-393cdc044dca.png">

Show the dialog, and then use `esc` to close it. The exception is thrown. 

### Expected behavior

For `esc` to not throw an exception. 

### Actual behavior

See above.

**Comment by jtommy** [comment]
Really strange that skips the first if condition, btw I think it happens when parent components is destroyed.

**Comment by amir20** [comment]
If condition is checking for undefined though. Not null.

**Comment by jtommy** [comment]
You can fix it with a PR 😉

**Comment by amir20** [comment]
I use `pnpm` for my project and am having a hard time try use `pnpm link`. Hopefully I can figure it out today.

**Comment by amir20** [comment]
I did confirm the bug does work and no errors are thrown.
