### ISSUE TITLE
Steps: wrong transition direction 

### ISSUE THREAD

**Issue by MaTTze** [oruga-ui/oruga#241]
### Overview of the problem

**Oruga** version: all
**Vuejs** version: all
**OS/Browser**:

### Description

The step content always transitions from right to left ever when clicking "prev".

### Steps to reproduce

Navigate through the steps in the Steps-Documentation/example 

### Expected behavior

The step content transitions from right to left ever when clicking "next" and from left to right when clicking "next".

### Actual behavior

The step content always transitions from right to left ever when clicking "prev".

**Comment by MaTTze** [comment]
I can prepare a PR if you want.

**Comment by jtommy** [comment]
Sure, thanks!
