### ISSUE TITLE
Tab type is not applied correctly

### ISSUE THREAD

**Issue by reskes** [oruga-ui/oruga#245]
### Overview of the problem

**Oruga** version: 0.4.7
**Vuejs** version: 3.0.0 (Using TypeScript)
**OS/Browser**: Chromium

### Description

The "Tab type"-prop and also config value seems to be ignored. It always shows the default type.

### Steps to reproduce

Create Tabs with "Tab type"-prop set to "toggle" or "boxed"
```
<o-tabs type="toggle">
...
```

### Expected behavior

Should have Look&Feel of Tab type "toggle" or "boxed"

### Actual behavior

Has Look&Feel of Tab type "default"

**Comment by jtommy** [comment]
@reskes what CSS are you using?
The default oruga.css is minimal and doesn't contain all types

**Comment by reskes** [comment]
I'm using this one: `oruga-next/dist/oruga-full.css`

**Comment by reskes** [comment]
@jtommy Thank you for the very quick response.
For me the latest fix didn't solve the issue.

Maybe I'm doing something wrong?
Here is an excerpt from my code:
`<o-tabs v-model="activeTab" type="toggle">
      <o-tab-item v-for="tab in tabs" :key="tab.id" :label="tab.title" :value="tab.id">
        <span >{{tab.helpText}}</span>
      </o-tab-item>
    </o-tabs>`

**Comment by jtommy** [comment]
@reskes Just tested and it works with `oruga-full.css` theme

**Comment by reskes** [comment]
I'm trying it out from scratch and have still the issues.

` <o-tabs type="toggle"> 
     <o-tab-item label="Pictures"> 
        <div></div>
      </o-tab-item>
      <o-tab-item label="Music">
        <div></div>
      </o-tab-item>
      <o-tab-item label="Videos">
        <div></div>
      </o-tab-item>
    </o-tabs>`

Becomes this:

`<div class="b-tabs" data-v-326520ca=""><nav class="tabs"><div class=""><a class="is-active"><!--v-if--><span class="">Pictures</span></a></div><div class=""><a class=""><!--v-if--><span class="">Music</span></a></div><div class=""><a class=""><!--v-if--><span class="">Videos</span></a></div></nav><section class="tab-content"><div class="tab-item" data-v-326520ca="" style=""><div data-v-326520ca=""></div></div><div class="tab-item" data-v-326520ca="" style="display: none;"><div data-v-326520ca=""></div></div><div class="tab-item" data-v-326520ca="" style="display: none;"><div data-v-326520ca=""></div></div></section></div>`

Excerpt of my used packages an versions:

_├── @oruga-ui/oruga-next@0.4.8
├── @oruga-ui/theme-bulma@0.1.4
├── bulma@0.9.3
├── vue@3.2.21_

**Comment by jtommy** [comment]
You are using Bulma theme, can you open an issue into the other repository?
It might be related to Bulma config and not Oruga internal code

**Comment by jtommy** [comment]
@reskes just released a new version of bulma theme that fix it ;)

**Comment by reskes** [comment]
@jtommy 
Thanks. I will check it out as soon as possible.
Did wrote a small CSS-hack as quick'n'dirty-fix and was looking forward to have some  time to look into the source of the issue. 
I'm happy you got it fixed in the meantime :)
