### ISSUE TITLE
Error on register component when try to test

### ISSUE THREAD

**Issue by Pablolgn** [oruga-ui/oruga#247]
### Overview of the problem

**Oruga** version: [0.4.6]
**Vuejs** version: [3.2.13]
**Jest** version: [27.1.0]
**OS/Browser**: Ubuntu

### Description

I get this error when testing files with oruga components. I tried test a component whit only a o-button and fails.

![oruga_bug](https://user-images.githubusercontent.com/36844424/142386589-d231c75a-a9ea-43d7-95fb-ff4b1fa38e35.png)

### Steps to reproduce

1. Create test for a file with some oruga component
2. Run test

### Expected behavior

Run test normally

### Actual behavior

Test are blocked by this error

**Comment by jtommy** [comment]
Can you share with us more code?
Keep in mind that the library exports Plugin using "treeshaking" way.

**Comment by Pablolgn** [comment]
https://codesandbox.io/s/blissful-bartik-qzcl5

This is an example of the error

**Steps to reproduce**
1. Open new terminal
2. `yarn jest --config tests/jest.config.js HelloWorld.spec.ts`

**Comment by jtommy** [comment]
@Pablolgn Your component uses Oruga so you have to init it in your test file.
Probably there are several ways to do it, you can check https://next.vue-test-utils.vuejs.org/migration/#no-more-createlocalvue.

For example:

```
import { mount } from '@vue/test-utils'
import   HelloWorld   from './HelloWorld.vue'

import Oruga from '@oruga-ui/oruga-next'

describe('Button.vue', () => {
  let wrapper

    wrapper = mount(HelloWorld, {
     global: {
        plugins: [Oruga]
     }
   })

	it('renders correctly', () => {

  })
})
```
