### ISSUE TITLE
RTL input status icon issue

### ISSUE THREAD

**Issue by ymgsmz** [oruga-ui/oruga#255]
### Overview of the problem

**Oruga** version: [0.4.8]
**Vuejs** version: [3.2]
**OS/Browser**: Any

### Description

Regarding https://github.com/oruga-ui/oruga/blob/develop/packages/oruga-next/src/components/input/Input.vue#L206,
the library only uses the right icon for setting the status icon which leads to an issue when the RTL direction is settled.

Please check screenshot:
<img width="301" alt="Screen Shot 2021-12-17 at 9 51 03 PM" src="https://user-images.githubusercontent.com/9605206/146590369-03e96daf-9252-4c21-97cb-6a0304f4bfe9.png">

### Temp Fix
Ensure removing icon would not impact the UI and set `statusIcon` => `false` in Oruga options when you create the App

### Expected behavior

Input should use the left icon for showing status icon

### Actual behavior

The status icon still show on the right if the direction of input is `rtl`

**Comment by jtommy** [comment]
@ymgsmz in my opinion you can support RTL by CSS using text-align: right, and invert padding-right with padding-left on input and icon right position:
For example:

```
.o-input-iconspace-right {
    padding-left: var(--oruga-input-height,2.25em);
}
.o-input {
  text-align: right;
}
.o-input__icon-right {
    left: 0;
}
```

![image](https://user-images.githubusercontent.com/8029488/146597481-86000b18-5348-421a-92d2-0335259c389c.png)

**Comment by ymgsmz** [comment]
@jtommy Are you sure it not going to have overlap with the left icon?

**Comment by jtommy** [comment]
It's only an example, you have to move ok right the left icon too and probably other things

**Comment by ymgsmz** [comment]
Yeah, that's right, this approach is what I personally take for most UI frameworks while working in the RTL direction 😃, or like this case, I disable the cause of the issue because it was unnecessary.

But I wonder if any plan to fix it in Oruga?

**Comment by jtommy** [comment]
What do you mean with "fix it"?
We can add a RTL theme but nothing to change in the core code. 
Probably you can help us 😉

**Comment by ymgsmz** [comment]
We may allow developers to define which side they prefer to show the status icon in the core code, it would also end with another customization option which I think is worth having.

> Probably you can help us 

Not sure I get time, but of course I love to contribute
will try.

**Comment by jtommy** [comment]
It's no a issue only about status icon, all components have to change alignment/position.

**Comment by ymgsmz** [comment]
What do you think if we make CSS changes only in [bulma theme](https://github.com/oruga-ui/theme-bulma) since it supports RTL?

**Comment by jtommy** [comment]
https://github.com/jgthms/bulma/releases/tag/0.9.0

Bulma already supports RTL
