### ISSUE TITLE
How to show a toast using Vue 3 syntax?

### ISSUE THREAD

**Issue by agm1984** [oruga-ui/oruga#256]
I have an app using Vue 3, Vite, and `<script setup>` syntax.

I don't have access to `this.$oruga`, so how can I launch a toast message programmatically?

**Comment by jtommy** [comment]
https://github.com/oruga-ui/oruga/issues/168#issuecomment-876618049

**Comment by agm1984** [comment]
Thanks for your help. I achieved success via #168 .

I did this:

``` vue
<script setup>
    import { useProgrammatic } from '@oruga-ui/oruga-next';

    const { oruga } = useProgrammatic();

    const handleSubmit = async () => {
        try {
            console.log('form payload', form.value);

            oruga.notification.open({
              message: 'Something saved correctly!',
              variant: 'info',
              position: 'bottom',
              closable: true
            });
            // console.log('oruga', oruga);
        } catch (err) {
            throw new Error(`Profile# Problem submitting profile: ${err}.`);
        }
    }
</script>
```

If anyone finds this later, note that I destructured `oruga` off of the `useProgrammatic()` because it returns an object with `addProgrammatic` and `oruga` keys on it.

**Comment by jtommy** [comment]
Yes, it was the initial concept but we changed later.
I'm sorry I hope to release Vue 3 docs soon!

**Comment by agm1984** [comment]
You're doing great work, thanks for everything.

**Comment by deotte** [comment]
Is there a way to extract this into a utility file?

It will work inside my `<script setup></setup>` component, but when I extract it into a utility function, and try to use it in a separate component, I get:

![Screenshot 2023-05-25 145309](https://github.com/oruga-ui/oruga/assets/31936704/9de98375-a0ec-48e5-9459-0a0cf1cf5d9e)

The code I'm using is:
```ts
// Toast.ts
import { useProgrammatic } from '@oruga-ui/oruga-next';

export function orugaToast(message: string, closable: boolean, variant?: string): void {
	const { oruga } = useProgrammatic;

	oruga.notification.open({
		message: message,
		closable: closable,
		variant: variant === undefined ? 'success' : variant,
	});
}
```

```ts
// Component.ts

onMounted(() => {
   orugaToast('Hello', true);
});
```
