### ISSUE TITLE
Proper way to use Oruga on Nuxt Edge with script setup

### ISSUE THREAD

**Issue by flavionn** [oruga-ui/oruga#259]
Hello! How do i use oruga on Nuxt Edge with script setup? I have to use Oruga or Oruga next?

Using the instructions in Oruga documentation and importing as module works for me, but i want to use this programatic on script setup function.

How can i achieve this?

**Comment by jtommy** [comment]
Oruga (Vue 2) is not composition oriented but you can import programmatic component and use it.
For example:

```
import { NotificationProgrammatic as notification } from '@oruga-ui/oruga'

notification.open({...})
```
