### ISSUE TITLE
useRouter undefined when using in modal

### ISSUE THREAD

**Issue by flavionn** [oruga-ui/oruga#260]
I have this in my component:

```js
onMounted(() => {
	modal.open({
		parent: this,
		component: ModalRegister,
		trapFocus: true,
		mobileBreakpoint: '200',
	})
})
```

and this in ModalRegister.vue

```vue
<script setup>

import { useRouter } from '@nuxtjs/composition-api'

const router = useRouter()
const emit = defineEmits()

console.log(router)

const click = () => {
	emit('close')
	router.push({ name: 'index' })
}

</script>
```

Im getting router "undefined" when i use useRouter inside modal component.

**Comment by jtommy** [comment]
The problem is `parent: this`.
It's mandatory it but `this` is not correct, you should use `getCurrentInstance` but I don't know if Vue 2 composition api exports it

**Comment by flavionn** [comment]
this should work?

```js
import { getCurrentInstance } from '@nuxtjs/composition-api'
```

i dont know what to put in parent property

**Comment by jtommy** [comment]
If it exists I think `parent: getCurrentInstance()`

**Comment by jtommy** [comment]
@flavionn any news?
