### ISSUE TITLE
Improve typescript support for vue 3 (oruga-next)

### ISSUE THREAD

**Issue by D4RKAR117** [oruga-ui/oruga#263]
### Description

Currently oruga has a very basic typescript support, provided by [this](https://github.com/oruga-ui/oruga/blob/208dd47e88002fb6f9cc55f6d194bb9f8f84eb13/packages/oruga-next/types/index.d.ts#L1) unique line, this only avoids that IDE's and typescript diagnostics trigger errors.
 
 
### Posible start point
To provide a more complete and native typescript support can be used `vue-tsc` to generate a very complete definitions for each component, like its described [here](https://github.com/johnsoncodehk/volar/tree/master/packages/vue-tsc#using), this can be used as is, or can be handily improved over specific use cases.

### Why Oruga need this feature

To Improve Developer Experience (DX) and the lib quality. Many modern Vue projects are now using typescript as their base. and workspaces like `Volar + VsCode` are focused in strongly typed components. 
this can also help more developers how are switching from Vue 2 environments like `Buefy` or others, to choose oruga.

**Comment by jtommy** [comment]
It's an important feature in our roadmap, I'll take a look at your link.

**Comment by rpauls** [comment]
Any update on the progress of adding `vue-tsc` and generating type definitions for `@oruga/oruga-next`?
Is there support needed to get this into oruga?
