### ISSUE TITLE
Time isn't visible in timepicker input after selecting time

### ISSUE THREAD

**Issue by karoletrych** [oruga-ui/oruga#266]
**Oruga** version: @oruga-ui/oruga-next: 0.4.8
**Vuejs** version: 3.2.26
**OS/Browser**: Windows 10/Firefox 95

### Description
```
<template>
    <o-field label="Select time">
    <o-timepicker
        rounded placeholder="Click to select..." 
        icon="clock" 
        :enable-seconds="true" 
        hour-format="24" 
        v-model="tt"
    />
        </o-field>
    {{tt}}
</template>
```
### Expected behavior
There should be value filled instead of "Click to select..."
### Actual behavior
![obraz](https://user-images.githubusercontent.com/17528710/148655825-e780d828-d49d-4175-81c9-3a3c1365163c.png)

**Comment by astagi** [comment]
@karoletrych 0.5.2 released!
