### ISSUE TITLE
Oruga Column Draggable in o-table

### ISSUE THREAD

**Issue by eamtalu** [oruga-ui/oruga#271]
### Description

ColumnDraggable Feature like buefy b-table

### Why Oruga need this feature

Oruga is a great lightweight framework and it would be nice if oruga o-table contains columndraggable feature like buefy b-table.

Thanks.

**Comment by jtommy** [comment]
@eamtalu what feature do you mean?

**Comment by eamtalu** [comment]
hi @jtommy 
Thanks for your quick reply. I have been using oruga since past few months in production. Then to satisfy one of the requirements which is columndragging for o-table, I can see the event is not supportable or working as like buefy b-table "draggable-column". Only draggable for row is working.

# Draggable rows/columns
Use draggable/draggable-column prop to allow rows and columns to be draggable. Manage dragging using dragstart/columndragstart, dragover/columndragover and drop/columndrop events

I would be highly grateful to you, if possible to add this or already there in oruga.

**Comment by jtommy** [comment]
Sure, I'll add it soon.

**Comment by eamtalu** [comment]
Thank you @jtommy, I appreciate your great support.

**Comment by eamtalu** [comment]
Hi @jtommy ,
I hope you are keeping well. Just a follow up, if you had any chance to work with this feature ? Never mind, if you did not have, in case if it is possible for you when you probably you would be able to add it ?

Thanks a lot.

**Comment by jtommy** [comment]
Probably before the end of week 😉

**Comment by eamtalu** [comment]
Wow, that would be a great help @jtommy. Can not thanks enough. Love Oruga.

**Comment by eamtalu** [comment]
Hi @jtommy, Thanks a million for your great help and salute to you for supporting the community, specially the developer/learner like me relying more on opensource. Thanks Man.

**Comment by eamtalu** [comment]
Hi @jtommy, currently my oruga version is "@oruga-ui/oruga": "^0.5.2",

should I run: # npm update @oruga-ui/oruga to get this feature ? Thanks

**Comment by jtommy** [comment]
I have to release the 0.5.3, i think max tomorrow

**Comment by eamtalu** [comment]
Hi @jtommy, you are a legend. Thank you and I wish you all the happiness.....
