### ISSUE TITLE
Future of Oruga Vue3 only?

### ISSUE THREAD

**Issue by cimchd** [oruga-ui/oruga#275]
First of all @jtommy and @astagi you are doing a great job. I really love the idea of Oruga and we are already using oruga-next in our first projects.

We see still a lot of essential things to improve in Oruga (typescript support, 100% esm compatible exports) and we are also willing to help with some prs but we already decided not to do it sometimes because of the vue2 repo.
It is a great thing that you want to provide oruga for both vue2 and vue3. But I think this leads to some problems:

1. You have to do a lot of things twice. This slows down the development speed of every contributor.
2. Some people willing to help don't help because of the higher effort to support both vue2 and vue3 (like us).
3. People searching for a vue3 repo are not sure if the vue3 support is already in focus, or if it is still too unstable to use it.

The downloads of the vue2 repo are not increasing much, but those of vue3 are 2x times higher and faster increasing: https://www.npmtrends.com/@oruga-ui/oruga-vs-@oruga-ui/oruga-next

I think vue2 deveoplers are mostly happy with their ui library and not looking for an alternative.
But I think that there are a lot of vue developers dealing with moving to vue3 at the moment and reconsider which ui library they use. Many are looking for a Tailwind/WindiCss compatible ui library like oruga. If you focus on this, I think Oruga can increase the growth of numbers a lot and provide a more mature version much earlier.

**Comment by jtommy** [comment]
@cimchd your point is correct and we agree with you on everything 😉 
In our roadmap there are features to develop only for Vue 3, such as new docs and types (https://github.com/oruga-ui/oruga/pull/270).

Nuxt is close to release a stable version and probably it's time for the Oruga to focus the efforts in the same direction.

Any advices about Oruga "promotion" are welcome and of course we are happy to receive your help!

**Comment by cimchd** [comment]
Thanks for the quick response. This is great news. :-)
