### ISSUE TITLE
[Feature Request]: Hover on the First element in autocomplete

### ISSUE THREAD

**Issue by mouadTaoussi** [oruga-ui/oruga#278]
The first element from autocomplete results should be selected automatically,
most of the time the user selects the first element when typing the exact word so he hit `Enter` instead of clicking `down key` then `Enter`

![image](https://user-images.githubusercontent.com/50294614/150844212-ba018c9f-5312-4023-b287-5f72face034c.png)
![image](https://user-images.githubusercontent.com/50294614/150844276-8c847f08-8e18-4093-9900-3c59f3cea452.png)

### Why Oruga need this feature
-better UX approach
-no need to click on `down key` then `Enter` if you want to select the first element

**Comment by jtommy** [comment]
There is already `keep-first` prop 😉

**Comment by mouadTaoussi** [comment]
OK , I should read the docs again 😁
