### ISSUE TITLE
Dropdown: Add active state in default slot scope

### ISSUE THREAD

**Issue by marcosgomesneto** [oruga-ui/oruga#284]
### Description

I would like to access the dropdown state (isActive) inside the default slot. For the trigger slot, this already exists.
This is very useful when you need to customize this slot.

### Why Oruga need this feature

This is the objective of Oruga, which is to be able to customize the components.

**Comment by jtommy** [comment]
@marcosgomesneto The trigger slot already shares `active` prop 😉

**Comment by jtommy** [comment]
Why do you need it? When the slot is visible then active is true

**Comment by jtommy** [comment]
@marcosgomesneto any news about my question?
