### ISSUE TITLE
Cannot use appendToBody in Dropdown

### ISSUE THREAD

**Issue by GiorgioJuniors** [oruga-ui/oruga#285]
### Overview of the problem

**Oruga** version: [0.5.3]
**Nuxtjs** version: [2.15.8]

### Description
i try to use the prop `append-to-body` in a o-dropdown but if i override the oruga classes with my custom, there is an error:
### Steps to reproduce
here the codesandbox : https://codesandbox.io/s/intelligent-murdock-t2zrc

### Expected behavior

using the prop 

### Actual behavior

throw this error:
`Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.`

**Comment by adrianogiannacco** [comment]
Any updates on this?

**Comment by GiorgioJuniors** [comment]
Thanks so much for the fix , is this already available to use  ?

**Comment by jtommy** [comment]
No, but we'll make a new release soon
