### ISSUE TITLE
Documentation lacking: Using icons

### ISSUE THREAD

**Issue by SuperCuber** [oruga-ui/oruga#287]
### Description

I've read the "Setup" section on `oruga.io`, which explains how to install oruga and its css.
Then I went to use a `$oruga.notification.open` which worked successfully but there was no `X` icon, just a circle.
I looked around the getting started section  and there's no mention of how to install icons.
I looked around `Icon` section and tried to guess based on the custom examples what I'm supposed to do but couldn't manage to understand...

I think either in the getting started page or the icon page there should be a section describing how to install default icons for the default icon pack (i think it's mdi). What `npm install` needs to be run, and what imports need to be added for it.

### Why Oruga need this feature

I think this will remove a lot of frustration and friction when starting out.

**Comment by jtommy** [comment]
@SuperCuber do you have suggestions? Can you make a PR to improve the docs?

Thanks

**Comment by SuperCuber** [comment]
@jtommy Hard to make a PR when I still don't know how to install the icons :P
I think the two places I would expect this to be in is either in an additional section in [Introduction](https://oruga.io/documentation/#setup), or in the [Icon base example](https://oruga.io/components/Icon.html#examples)

**Comment by jtommy** [comment]
What's icon pack do you need?

**Comment by SuperCuber** [comment]
Any one really, I see the popular ones are fontawesome and material design, the default (in the docs for example) is material design I suppose?

**Comment by jtommy** [comment]
Then you have to import CSS font and it's ready

**Comment by SuperCuber** [comment]
@jtommy do you mean https://www.npmjs.com/package/@mdi/font ? because a simple `import "@mdi/font"` results in an error...

**Comment by SuperCuber** [comment]
OK based on https://dev.materialdesignicons.com/getting-started/webfont I tried doing `import '@mdi/font/css/materialdesignicons.min.css'` but this gives me an error in the browser console:

```
Source map error: Error: request failed with status 404
Resource URL: http://localhost:3000/play
Source Map URL: materialdesignicons.css.map
```

**Comment by SuperCuber** [comment]
In addition, the getting started page recommends using [vue icon](https://dev.materialdesignicons.com/getting-started/vuejs) instead..?

**Comment by jtommy** [comment]
For example `<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@mdi/font@5.8.55/css/materialdesignicons.min.css">`

**Comment by SuperCuber** [comment]
@jtommy  The icon close icon on the notification still doesn't show. Upon further investigation with style editor, looks like `mdi-times` icon does not exist in that link's files? Changing the class to something else like `mdi-crosshair` shows an icon. I tried with version `@6.5.95` of the link but it still doesn't show it...

**Comment by SuperCuber** [comment]
I'm using `"@oruga-ui/oruga-next": "^0.5.3"` btw. If there's more info I can provide then tell me :)

**Comment by jtommy** [comment]
@jtommy the docs use font awesome and font-awesome vue component

**Comment by luisdnodrizat** [comment]
If you want to use default mdi:
`npm install @mdi/font`
`@import '@mdi/font/css/materialdesignicons.min.css';`
