### ISSUE TITLE
Datepicker functionality lost when wrapped in Headless UI modal dialog

### ISSUE THREAD

**Issue by birdlavv** [oruga-ui/oruga#290]
### Overview of the problem

**Oruga** version: 0.5.3
**Vuejs** version: 3.2.30
**OS/Browser**: OSX - Firefox & Chrome

### Description

The datepicker dropdown's "click-outside-to-close" functionality seems to break when the component is wrapped inside a Headless UI modal.

### Steps to reproduce

Reproduction URL: https://stackblitz.com/edit/vue-43dtrh
1. Open the modal
2. Try to close the dropdown by clicking outside the datepicker but within the modal dialog.

### Expected behavior

The expected behavior is that the dropdown would close when focus within the datepicker is lost.

### Actual behavior

The dropdown does not close when being used within a Headless UI modal.

**Comment by jtommy** [comment]
@birdlavv just tested and there is something strange with the body of Dialog (Headless).
For example https://github.com/tailwindlabs/headlessui/blob/639d8d2d607880472375627e5b170789eca530e7/packages/%40headlessui-vue/src/components/dialog/dialog.ts#L173, it might lock dropdown (oruga) listeners
