### ISSUE TITLE
Collapse: Example code not working with slot errors

### ISSUE THREAD

**Issue by ellejeong** [oruga-ui/oruga#295]
### Overview of the problem

**Oruga** version: `"@oruga-ui/oruga-next": "0.5.3"`
**Vuejs** version: [3.2.29]
**OS/Browser**: Chrome Version 98.0.4758.80 (Official Build) (x86_64)

### Description

Collapse component seems to have errors related to Vue 3 - collapse is just not working.
`slot` and `slot-scope` are both showing `vue/no-deprecated-slot-attribute` errors. 

See screenshots below - I am copying/pasting original code from [documentation](https://oruga.io/components/collapse.html#accordion).

![Screen Shot 2022-02-14 at 12 51 17 PM](https://user-images.githubusercontent.com/19518960/153919623-bb8dc7d9-5d8c-462d-b640-ae3dbaad2474.png)
![Screen Shot 2022-02-14 at 12 51 00 PM](https://user-images.githubusercontent.com/19518960/153919625-0a36b98c-0881-4d07-9732-756e0c1c6312.png)

### Steps to reproduce
1. Copy/paste code from here to your file.
2. You should see errors on text editor which prevents app from loading.
3. Running the app -> app does not run.
4. Console errors appear that point to collapse.mjs file. 

### Expected behavior
Expect collapse to work with no errors.

### Actual behavior
Collapse won't work.
App won't load with console errors:
![Screen Shot 2022-02-14 at 12 57 34 PM](https://user-images.githubusercontent.com/19518960/153919953-0b515493-e90a-4777-8df2-25ed064319d9.png)

![Screen Shot 2022-02-14 at 12 57 48 PM](https://user-images.githubusercontent.com/19518960/153919989-f3a88e55-d74b-4c62-84d1-5a7cd4633594.png)

**Comment by jtommy** [comment]
The examples in the docs is for Vue 2, you have to change it for Vue 3.

`<template v-slot:trigger="props"> ..`

I hope to update the docs soon to Vue 3

**Comment by ellejeong** [comment]
@jtommy 

Hey! Thank you for your response; the update you provided helped solve the editor errors, however I'm still seeing this console error:

**console:** 
![Screen Shot 2022-02-14 at 2 39 47 PM](https://user-images.githubusercontent.com/19518960/153934416-960f0e9e-4c79-4146-8630-e1353b0062e7.png)

**code editor:**
![Screen Shot 2022-02-14 at 2 40 06 PM](https://user-images.githubusercontent.com/19518960/153934478-8fe3e901-7b64-4213-92a9-d40478df2f77.png)

**Comment by jtommy** [comment]
You gave to use template tag as trigger slot. 
It's a Vue 3 requirement

**Comment by ellejeong** [comment]
@jtommy That works, thank you!!!!!!!!!!
