### ISSUE TITLE
DatePicker Not Displaying Buttons

### ISSUE THREAD

**Issue by meriahoneil** [oruga-ui/oruga#296]
### Overview of the problem

**Oruga** version: `"@oruga-ui/oruga-next": "0.5.3"`
**Vuejs** version: [3.2.29]
**OS/Browser**: Chrome

### Description

When rendering a DatePicker object with nested buttons that should display on footer of DatePicker, instead nothing appears, along with no errors. 

### Steps to reproduce

1. Create a datepicker object
2. Attempt to nest buttons within it, like Now or Clear

### Expected behavior

DatePicker renders with nested buttons visible

### Actual behavior

Note that DatePicker renders on UI but nested buttons do not
Can view bug here in DatePicker documentation example for footer-slot: https://oruga.io/components/datepicker.html#footer-slot

**Comment by vimalrajgit** [comment]
@meriahoneil the documentation examples are not correct as they might have updated code to use the named slot. here is the updated code which will work

```
<template>
  <o-field label="Select a date">
    <o-datepicker v-model="date" :first-day-of-week="1" placeholder="Click to select...">
      <template #footer>
        <o-button variant="primary" @click="date = new Date()">
          <o-icon icon="calendar"></o-icon>
          <span>Today</span>
        </o-button>
        <o-button variant="danger" @click="date = null">
          <o-icon icon="times"></o-icon>
          <span>Clear</span>
        </o-button>
      </template>
    </o-datepicker>
  </o-field>
</template>
```

**Comment by jtommy** [comment]
Yes, the examples in the docs are for Vue 2.
I hope to update soon them to Vue 3

**Comment by meriahoneil** [comment]
Ah thank you @jtommy, that worked!
