### ISSUE TITLE
Oruga table dynamic fields issue.

### ISSUE THREAD

**Issue by vimalrajgit** [oruga-ui/oruga#297]
Can anyone suggest whats the best way to render the dynamic fields in table in faster way

consider a table with 12 columns and want to render all the column fields dynamically

```
<o-table :data="data">
  <o-table-column for="field in columns" :field="field.id" v-bind="field">
    <component ....../>
  </o-table-column>
</o-table>
```

Issue: as there are 12 columns, o-table-column is called 12 times due to for-loop in o-slot-component (in package table.vue) and o-table-column itself looped 12 times to get the field details since the field data cant be received directly by o-table-component using slots in vue 3

There will be no slow rendering issue if its a simple field component which displays just text but when there is more rows with some more functional field component it will take time as the rendering of single field component will be nxn times.

**Comment by jtommy** [comment]
@vimalrajgit maybe using key attribute, did you try?

**Comment by vimalrajgit** [comment]
Yes @jtommy i do use key attribute for o-table-column.

**Comment by jtommy** [comment]
@vimalrajgit any news?

**Comment by jtommy** [comment]
Just improve SSR rendering and first load https://github.com/oruga-ui/oruga/commit/26935a35378530da14c6c294f706b23c87a3dd48
