### ISSUE TITLE
[Nuxt Bridge] Tree shaking not working

### ISSUE THREAD

**Issue by Tragio** [oruga-ui/oruga#298]
### Overview of the problem

**Oruga** version: 0.5.3
**Vuejs** version: Nuxt - 2.16.0-27358576.777a4b7f
**OS/Browser**: MacOS 11

### Description

Making use of tree shaking of Oruga does not work. Importing one component makes all modules in the build bundle.

![Screenshot_2022-02-11_at_08 06 54](https://user-images.githubusercontent.com/5109593/154047007-9bc457d0-60ed-44e9-a2d3-8394dbf860e1.jpg)

### Steps to reproduce

**Minimal reproduction:**
https://github.com/Tragio/oruga-tree-shaking-bug

The client bundle will bundle right and show the webpack analyzer, however, the server bundle will fail due to nuxt/bridge#128 but it's not related to this issue and should not interfere with its resolution.

Thank you for the amazing work 😃

**Comment by danielroe** [comment]
Workaround for now (we'll need to investigate in Nuxt what the root cause is here):

```js
import { defineNuxtConfig } from '@nuxt/bridge'

export default defineNuxtConfig({
  bridge: {
    resolve: false,
  }
})
```

**Comment by Tragio** [comment]
> Workaround for now (we'll need to investigate in Nuxt what the root cause is here):
> 
> ```js
> import { defineNuxtConfig } from '@nuxt/bridge'
> 
> export default defineNuxtConfig({
>   bridge: {
>     resolve: false,
>   }
> })
> ```

Thank you for your quick reply!! Doing that workaround I get a 500 error, at least on Vercel.

![Screenshot 2022-02-15 at 12 03 37](https://user-images.githubusercontent.com/5109593/154058804-4a4bcebc-aa5d-46d4-baf5-b07417cfe45c.jpg)

**Comment by Tragio** [comment]
> That's an unrelated issue. See https://v3.nuxtjs.org/concepts/esm.
> 
> 
> 
> **Edit**: Forgive my too hasty assumption; are you saying this occurs only when you set `resolve: false`?

Yes, that's correct. This issue only happens when I use that workaround 🙃

**Comment by jtommy** [comment]
@Tragio we might fix it using the same approach of https://github.com/oruga-ui/oruga/pull/273

**Comment by jtommy** [comment]
@Tragio we've just released 0.5.4, please check it

**Comment by Tragio** [comment]
@jtommy thank you. I deleted `.nuxt`, `.output`, `node_modules`, and `yarn.lock`. Did a yarn install, and then a build. All is the same 🤔

**Comment by jtommy** [comment]
Did you see the new file index.mjs into dist/esm ?

**Comment by Tragio** [comment]
> Do you see the new file index.mjs into dist/esm ?

Yes, I have it here.
![Screenshot 2022-02-22 at 09 56 20](https://user-images.githubusercontent.com/5109593/155108114-e8568ded-b553-402a-a93d-cc777f16fdc7.jpg)

**Comment by Tragio** [comment]
> What's the error right now?

Tree shaking keeps not working.

![Screenshot 2022-02-22 at 10 04 18](https://user-images.githubusercontent.com/5109593/155109559-89126fee-6401-424e-8d6c-c8ddf3cb6589.jpg)

**Comment by jtommy** [comment]
The fix should resolve the problem using the workaround.
I think that @danielroe is investigating about tree shaking

**Comment by jtommy** [comment]
@Tragio any news?
