### ISSUE TITLE
Oruga's field component prop types different than Buefy's counterpart

### ISSUE THREAD

**Issue by edfrias** [oruga-ui/oruga#310]
### Description

Hi everyone, I'm currently migrating from Buefy to Oruga and some components that do the same had differences on their properties.

In buefy's field component we have the property `:type`, in oruga's field this property is called `:variant`, apparently they are the same but not the types. 

Buefy's type is "string, object" and in oruga's counterpart is only "string" (I'm also seeing this in properties like message).

If you have something like:

`<b-field :type="{ 'is-danger': errors[0] }" > <MyAwesomeComponentHere /> </b-field>`

You can't directly go to this:

`<o-field :variant="{ 'is-danger': errors[0] }" > <MyAwesomeComponentHere /> </o-field>`

I don't know how intentional this is.

### Why Oruga need this feature

Although prop names may be different, it would be super nice to have the same types in order to not having to refactor a lot to pass from buefy to oruga.

Thank you so much for your work and efforts in this library ;)

**Comment by jtommy** [comment]
At the moment it doesn't support object prop.
It's an important change to the core code because it's a prop used as classes composition

**Comment by edfrias** [comment]
Thanks for your response! Will do that way!
