### ISSUE TITLE
Programmatically close modal with events

### ISSUE THREAD

**Issue by tanhs** [oruga-ui/oruga#313]
### Why Oruga need this feature
Need to close modal in parent when open programmatically

Admin.vue
   ```
 ...
    Modal.open({
        component: UserAccountAdd,
        events: {customEvt},
    function customEvent(e){
        -->need to close the Model programmatically here?
    }
```
    UserAccountAdd.vue
    ```<o-button
        type="button"
        @click="customEvt"
        >Close</o-button>
    function customEvt(event) {
        emit('customEvt', event);
    };
```

**Comment by IceBlizz6** [comment]
As i mentioned on discord earlier the Vue 2 version seems to have a working solution for this.
$oruga.modal.open(..) will return the component instance.
And then the modal can be closed with .close()

const comp = $oruga.modal.open(..)
....
comp.close()

This seems to have changed in Vue 3 as modal.open function now returns undefined instead.
In our project we are currently running a hack with a global map register to get around this.
The modal component will register itself in a lifecycle hook using an auto incremented id that can then be fetched back from the caller.
It's an ugly solution, and will be reverted when we get an official solution for Vue 3.
