### ISSUE TITLE
o-switch input event

### ISSUE THREAD

**Issue by nioc** [oruga-ui/oruga#317]
### Overview of the problem

**Oruga** version: 0.5.4
**Vuejs** version: 3.2.31
**OS/Browser**: Firefox 98

### Description

The input event emitted by `o-switch` is before the computation of the v-model value.
[Doc](https://oruga.io/components/Switch.html#events) says that component has an `input` event but it seems broken, should we use the `update:modelValue` event?

### Steps to reproduce

``` vue
<template>
  <o-switch variant="primary" v-model="switchedValue" @input="doSomething"> {{switchedValue}}broken </o-switch>
  <o-switch variant="primary" v-model="switchedValue" @update:modelValue="doSomethingValid"> {{switchedValue}} working </o-switch>
</template>

<script lang="ts">
export default {
  data() {
    return {
      switchedValue: false,
    }
  },
  methods: {
    doSomething(event) {
      console.log(event.target.value, this.switchedValue)
    },
    doSomethingValid(value) {
      console.log(value, this.switchedValue)
    }
  },
};
</script>
```

### Expected behavior
Console output the value according to the switch (for both `event.target.value` and `this.switchedValue`)

### Actual behavior
Console output the previous value and `event.target.value` not updated for `@input`
Console output the correct values for `@update:modelValue`

**Comment by jtommy** [comment]
We are working on new docs because the current examples are for Vue 2.

The correct is the new syntax as you described.
