### ISSUE TITLE
Missing emit declaration for details-open in Table component

### ISSUE THREAD

**Issue by Thaurin** [oruga-ui/oruga#319]
### Overview of the problem

**Oruga** version: [0.5.4] (oruga-next)
**Bulma theme** version [0.2.3]
**Vuejs** version: [3.2.25]
**OS/Browser**: Latest Chrome

### Description

When using a Table with a detail slot, when opening the detail for a row, Vue warns me that:

    [Vue warn]: Component emitted event "details-open" but it is neither declared in the emits option nor as an "onDetails-open" prop.

I checked the `Table.vue` component `emits` property, and although `details-close` is defined, `details-open` seems to be missing from the array.
### Steps to reproduce

1. Create a table with a detail slot
2. Open the detail for a row in the table
3. Look at the console warning

### Expected behavior

No warning should be given in the console.

### Actual behavior

    [Vue warn]: Component emitted event "details-open" but it is neither declared in the emits option nor as an "onDetails-open" prop.

**Comment by jtommy** [comment]
@Thaurin please make a PR to fix it

**Comment by Thaurin** [comment]
Could try it. I don't have the environment set up, but I tried earlier and I got some errors after `npm run bootstrap` (Git for Windows setup). I'll try again a bit later.

Node v12.22.7
npm v6.14.15

**Comment by jtommy** [comment]
It's only a value to add to emits list, you can it directly from GitHub

**Comment by Thaurin** [comment]
I guess I kinda have it in my system that I want to test any and all changes myself before I make a PR. :) I also don't have that much experience with GitHub (more with GitLab). But like the idea of helping out more in the future, so getting this set up right would be nice.

Made PR at #320

**Comment by Thaurin** [comment]
Can I still ask if this tool chain works with Git for Windows, or do I have to go WSL or full Linux?

**Comment by jtommy** [comment]
I use Windows :)

**Comment by Thaurin** [comment]
So I can find a solution for these errors and be more helpful in the future!
