### ISSUE TITLE
Help on this.$oruga.config when using tree shaking

### ISSUE THREAD

**Issue by nioc** [oruga-ui/oruga#329]
### Overview of the problem

Oruga version: 0.5.4
Vuejs version: 3.2.31
OS/Browser: Firefox 98

### Description

I would like to update datepicker configuration (defaultFirstDayOfWeek) when user change locale, I used `this.$oruga.config.setOptions({...})` but with tree shaking, I got `this.$oruga.config is undefined`. What is needed to be imported for config be defined?

Here is my import statement (main.js):

```js
import { Tabs, Field, Config, Loading, Switch, Modal, Table, Icon, Upload, Datepicker, Collapse, Slider, Input } from '@oruga-ui/oruga-next'
// ...
app.use(Tabs)
  .use(Field)
  .use(Loading)
  .use(Switch)
  .use(Modal)
  .use(Table)
  .use(Icon)
  .use(Upload)
  .use(Datepicker)
  .use(Collapse)
  .use(Slider)
  .use(Input)
  .use(Config, {
    ...bulmaConfig,
    iconPack: 'fas',
    datepicker: {
      ...bulmaConfig.datepicker,
      firstDayOfWeek: localeData.firstDayOfWeek(),
    },
  })
```

And when user switches locale:
```js
    setLocale (locale) {
      // setHeader('Accept-Language', locale)
      // document.querySelector('html').setAttribute('lang', locale)
      // this.$i18n.locale = locale
      this.$dayjs.locale(locale)
      const localeData = this.$dayjs.localeData()
      this.$oruga.config.setOptions({
        datepicker: {
          firstDayOfWeek: localeData.firstDayOfWeek(),
        },
      })
  }
```

### Expected behavior

`this.$oruga.config` is defined.

### Actual behavior

`this.$oruga.config` is undefined.

**Comment by jtommy** [comment]
Are you using composition api?

**Comment by nioc** [comment]
Good morning.
No, I use options API, and on some components with a setup (for store for example).

**Comment by jtommy** [comment]
@nioc ah ok, you are not using the full bundle so you don't have `$oruga` variable; you have to use `Config.setOptions(...)`

**Comment by nioc** [comment]
Otherwise, I may have forgotten to import/use something in my `main.js` to inject the `config` attribute. If you know what import can handle that, it should be great 👍🏻

I imported these:
Tabs, Field, **Config**, Loading, Switch, Modal, Table, Icon, Upload, Datepicker, Collapse, Slider, Input

**Comment by jtommy** [comment]
> Thanks. _I do have a `this.$oruga` variable set with `loading` and `modal` attribute but no `config`._
> 
> I tried to `import { Config } from '@oruga-ui/oruga-next'` in the component which handle locale switch:
> 
> ```
> <script>
> import { Config } from '@oruga-ui/oruga-next'
> import { useStore } from '@/store'
> // ...
> export default {
>   setup() {
>     const store = useStore()
>     return { store }
>   },
>   //...
>   methods: {
>     setLocale (locale) {
>       // setHeader('Accept-Language', locale)
>       // document.querySelector('html').setAttribute('lang', locale)
>       // this.$i18n.locale = locale
>       this.$dayjs.locale(locale)
>       const localeData = this.$dayjs.localeData()
>       Config.setOptions({
>         datepicker: {
>           firstDayOfWeek: localeData.firstDayOfWeek(),
>         },
>       })
>     },
>   },
> }
> </script>
> ```
> 
> **But I got an `Uncaught TypeError: (intermediate value).setOptions is not a function`. What do I need to import for update instance config?**

Here you are using composition api.. you can import useProgrammatic from '@oruga-ui/oruga-next'

**Comment by nioc** [comment]
Was not ok for me as the result is the same as `this.$oruga`.

After a few tries, I finally found my way (`import ConfigProgrammatic` then `ConfigProgrammatic.setOptions({...})`), if anyone is in the same situation (or if you want to add it to the doc):

``` js
import { ConfigProgrammatic } from '@oruga-ui/oruga-next'
export default {
  //...
  methods: {
    setLocale (locale) {
      ConfigProgrammatic.setOptions({
        locale,
        datepicker: {
          firstDayOfWeek: localeData.firstDayOfWeek(),
        },
      })
    },
  },
}
```

**Comment by jtommy** [comment]
> Was not ok for me as the result is the same as `this.$oruga`.
> 
> After a few tries, I finally found my way (`import ConfigProgrammatic` then `ConfigProgrammatic.setOptions({...})`), if anyone is in the same situation (or if you want to add it to the doc):
> 
> ```js
> import { ConfigProgrammatic } from '@oruga-ui/oruga-next'
> export default {
>   //...
>   methods: {
>     setLocale (locale) {
>       ConfigProgrammatic.setOptions({
>         locale,
>         datepicker: {
>           firstDayOfWeek: localeData.firstDayOfWeek(),
>         },
>       })
>     },
>   },
> }
> ```

I told you it in my first answer! You can use the other solution too
Btw the docs for Vue 3 is working in progress

**Comment by nioc** [comment]
You're right but reading your answer, it was not obvious to me that I have to import `ConfigProgrammatic`.
Sorry to disturb you with these beginner questions. Oruga will be a great tool and I really thanks you for all this work.

**Comment by jtommy** [comment]
No problem, thanks 😉
