### ISSUE TITLE
Tooltip triggers are visible over other open tooltips

### ISSUE THREAD

**Issue by j-a-m-l** [oruga-ui/oruga#330]
### Overview of the problem

**Oruga** version: 0.5.4
**Vuejs** version: 3.2.26
**OS/Browser**:

### Description

When using `appendToBody`, tooltip trigger have higher `z-index` than tooltip content and arrow, so when using several tooltips, their triggers will be visible over the other tooltip contents.

### Expected behavior

The tooltip content should be always over any other tooltip trigger.

### Actual behavior

The tooltip content is under other tooltip triggers.

**Comment by jtommy** [comment]
Similar to https://github.com/oruga-ui/oruga/issues/105

In general `append-to-body` needs of a refactor

**Comment by mlmoravek** [comment]
Seems to be solved.
