### ISSUE TITLE
Migrate from uefy to Oruga: Message Component.

### ISSUE THREAD

**Issue by ayalon** [oruga-ui/oruga#331]
I'm in progress of moving from Buefy to Oruga to prepare the switch to Vue3.

Refactoring my Buefy components to Oruga components was straight forward.

But then I wanted to implement the Buefy Message:
https://buefy.org/documentation/message/

But I could not find a relevant counterpart on Oruga. 
What is the best way to to have the same behaviour like a Message with a header?

**Comment by jtommy** [comment]
Base notification? https://oruga.io/components/Notification.html#examples

**Comment by ayalon** [comment]
Notification exist on Bulma as well and they are already perfectly styled.

https://bulma.io/documentation/elements/notification/
vs
https://bulma.io/documentation/components/message/

I could maybe somehow refactor it but a notification for example does not have a title while a message has a title. I think I should not hijack notification because its already perfectly working.

**Comment by jtommy** [comment]
Then you can create a component by yourself or simply use html elements and Bulma CSS

**Comment by ayalon** [comment]
Will do. Thanks for your help and your great framework!

**Comment by jtommy** [comment]
Thanks 👍
