### ISSUE TITLE
Tab Component: Default tab is not respected on initial page load.

### ISSUE THREAD

**Issue by ayalon** [oruga-ui/oruga#332]
I found a bug with the default tab on SSR Rendering.

The bug is reproducible on the Tabs documentation page of Oruga itself:
https://oruga.io/components/tabs.html

If you open the page directly in the browser you see this:
![image](https://user-images.githubusercontent.com/432045/161225985-327322af-77a1-4895-8818-4fd03d5497a8.png)

The first tab does not show content.

If you navigate client side to this page, you can see, that there is default content. It just does not work on the initial page load:
![image](https://user-images.githubusercontent.com/432045/161226188-359e7d4a-7c44-4a64-95d1-6cf2a24b00b9.png)

**Comment by jtommy** [comment]
The issue is only in that example, did you reproduce it in your project?

**Comment by ayalon** [comment]
I had the same Issue ist n my project using nuxt. And I was glad I saw the same issue on the example page. Bur I first realized it in my local project on page load.

**Comment by denised** [comment]
I ran into this as well.

**Comment by jtommy** [comment]
@denised oruga-next (vue 3) or oruga (vue 2)?

**Comment by denised** [comment]
Vue 3

-- 
  Denise Draper
  ***@***.***

**Comment by jtommy** [comment]
@denised can you reproduce on codesandbox or similar?

**Comment by denised** [comment]
You should be able to see it on https://stackblitz.com/edit/vitejs-vite-gya47e?file=src%2FVarViewer.vue
(The issue isn't unique to Stackblitz --- it also happened on my desktop.)



-- 
  Denise Draper
  ***@***.***

**Comment by denised** [comment]
You have to click on "show sources" to get the tabs to show for the first time.

-- 
  Denise Draper
  ***@***.***

**Comment by jtommy** [comment]
Double issue https://github.com/oruga-ui/oruga/issues/428

**Comment by jtommy** [comment]
@denised  the problem is that you are mixing string and number as tabs-item value, try to use only number for example
