### ISSUE TITLE
Modal onClose method called twice

### ISSUE THREAD

**Issue by BuffMcBigHuge** [oruga-ui/oruga#333]
### Overview of the problem

```
Vue: 3.2.25
@oruga-ui/oruga-next: 0.5.4
@oruga-ui/theme-bulma: 0.2.3
```

### Description

The Modal onClose functions seems to call twice. This behaviour makes it difficult to handle modal callbacks to the originating component.

### Steps to reproduce

[CodeSandbox](https://codesandbox.io/s/oruga-vue3-modal-test-0hcqxy?file=/src/App.vue)

### Expected behavior

Emitting a single 'close' event should only call the `onClose` method a single time.

### Actual behavior

The `onClose` method is called twice, one of which is always with an undefined result in the callback.

**Comment by jtommy** [comment]
@BuffMcBigHuge using promise it works.
We'll investigate about callback way
