### ISSUE TITLE
v0.5.5 new promise returns (modal/notification) makes vue throw type warnings

### ISSUE THREAD

**Issue by dwhoop55** [oruga-ui/oruga#335]
### Overview of the problem

**Oruga** version: [0.5.5] (latest)
**Vuejs** version: [2.6.14] (latest vue2)
**OS/Browser**: Chrome Version 100.0.4896.75 (arm64)

Version < 0.5.5 are not affected.

### Description

Modal and Notification have props defined "promise" as `Object` but get fed with a `Promise`.
Thus Vue warns of the type mismatch:
`[Vue warn]: Invalid prop: type check failed for prop "promise". Expected Object, got Promise `

Defined for Modal here:
https://github.com/oruga-ui/oruga/blob/19cbd6aacd5c896b8f7adfdda805902913a4816b/packages/oruga/src/components/modal/Modal.vue#L80

and for Notification through the mixin in NotificationNotice here:
https://github.com/oruga-ui/oruga/blob/19cbd6aacd5c896b8f7adfdda805902913a4816b/packages/oruga/src/utils/NoticeMixin.js#L57

I understand that this is only a warning and not breaking any functionality right now. So while this is not really a "bug" I wanted to submit it such that others seeing the same in their log can find it and don't have to do the digging.

### Steps to reproduce

Create a programmatic Modal or Notification

https://codesandbox.io/s/oruga-modal-xoq1h
Open a modal or Notification and see console.

### Expected behavior

No warning

### Actual behavior

Vue warns of type mismatch

**Comment by DavidVaness** [comment]
@jtommy Is this fix released? I am on v0.5.5 and get the same issue

**Comment by jtommy** [comment]
@DavidVaness it will be available in the next 0.5.6

**Comment by jtommy** [comment]
@DavidVaness i released it last week
