### ISSUE TITLE
Pagination issue when manually updating current prop

### ISSUE THREAD

**Issue by wyxos** [oruga-ui/oruga#336]
### Overview of the problem

**Oruga** version: 0.5.5
**Vuejs** version: 3.2.25
**OS/Browser**: ElectronJS

### Description

Pagination bug when :current is updated while the total  number of pages is consequent enough.

### Steps to reproduce

1. Bind the current page to an input.
2. Set total number of items to 19000 and per-page to 24
3. Manually update the input to a large number i.e. 1000

### Expected behavior
Pagination should show only a limited range before and after the number that was keyed in.

### Actual behavior
Pagination shows a bigger range of numbers prior to the number keyed in even if range-before is defined i.e. set to 3.

![image](https://user-images.githubusercontent.com/23614232/162353284-17a687fe-5ba6-4281-b670-04a4e697a427.png)

![image](https://user-images.githubusercontent.com/23614232/162353341-fee85373-36c2-4673-a4a3-d799bc5ca4b4.png)

Navigation works fine. Only issue is during manual input.

**Comment by Mars073** [comment]
it's a simple, the problem is that your `v-model` returns a `string`, so the component will concatenate it with the numbers instead of doing the mathematical operations. you can solve this problem by using `v-model.number="..."`.

@jtommy do you want me to add security to cast the types and prevent "page overflow"?

**Comment by jtommy** [comment]
@Mars073 ok

**Comment by wyxos** [comment]
@Mars073 Although it is correct that it is a casting issue, I found even more issues while trying the above.

- Going for ```v-model.number``` fixes my issue but the pagination "active" state stops working. So if I am on page 10, it doesn't set the anchor for page 10 as active.
- Going for ```v-model:current.number``` maintains the active state but it doesn't address the problem initially reported.

**Comment by wyxos** [comment]
Sorry, please ignore the above. I was looking at the wrong v-model.

**Comment by wyxos** [comment]
@Mars073 You're correct, issue was due to not casting the value from the input to number. Closing issue.
