### ISSUE TITLE
[Bug] Table column width is not respected if showHeader=false

### ISSUE THREAD

**Issue by Zelgadis87** [oruga-ui/oruga#342]
### Overview of the problem

**Oruga** version: 0.5.5
**Vuejs** version: 3.2.13
**OS/Browser**: Microsoft Edge

### Description

Using the width parameter on a o-table-column component only works when it's parent o-table has showHeader=true (the default). It has no effect when the header is hidden.

**Comment by jtommy** [comment]
@Zelgadis87 you are right, at the moment the column width is applied to the head that maintains it to the body. 
We might refactor it or hide the head with `v-show`, but probably better the first way
