### ISSUE TITLE
[Bug] Table cannot works with reactive props

### ISSUE THREAD

**Issue by heohex** [oruga-ui/oruga#344]
### Overview of the problem

**Oruga** version: 0.5.5
**Vuejs** version: 3.2.31
**OS/Browser**: Windows / Chrome

### Description

Table getting errors when use some reactive prop

### Steps to reproduce

**https://codesandbox.io/s/long-http-to0pjl?file=/src/App.vue**
1. Try to resize window
2. Try to use switch "Bordered"

### Expected behavior

1. Rows appears as cards on mobile
2. Border to all cells

### Actual behavior

Errors in console: 
[Screenshot](https://prnt.sc/1YRexvX4zv-3)

1. [Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
2. Uncaught (in promise) TypeError: Cannot read properties of null (reading 'subTree')
3. Cannot read properties of null (reading 'emitsOptions')

**Comment by jtommy** [comment]
The problem is `columns` prop, try using table-column components.
The prop is now well supported in the next version at the moment.

**Comment by heohex** [comment]
> The problem is `columns` prop, try using table-column components. The prop is now well supported in the next version at the moment.

It's not obvious :) 
Thank you

**Comment by akhma-ps** [comment]
> The prop is now well supported in the next version at the moment.

I'm sorry, I don't understand. You mean the next version after 0.5.5, which has not yet been released?

**Comment by jtommy** [comment]
I am not working on it, but I'll decide to break the support or fix it later. Btw there is an alternative:)

**Comment by luisdnodrizat** [comment]
Example:
`            <OTable :data="data"
                    :striped="true">
                <OTableColumn field="id" label="ID" width="40" numeric v-slot="props">
                    {{ props.row.id }}
                </OTableColumn>
                <OTableColumn field="first_name" label="First Name" v-slot="props">
                    {{ props.row.first_name }}
                </OTableColumn>
                <OTableColumn field="last_name" label="Last Name" v-slot="props">
                    {{ props.row.last_name }}
                </OTableColumn>
                <OTableColumn field="date" label="Date" centered v-slot="props">
                    {{ props.row.date }}
                </OTableColumn>
                <OTableColumn field="gender" label="Gender" v-slot="props">
                    {{ props.row.gender }}
                </OTableColumn>
            </OTable>`
