### ISSUE TITLE
Tabs Animation on clicking previous tab is broken

### ISSUE THREAD

**Issue by Roldification** [oruga-ui/oruga#355]
### Overview of the problem

**Oruga** 0.5.5
**Vuejs** 3.2.33
**OS/Browser**:  Chrome 100.0.4896.127

### Description

When clicking the previous tab, no animation is shown for sliding back.

### Steps to reproduce

1. Use the Tabs component

### Expected behavior

A nice slide animation to previous tab should occur

### Actual behavior

it went back to previous tab but without the sliding animation.

**Comment by mlmoravek** [comment]
Look like it is alreay fixed.
