### ISSUE TITLE
Oruga Table CheckBox not selecting

### ISSUE THREAD

**Issue by SebastianHenzmann** [oruga-ui/oruga#358]
### Overview of the problem

**Oruga** version: [0.5.5]
**Vuejs** version: [3.2.33]
**OS/Browser**: Windows 10 Pro 21H2, Chrome 101.0.4951.54

### Description

Warning in console, when clicking checkbox in table.
![image](https://user-images.githubusercontent.com/100124568/167613756-bdafb835-8fe1-4134-be38-b291d9314edd.png)

### Steps to reproduce

1. Create new project and select vue 3 and npm
2. Select dependencies: 
![image](https://user-images.githubusercontent.com/100124568/167615754-f5e49a60-1217-4ca4-b8eb-c95bcdc7cb49.png)
3. Import oruga and bulma in main.js
4. Create a new .vue file
5. Add oruga Checkable table example from  --> https://oruga.io/components/Table.html
6. Edit :checked-rows.sync="checkedRows" to v-model:checkedRows  --> so it works with vue 3
7. Select one or more checkbox
8. Press F12 go to Console see error/warning, then open vue dev tools
9. Select the table with the selector then find: checkedRows 
![image](https://user-images.githubusercontent.com/100124568/167615092-ba8e3a8d-7a9e-4e54-ac90-1ebe7abc5c4d.png)
10. Uncheck some, check some different ones

### Expected behavior

checkedRows should update and show selected rows

### Actual behavior

checkedRows are not updated, except when selecting the select all checkbox

**Comment by jtommy** [comment]
@SebastianHenzmann thanks, try to downgrade the Vue 3 version because in the previous versions I didn't see a similar warning.

We'll fix it in the next release 😉
