### ISSUE TITLE
@input event not triggered on o-upload

### ISSUE THREAD

**Issue by wyxos** [oruga-ui/oruga#361]
### @input event not triggered on o-upload

**Oruga** version: [0.5.5]
**Vuejs** version: [3.2.25]
**OS/Browser**: Windows 10/Chrome 

### Description

The @input event is not being triggered on the component o-upload

### Steps to reproduce

- Implement o-upload component as from documentation example
- Add @input event and define a method
- Add console log of event within the new method

### Expected behavior
Log to print under dev tool

### Actual behavior
No log is shown.

**Comment by jtommy** [comment]
There is `@update:modelValue`
