### ISSUE TITLE
Sidebar slide out not working in Vue 3

### ISSUE THREAD

**Issue by jake-armour** [oruga-ui/oruga#362]
### Overview of the problem

**Oruga** version: 0.5.5
**Vuejs** version: 3.1.0
**OS/Browser**: Chrome 101.0.4951.64

### Description

Oruga sidebar doesnt have the slide animation when opening. Initial investigation appears to show that, while the slide out class (`.slide-prev-leave-to`) has been updated for Vue 3, the stylesheet is still using Vue 2 for the enter class (`.slide-next-enter` instead of `.slide-next-enter-to`). The component itself applies the correct class, just seems to be missing the updated styling.

### Steps to reproduce

1. Create `o-sidebar` (our options are fullheight and overlay: true, override: false)
2. Open sidebar and witness it appearing straight away with no slide

### Expected behavior
Sidebar should have transform that slides it in 

### Actual behavior
Sidebar appears with no slide animation

**Comment by jtommy** [comment]
Thanks, can you make a PR to fix it?
