### ISSUE TITLE
Initial value passed is not reflecting on Range Slider

### ISSUE THREAD

**Issue by vindru** [oruga-ui/oruga#364]
### Overview of the problem

**Oruga** version: [0.5.4]
**Vuejs** version: [3.0.0]
**Macos/Chrome**:

### Description

Initial value passed is not reflecting on Range Slider.

```
 <o-field>
      <o-slider v-model="numbers" :min="1" :max="15" :step="0.5" ticks> </o-slider>
  </o-field>
  
  data() {
      return {
        numbers: [2, 5]
      }
   }  
```

### Expected behavior

Expected, [2, 5] as the initial value for slider 

### Actual behavior

Getting, [2,2] as the initial value for slider

 [This](https://github.com/oruga-ui/oruga/blob/develop/packages/oruga-next/src/components/slider/Slider.vue#:~:text=methods%3A%20%7B-,setValues(newValue)%20%7B,%7D%2C,-sliderSize()%20%7B) code is storing minValue to both value1 and value2.

**Comment by jtommy** [comment]
@vindru i'm not able to reproduce on current dev branch (0.5.5), can you share a condesandbox or similar?
