### ISSUE TITLE
Dropdown cut off when inside a Modal

### ISSUE THREAD

**Issue by BuffMcBigHuge** [oruga-ui/oruga#368]
### Overview of the problem

```
vue: 3.2.36
@oruga-ui/oruga-next: 0.5.5
@oruga-ui/theme-bulma: 0.2.5
```

### Description

Adding a dropdown in a modal encapsulates the dropdown menu inside the modal body which results in a bad user experience on desktop.

### Steps to reproduce

[CodeSandbox](https://codesandbox.io/s/oruga-vue3-test-0hcqxy?file=/src/Modal.vue)

### Expected behavior

The dropdown menu should appear above all other components when being accessed.

### Actual behavior

The dropdown is cut off inside the modal body. The dropdown should be fixed to the window rather than absolute to the 
parent component to ensure it displays correctly. I was able to perform a quick solution with the following code:

```
<o-dropdown
  ref="dropdown"
  aria-role="list"
>
  <template #trigger>
    <o-button
      ref="dropdownButton"
    >
      Click Me
    </o-button>
  </template>

  <o-dropdown-item
    v-for="(menuItem, index) in menus"
    :key="index"
    :value="menu"
    aria-role="listitem"
  >
    {{menuItem}}
  </o-dropdown-item>
</o-dropdown>
```

```
let dropdown = this.$refs.dropdown;
const dropdownButtonRect = this.$refs.dropdownButton.$el.getBoundingClientRect();
dropdown.menuStyle.position = "fixed!important";
dropdown.menuStyle.top = `${dropdownButtonRect.top + window.scrollY}px`;
dropdown.menuStyle.left = `${dropdownButtonRect.left + window.scrollX}px`;
```

**Comment by jtommy** [comment]
Did you try using `append-to-body` prop?

**Comment by BuffMcBigHuge** [comment]
You are a lifesaver. Case closed!
