### ISSUE TITLE
Tailwind components

### ISSUE THREAD

**Issue by re2005** [oruga-ui/oruga#370]
As we know **Oruga** is beautiful project, both have super handy components. I'm also Buefy user and love that.

The only great feature request after using these two lib for about 4 years now is styling. I mean, I love the no CSS dependency and the fact that both also provide some styling (Buefy provides it all)

But Oruga, can we do something about Tailwind ? Like refactor the components to be tailwind compatible, and mostly configurable?

```
.o-notification {
    @apply gel-default-bg rounded-3xl p-10 dark:text-gel-brown relative;

    .o-notification__close {
        @apply absolute w-7 h-7 right-3 top-2;

        .o-icon {
            &:before {
                content: 'x';
                @apply text-gray-900 font-normal text-2xl;
            }
        }
    }
}

.o-btn {
    @apply bg-gel-red-dark px-5 py-3 rounded-3xl text-white;
}

```

Something that would look like 👆

Thanks!

**Comment by jtommy** [comment]
Thanks 🙏
There is a old sample project that integrates Oruga with tailwind.
Btw you can use it as you prefer.. overriding the default classes (Oruga minimal CSS) or creating new classes to apply to each components removing the default or in append.
