### ISSUE TITLE
Documentation on how to transition from Buefy to Oruga

### ISSUE THREAD

**Issue by drewda** [oruga-ui/oruga#371]
### Description

Please consider adding a documentation page with step-by-step instructions on how to switch from Buefy to Oruga + a Bulma theme.

### Why Oruga need this feature

Users looking to upgrade from Vue 2.x and Nuxt 2.x to Vue 3.x and Nuxt 3.x will have to switch from Buefy to an alternative: https://github.com/buefy/buefy/issues/2505 

---

In case it is useful to others, I will start to collect my own notes on transitioning a Nuxt 2.x/Buefy project to Nuxt 2.x/`@oruga-ui/oruga`/`@oruga-ui/theme-bulma`. If the maintainers are open to it, this could be useful turning into a documentation page over time.

- `<b-message>` can be replaced by `<o-notification>` https://github.com/oruga-ui/oruga/issues/331#issuecomment-1083538878
- `<b-navbar>` does not appear to have an Oruga replacement
- `<b-tabs v-model="blah">` starts its indexing with a 0, `<o-tabs v-model="blah">` starts its indexing with a 1

**Comment by jtommy** [comment]
As you can see I'm working on new docs compatibile with Vue 3 and i would like to add a dropdown/select to switch base theme, full theme and Bulma theme.

About all differences between Buefy and Oruga maybe better add them to bulma-theme realme.

(the difference about tabs is looks like a issue to be honest 😄 )

**Comment by jtommy** [comment]
@drewda the new docs is available with the last release

**Comment by drewda** [comment]
I see https://github.com/oruga-ui/theme-bulma#buefy-users Thanks!
