### ISSUE TITLE
Active class applied to all dropdown items when `value` is not defined

### ISSUE THREAD

**Issue by themodernpk** [oruga-ui/oruga#378]
### Overview of the problem

**Oruga** version: [0.5.5]
**Vuejs** version: [3.2.37]
**OS/Browser**: Chrome

### Description
If the value is not set for Dropdown Items, and if a dropdown item is clicked, it applies `is-active` class on all the dropdown items

[Screenshot](https://drive.google.com/file/d/1MsuynWxA-9jqOl0PpdWRrU8_B1VT1GYq/view)

### Steps to reproduce

1. Use Oruga with Bulma theme
2. Create a dropdown
3. Click on any dropdown item

### Expected behavior
A) There should be a configuration to define whether an active class should be applied or not.
B) It should apply active class only to the dropdown item which is clicked

### Actual behavior
`is-active` is applied to all dropdown items

**Comment by amorimfilipe** [comment]
Besides applying `is-active` to all dropdown items, the class is persisted. If we close and click again on the dropdown all dropdown items remain with the class, as it happens in [docs](https://oruga.io/components/Dropdown.html).

<img width="223" alt="image" src="https://user-images.githubusercontent.com/7718612/213545735-1ed4aa20-d020-4529-8c75-0ca9dbcd3f66.png">

**Comment by darkylmnx** [comment]
I can confirm this still happens and is especially confusing when there's no need to have a value on items with `tag="router-link"` 

![image](https://user-images.githubusercontent.com/1426357/220504380-2899045b-d420-4f26-b17e-1bfa8eb2c4be.png)

**Comment by andrzejkupczyk** [comment]
I came here to report the same issue. Has it truly been more than a year and a half? 😮 It would be greatly appreciated if we could address it.

https://github.com/oruga-ui/oruga/assets/11018286/67edea70-ef89-41ef-9e34-bd75c4eb8616

**Comment by jtommy** [comment]
It needs value for each item at the moment

**Comment by andrzejkupczyk** [comment]
Thank you for the prompt response! Your assistance is truly helpful. Perhaps, for now, the most cost-effective solution could be adding some information to the documentation, considering that you have more pressing tasks at hand.

**Comment by jtommy** [comment]
Sure, anyway I'll fix it in order to avoid to select all without values

**Comment by andrzejkupczyk** [comment]
Sounds good! Thanks, @jtommy, I really appreciate your work <3

**Comment by mlmoravek** [comment]
Seems to be fixed.
