### ISSUE TITLE
Is There a Proper Way to Use in SFC or by Manually Imports?

### ISSUE THREAD

**Issue by YDX-2147483647** [oruga-ui/oruga#386]
### Description

[In the doc](https://oruga.io/documentation/#setup), Oruga is installed (universally) by `app.use(some_plugin)` even for individual components.

AFAIK, there’s no `app` in [SFC](https://vuejs.org/api/sfc-spec.html)… Is their a proper way to manually import?

```vue
<script>
  import { OButton } from '@oruga-ui/oruga-next'
  // (not real)

  export default {
    components: {
      OButton
    }
  }
</script>

<template>
    <o-button>Click Me</o-button>
</template>
```

### Why Oruga need this feature

- Already implemented!

  (in a trickier way)

  ```js
  import { OButton } from '@oruga-ui/oruga-next/src/components/button'
  ```

- Easier to migrate from other libraries that support this feature. (Eg. [Element Plus](https://element-plus.org/en-US/guide/quickstart.html#manually-import), [Naive UI](https://www.naiveui.com/en-US/os-theme/docs/usage-sfc))

- (For me :-) Oruga offers unique components (eg. `Inputitems` with autocomplete in Vue 3). For some reason, I use Oruga inside a component rather than through out the whole app. Thanks.

> Why does `from '@oruga-ui/oruga-next'` not work?
>
> In [`src/components/button/index.ts`](https://github.com/oruga-ui/oruga/blob/769c98d7b2a60d102409d089576c9a688cfb5382/packages/oruga-next/src/components/button/index.ts), both `default` (the plugin) and `OButton` (the component) are exported.
>
> ```js
> export default {…} as Plugin
> 
> export {
> Button as OButton
> }
> ```
>
> However in [`src/components/index.ts`](https://github.com/oruga-ui/oruga/blob/769c98d7b2a60d102409d089576c9a688cfb5382/packages/oruga-next/src/components/index.ts), only `default` is imported.
>
> ```js
> import Button from './button'
> ```

### Possible Solutions

- Do nothing — just add `import { OButton } from '@oruga-ui/oruga-next/src/components/button'` into the doc.

- Add another `index.ts`, `export { OButton } from './components/button'`.

  > Therefore we can import several components in one line.
  >
  > ```js
  > import { OInputitems, OField, OSwitch } from '@oruga-ui/oruga-next/components'
  > ```
  >
  > Current tricky version:
  >
  > ```js
  > import { OInputitems } from '@oruga-ui/oruga-next/src/components/inputitems'
  > import { OField } from '@oruga-ui/oruga-next/src/components/field'
  > import { OSwitch } from '@oruga-ui/oruga-next/src/components/switch'
  > ```

**Comment by jtommy** [comment]
@YDX-2147483647 did you try something like `import { OButton } from '@oruga-ui/oruga-next/dist/esm/button'`

**Comment by YDX-2147483647** [comment]
It works. Thanks!

**Comment by ishitatsuyuki** [comment]
I think doing imports from `dist/esm` is a poor suggestion: it depends on implementation details, doesn't integrate with IDEs for the same reason, and can also have weird interactions with webpack `resolve.alias` etc.

I've opened #397 as an alternative way to handle this.
