### ISSUE TITLE
Collapse with 2nd button that checks if div is expanded? Is this possible?

### ISSUE THREAD

**Issue by calicoder77** [oruga-ui/oruga#389]
Good evening, I'm going through the official docs and see the **_collapse_** example here: [Oruga Collapse component](https://oruga.io/components/Collapse.html). If I add a second button (Button02), how would I go about checking if the div is expanded? I've been looking for a way to check if the div is expanded and if **_true_** disable it from retracting.
Appreciate the tips and keep up the amazing work. Thank you

```
<o-collapse :open="false" aria-id="contentIdForA11y1">
        <template #trigger="props">
            <o-button
                variant="primary"
                aria-controls="contentIdForA11y1"
                :aria-expanded="props.open"
                >Button01</o-button
            >
            <o-button
                variant="primary"
                aria-controls="contentIdForA11y1"
                :aria-expanded="props.open"
                >Button02</o-button
            >
        </template>
        <div class="notification">
            <p>Lorem ipsum dolor sit amet</p>
        </div>
</o-collapse>
```

**Comment by jtommy** [comment]
Trigger slot is a scoped slot and emit `props`, for example `open`

`v-slot:trigger="{ open }"`

**Comment by calicoder77** [comment]
I'm not 100% sure if this is a bug but I changed the Button02 code above to:
`<o-button variant="primary" v-slot:trigger="{ open }">Button02</o-button>` and it still closes the collapse. Shouldn't it force open the div for me?

**Comment by jtommy** [comment]
Do you see the button? In Vue 3 you have to put the slot to template element

**Comment by calicoder77** [comment]
I do see the button after adding the change to the template tag: `<template #trigger="props" v-slot:trigger="{ open }">`

**Comment by jtommy** [comment]
Mmm no `v-slot` is an alternative of `#slot`
