### ISSUE TITLE
Deprecated methods for vue 3

### ISSUE THREAD

**Issue by bzd2000** [oruga-ui/oruga#39]
Hi,

Thx for providing the Vue 3 branch.

There are some methods now depricated:
Vue warn]: `beforeDestroy` has been renamed to `beforeUnmount`. 
  at <OTableColumn field="id" label="title" sortable="" > 
  at <OTable data= (3) [{…}, {…}, {…}] isPaginated:="" true,=""  ... > 
  at <HostListings onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {…} > > 
  at <RouterView> 
  at <HostLayout onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {…} > > 
  at <RouterView> 
  at <App>

I can fix it, but it seems there is one code base for vue2 and vue3.
What is strategy to maintain those 2?

**Comment by jtommy** [comment]
Yes, i know and I added it the mixin.
What's the warning?

**Comment by bzd2000** [comment]
Vue warn]: beforeDestroy has been renamed to beforeUnmount.

**Comment by jtommy** [comment]
Mmm ok, I should remove it when Vue version is 3

**Comment by bzd2000** [comment]
@jtommy , i have some other issues. 
I'll log them all?

**Comment by jtommy** [comment]
You should open new issues, thanks

**Comment by jtommy** [comment]
I'm working on rewriting a different codebase for Vue 3
