### ISSUE TITLE
Error on unmounting a table with columns declared with property

### ISSUE THREAD

**Issue by akhma-ps** [oruga-ui/oruga#392]
### Overview of the problem
When trying to unmount a table in any way, an error occurs if the columns are specified via the `:columns=""` property.

**Oruga** version: [0.5.5]
**Vuejs** version: [3.2.33]
**OS/Browser**: macOS Monterey 12.3/Chrome 103.0.5060.114

### Description
Demo: https://codesandbox.io/s/oruga-table-unmount-bug-nn7kox
Turn off the switch at the top. You should get an error:
`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'type')`

### Steps to reproduce

1. Add the OTable component
2. Describe any columns vie the `:columns` property 
3. Unmount the table at runtime. For example using `v-if`

### Expected behavior

The table should unmount without any errors

### Actual behavior

An error occurs: `Uncaught (in promise) TypeError: Cannot read properties of null (reading 'type')`

**Comment by jtommy** [comment]
https://github.com/oruga-ui/oruga/issues/344
