### ISSUE TITLE
Taginput: Close on select

### ISSUE THREAD

**Issue by urkle** [oruga-ui/oruga#395]
### Description

Add an option to the inputitems component to have the dropdown close after selecting an entry.  

Currently the component ties the behavior to the open-on-focus setting.. these should be separate concerns and not tied together.

### Why Oruga need this feature

More flexibility and usability for apps.

**Comment by jtommy** [comment]
@urkle it's a nice feature, do you want to work on it?

**Comment by gbrrrl-no** [comment]
@jtommy is this issue still active? Can I work on it?

**Comment by jtommy** [comment]
@gbrrrl-no sure

**Comment by mlmoravek** [comment]
This is already implemented with the `keepOpen` prop, which is the same function, just in reverse. The `keepOpen` prop is implemented in the Autocomplete component on which the Taginput component depends. The default value is `false`, so the inverted behaviour is like close on select, which is therefore enabled by default.
