### ISSUE TITLE
Click events are prevented inside carousel components

### ISSUE THREAD

**Issue by michastubi** [oruga-ui/oruga#399]
### Overview of the problem

**Oruga** version: 0.5.5
**Vuejs** version: 3.2.37
**OS/Browser**: Firefox, Chrome...

### Description

This bug can be seen in the Oruga Documentation itself at the "custom" Example: 
[https://oruga.io/components/carousel.html#custom](https://oruga.io/components/carousel.html#custom
)

### Steps to reproduce

1. Add a input inside a carousel component
2. Try to focus the input

### Expected behavior

The input is focused.

### Actual behavior

Nothing happens

### Solution

Inside the carousel component there are following lines:

```   
          <div
                @mousedown.prevent="dragStart"
                @touchstart="dragStart"
                :class="itemsClasses"
                :style="'transform:translateX('+translation+'px)'">
                <slot/>
            </div>
```
By removing `prevent `from `@mousedown` the problem is fixed. But I am not sure if this will cause other problems.

Thanks for your great work!
Micha

**Comment by jtommy** [comment]
You can make a PR to fix it checking if there is a reason to maintain `prevent`, what do you think?

**Comment by jtommy** [comment]
@michastubi did you investigate about it?

**Comment by jtommy** [comment]
fix https://github.com/oruga-ui/oruga/commit/159201e1dfd7f0342585c377e932a97d0b5d04d2
