### ISSUE TITLE
Add update feeds to discord server [Webhook]

### ISSUE THREAD

**Issue by zhaolinlau** [oruga-ui/oruga#405]
### Description

[Example from youtube](https://youtu.be/-KDQqWNK3Tw)

### Why Oruga need this feature

To improve the community server of oruga

**Comment by jtommy** [comment]
It could be helpful for new release!

**Comment by zhaolinlau** [comment]
> It could be helpful for new release!

May separate into several channels like pulls, commits, issues, releases, and issues' comments

**Comment by jtommy** [comment]
Probably commit is too invasive but we might start to something

**Comment by zhaolinlau** [comment]
> Probably commit is too invasive but we might start to something 

Sure
