### ISSUE TITLE
Add loading prop to button component

### ISSUE THREAD

**Issue by luisdnodrizat** [oruga-ui/oruga#406]
### Description

Please add loading prop to Button component.

### Why Oruga need this feature

Is very useful like buefy buttons:
https://buefy.org/documentation/button

**Comment by jtommy** [comment]
There is already a open PR https://github.com/oruga-ui/oruga/pull/376, but I have to decide how to implement it

**Comment by luisdnodrizat** [comment]
Thank you,
I was able to integrate the loader into my project using the code from the PR.
Temporal solution :)

**Comment by jtommy** [comment]
Ok, but keep in mind that i might change it and add the feature in other way
