### ISSUE TITLE
Configure keyup enter to button

### ISSUE THREAD

**Issue by luisdnodrizat** [oruga-ui/oruga#409]
### Description

Is there a way to configure @keyup.enter to a Button component?

### Why Oruga need this feature

Sometimes in some forms it is useful to be able to do this.

Please add "question" tag for this Issue. Thank you!

**Comment by jtommy** [comment]
`<o-button @keyup.enter>Btn</o-button>`, like native button

**Comment by jtommy** [comment]
Can you reproduce on codepen or similar?
