### ISSUE TITLE
Content of modal gets overlayed

### ISSUE THREAD

**Issue by fmoessle** [oruga-ui/oruga#412]
### Overview of the problem

"@oruga-ui/oruga-next": "0.5.6"
"nuxt": "3.0.0-rc.9"
OS/Browser**: Chrome/Safari/Firefox (latest)

### Description

This might be a regression of: fix(modal): modal content position attribute.

It worked with "@oruga-ui/oruga-next": "0.5.5"

When opening a modal, the content gets under the overlay. This even happens on the official docs:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/17830282/189835674-6e222383-01dc-4dad-a897-e591ae5d4ca8.png">

### Expected behavior

Modal content shouldn't get overlayed.

**Comment by emeric254** [comment]
Same problem with `@oruga-ui/oruga`

forcing `"@oruga-ui/oruga": "=0.5.5",` in package.json solved the problem

**Comment by jtommy** [comment]
Probably the fix https://github.com/oruga-ui/oruga/commit/41d9475999faf5940f272604104240934074682c broke the modal style using the default css. Just to override it instead of downgrade to 0.5.5

**Comment by Roldification** [comment]
hello sir @jtommy , can you also make a fix on this on the Bulma CSS? Your help is greatly appreciated. Thank you!
