### ISSUE TITLE
Component request : Menu

### ISSUE THREAD

**Issue by nioc** [oruga-ui/oruga#414]
### Description

The [buefy menu component](https://buefy.org/documentation/menu/ ) is great.
I understand it was proposed in merge request #70 year ago, then removed. Do you plan to propose a menu component?

### Why Oruga need this feature

It is a frequently used component.

**Comment by groundfloorwebb** [comment]
+1 to this, the menu components are one of the most important gaps blocking my team from adopting oruga. Looks like the old PR only includes vue 2 support and would need a fair amount of work to complete. I'm happy to help out with implementation.

**Comment by jtommy** [comment]
@groundfloorwebb it would be great! You might start from scratch, the current PR is really old

**Comment by jtommy** [comment]
Ref: https://github.com/oruga-ui/oruga/pull/419

**Comment by nioc** [comment]
Thanks a lot @groundfloorwebb
