### ISSUE TITLE
Datepicker - month picker differences in prop types

### ISSUE THREAD

**Issue by beljand** [oruga-ui/oruga#417]
### Overview of the problem

**Oruga** version: [0.5.6]
**Vuejs** version: [2.7.8]
**OS/Browser**: MacOS / Chrome

### Description

`selectabledates` in https://github.com/oruga-ui/oruga/blob/develop/packages/oruga/src/components/datepicker/Datepicker.vue#L378 must be and `Array`, but when using a Month picker, the same prop can be also a `Function` - https://github.com/oruga-ui/oruga/blob/develop/packages/oruga/src/components/datepicker/DatepickerMonth.vue#L61.

Vue throws a warning `Invalid prop: type check failed for prop "selectableDates". Expected Array, got Function`

### Steps to reproduce

- use `ODatepicker`
- add `type="month"`
- provide a function for `selectableDates`

### Expected behavior

- prop `selectableDates` in `Datepicker.vue` should accept both `Array | Function`

### Actual behavior

- prop `selectableDates` in `Datepicker.vue` accepts only `Array` while `DatepickerMonth` accepts `Array | Function`

**Comment by jtommy** [comment]
You are right, can you make a PR?

**Comment by beljand** [comment]
> You are right, can you make a PR?

Will do
