### ISSUE TITLE
Detailed row opens at the end of the table instead of right under the row

### ISSUE THREAD

**Issue by kevincote** [oruga-ui/oruga#42]
### Overview of the problem

**Oruga** version: 0.2.2
**Vuejs** version: 2.6.11
**OS/Browser**: Chrome

### Description

When toggling a detailed row, the detail section appears at the end of the table. 

### Steps to reproduce

This behavior is present in the documentation examples. See: https://oruga.io/components/table.html#detailed 

### Expected behavior

It should open the detailed row under the row in which the toggle has been done.

### Actual behavior

The detailed row opens at the end of the table.

![image](https://user-images.githubusercontent.com/31894882/96023767-eba2f600-0e20-11eb-8baa-5fb4f7f7b677.png)

**Comment by jtommy** [comment]
You are right! I'll check it soon

**Comment by krizzdev** [comment]
We have the same problem. Thanks for checking. Any updates on this? :)

**Comment by jtommy** [comment]
Fixed https://github.com/oruga-ui/oruga/commit/1ea97d1cfa19446f7baa4cebda67b6f3a283769c and rewriting for Vue 3 (wip)
