### ISSUE TITLE
How do you run the oruga-next tests?

### ISSUE THREAD

**Issue by travatomic** [oruga-ui/oruga#424]
I found instructions [here](https://github.com/oruga-ui/oruga/blob/develop/.github/CONTRIBUTING.md?plain=1#L83) for running the `oruga` tests, but I can't seem to work out how to run the `oruga-next` tests. How do you run the `oruga-next` tests?

**Comment by jtommy** [comment]
@travatomic it doesn't have any unit tests, there is a PR that uses cypress but it's working in progress.
