### ISSUE TITLE
o-input not showing data inside o-field

### ISSUE THREAD

**Issue by tanhs** [oruga-ui/oruga#426]
### Overview of the problem

**Oruga** version: [0.5.6]
**Vuejs** version: [3.2.40]
**OS/Browser**:Windows 10/Firefox105.0.2

### Description

Problem with o-field and o-input, value are not show in the input tag, no error showing in console, screenshot attached

### Steps to reproduce
if the o-input is inside o-field, it will not show anything
```
<div class="column">
			<o-field label="batch_details_id" horizontal labelSize="small">
				<o-input
					v-model="apacDtls.batch_details_id"  <---- not showing data
				/>
			</o-field>

  </div>
![Capture](https://user-images.githubusercontent.com/1995229/195229277-a8168b25-1d6e-492a-88c6-d75a905e6b23.PNG)

  <div class="column">
			<o-field label="lab_id" horizontal labelSize="small">
				test {{ apacDtls.lab_id }}   <---- it shows data
				<o-input
					v-model="apacDtls.lab_id"             <------ not showing data in input
				/>
			</o-field>
</div>
```

### Expected behavior

Data should show in input tag

### Actual behavior

not showing data

**Comment by jtommy** [comment]
@tanhs can you reproduce on codepen or similar?
