### ISSUE TITLE
OField message slot not rendered when horizontal

### ISSUE THREAD

**Issue by lucifilote** [oruga-ui/oruga#427]
### Overview of the problem

**Oruga** version: [0.5.6]
**Vuejs** version: [2.7.10]
**OS/Browser**:

### Description

When using 
``<o-field horizontal>
``
`         <template #message>Message goes here</template>`
`
  </o-field>`

The #message slot is not rendered.

### Steps to reproduce

1. Create an o-field with `horizontal` set to `true`
2. add child template for slot #message

### Expected behavior

Message slot should be rendered

### Actual behavior

Message slot is not rendered

**Comment by yoji-kojio** [comment]
hey @lucifilote ! I believe that this behaviour is intentional
https://github.com/yoji-kojio/oruga/blob/develop/packages/oruga/src/components/field/Field.vue#L34-L40

`message` slot will exist only if `horizontal` props is not enabled!

**Comment by yoji-kojio** [comment]
@jtommy @astagi can you tell us if this is intentional or a bug? 😸

**Comment by jtommy** [comment]
@yoji-kojio it's a bug!

**Comment by yoji-kojio** [comment]
@jtommy can you assign to me? I will open a PR :D

**Comment by jtommy** [comment]
@yoji-kojio I had to revert your PR, it shows two messages and it break the HTML template

**Comment by tector** [comment]
Any update on this issue?
