### ISSUE TITLE
Values passed on range slider are not showing correctly

### ISSUE THREAD

**Issue by saadrhiri** [oruga-ui/oruga#429]
### Overview of the problem

**Oruga** version: [0.5.0]
**Vuejs** version: [2.6.14]
**MacOS/Chrome**:

### Description

Values passed on range slider are not showing correctly, or more precisely the min value is right but the max value gets also the initial value of min.

``<o-slider
          v-model="range"
          :tooltip="false"
          tooltip-variant="info"
          :disabled="loading"
          :min="min"
          :max="max"
          :step="step"
        />``

### Expected behavior

min = x
max = y

### Actual behavior

min = x 
max = x

**Comment by jtommy** [comment]
@saadrhiri can you reproduce on codepen o similar? I am not able to see the error looking at the docs.
