### ISSUE TITLE
Table: add props to set table class (and th class)

### ISSUE THREAD

**Issue by bzd2000** [oruga-ui/oruga#43]
Hi,

Is it possible to add a prop to the table component in order add  class on table
This is needed to manage the width of the columns with tailwindcss (table-auto, table-fixed)
Maybe also something is needed at th level to specify the width by tailwind class (w-32, w-1/3)

Thx,
Filip.

**Comment by jtommy** [comment]
It's the main scope of Oruga as you can see in the docs.. https://oruga.io/components/Table.html#props

**Comment by bzd2000** [comment]
@jtommy , I don't see how to set a class on the table tag itself

**Comment by jtommy** [comment]
Oh you are right, i'add one but at the moment you can use rootClass and apply your style on inner table
