### ISSUE TITLE
Outline: none prevents keyboard visible focus

### ISSUE THREAD

**Issue by mmazanec22** [oruga-ui/oruga#432]
### Overview of the problem

**Oruga** version: 0.5.6
**Vuejs** version: 3.2.30
**OS/Browser**: Pop!_OS/Chrome

### Description

The presence of `outline: none` on interactive elements prevents them from receiving visible keyboard focus. This is a conflict with [WCAG Success Criterion 2.4.7 Focus Visible (Level AA)](https://www.w3.org/TR/WCAG21/#focus-visible): any keyboard operable user interface has a mode of operation where the keyboard focus indicator is visible.

This issue does appear to be addressed for the button [in the next version of the docs in lines 155 - 163.](https://github.com/oruga-ui/oruga/blob/8097a06e7fb929ea61bc0f6f0a72901fd92cb6b5/packages/docs-next/.vitepress/theme/styles/base.css#L155)

The workaround I'm using now in my project's css:
```
[class^="o-"] {
  outline: revert !important;
}
```

### Steps to reproduce

Use the tab key to navigate on a page where there are interactive Oruga elements, like buttons, radio buttons, checkboxes, dropdowns, etc (but not the buttons in the docs, because this issue is addressed there).

### Expected behavior

I would expect keyboard users to be able to navigate through a page with interactive elements and see an outline (either the one that the browser shows natively or an Oruga-specified outline) indicating which element is receiving focus.

An example of clear visual focus can be seen on the [USWDS website and other federal websites that use that library](https://designsystem.digital.gov/). If you use the tab key to navigate that page, a thick blue outline shows up to indicate which element you are interacting with.

### Actual behavior

Since `outline: none` is set on many of the interactive elements in this library, interactive elements do not receive visible keyboard focus. A project using this library will not meet WCAG level AA and presents a barrier for keyboard users.

**Comment by jtommy** [comment]
Can you make a PR to fix the default theme?
