### ISSUE TITLE
Read only support in o-input

### ISSUE THREAD

**Issue by netoec84** [oruga-ui/oruga#434]
### Description

`readonly` property is not supported in `o-input`. Sometimes this functionality is needed so it would be useful to add it

### Why Oruga need this feature

Complements the current operation of `o-input`, additionally the `readonly` property is native in the `<input>` tag

I can add the support, but in the contribution guide it was suggested to post it as an Issue before developing it

**Comment by jtommy** [comment]
@netoec84 there isn't a class because you can style it with readonly attribute by CSS but if you want to add a new class prop you are welcome 😉
