### ISSUE TITLE
Sidebar Hidden/Showing Classes 

### ISSUE THREAD

**Issue by mlmoravek** [oruga-ui/oruga#435]
### Description
It would be create to define specific classes for each the hidden and the showing state of the Sidebar component. 

Todo: Expend the computed prop _contentClasses_ in Sidebar.vue with "shownClass" if _isOpen_ else "hiddenClass". 

### Why Oruga need this feature
Some CSS-Frameworks like Bootstrap set specific classes when their sidebar (called Offcanvas in Bootstrap) is in the open or hidden state .

**Comment by jtommy** [comment]
You are welcome 😉
