### ISSUE TITLE
Methods property "noticeCustomContainerClasses" is already defined in Props in the Notification Component

### ISSUE THREAD

**Issue by jeevan-lal** [oruga-ui/oruga#437]
**Overview of the problem**

Oruga version: 0.5.8
Vue version: 3.2.37

**Description**

I'm using notification component like this:

```js
oruga.notification.open({ message: `Copied!`, position: 'bottom', variant: 'success', duration: 1000 });
```

this warning coming..

<img width="959" alt="image" src="https://user-images.githubusercontent.com/40091315/200175402-369d49a4-0f01-4b8f-b46d-2f66e1e89da7.png">

**Comment by jtommy** [comment]
Ok, it's only a warning it should be easy to fix it (you can make a PR if you want)
