### ISSUE TITLE
Cant customize styling using scss variable (oruga-next)

### ISSUE THREAD

**Issue by gmw-web** [oruga-ui/oruga#438]
### Overview of the problem

**Oruga** version: @oruga-ui/oruga-next @v0.5.8
**Vuejs** version: 3.2.41
**OS/Browser**: Chrome latest

### Description
Cant customize styling using SCSS variables when following the instructions from the docs:
https://oruga.io/documentation/#using-css-or-sass-scss-variables

I saw this issues: https://github.com/oruga-ui/oruga/issues/87, but that seems to apply to `oruga` instead of `oruga-next` and the same setup doesn't seem to work any more.

### Steps to reproduce
I'm using the following setup:

This works (CSS variables)
```
// assets/styles.scss

:root {
  --oruga-variant-primary: #cc3300;
}


// main.ts

import "assets/styles.scss"
import "@oruga-ui/oruga-next/dist/oruga-full-vars.css";
```

But when I switch to SCSS variables, the custom styling isn't applied:
```
// assets/styles.scss

$variant-primary: #cc3300; // also tried '$oruga-variant-primary' and '$primary'


// main.ts

import "assets/styles.scss"
import "@oruga-ui/oruga-next/src/scss/oruga-full-vars.scss";
```

**Comment by jtommy** [comment]
@gmw-web you should import `@oruga-ui/oruga-next/src/scss/utilities/_variables.scss` and the set your variable values and oruga theme
