### ISSUE TITLE
horizontal field somewhat broken in 0.5.8

### ISSUE THREAD

**Issue by mat813** [oruga-ui/oruga#442]
### Overview of the problem

**Oruga** version: 0.5.8
**Vuejs** version: 3.2.41
**OS/Browser**: Firefox Linux

### Description

After 9e5b406e33b63ce3c0feeafd356f290eda829922 which fixes  #427, it seems `<o-field horizontal>` is broken, there is a new div without any styling on the input side, and it lacks the correct flex attributes to display correctly.

### Steps to reproduce

```help
    <o-field horizontal label="Foo">
      <o-input></o-input>
    </o-field>
```
now generates 

```html
<div class="field is-horizontal">
  <div class="field-label"><label class="label">Foo</label></div>
  <div class="">
    <div class="field-body">
      <div class="field"><div class=""><!--v-if--></div><div class=""><div class="control"><input class="input" type="text" autocomplete="off"><!--v-if--><!--v-if--><!--v-if--></div><!--v-if--></div></div>
    </div><!--v-if-->
  </div>
</div>
```

### Expected behavior

If I manually edit the html in the devtools and remove the outer div with the empty class I get what I was expecting:

![20221109-114638_1425x86](https://user-images.githubusercontent.com/75783/200810482-8ba56335-0d49-4966-bdb7-d2d890ccfb11.png)

### Actual behavior

But with what is now generated, the right part of the field does not has the grow bits, and it gets shrunk:

![20221109-114333_1442x101](https://user-images.githubusercontent.com/75783/200809806-61dfd4b6-6c2c-4524-9aa1-a4cad7df6c66.png)

**Comment by mat813** [comment]
But maybe the problem is in https://github.com/oruga-ui/theme-bulma/

**Comment by jtommy** [comment]
@mat813 you are right, i'll will revert it
