### ISSUE TITLE
Background property overwrites background-size property

### ISSUE THREAD

**Issue by lucifilote** [oruga-ui/oruga#449]
### Overview of the problem

**Oruga** version: [0.5.9]
**Vuejs** version: [2.7.10]
**OS/Browser**: any

### Description

Using the `background` shorthand css property to set the color only overwrites other background css property like `background-size`.

### Steps to reproduce

https://user-images.githubusercontent.com/9740270/203086376-23aeabf1-6e77-48fb-8d93-de978bab5635.mov

### Expected behavior

`background-size` shouldn't be overwritten by background property

### Actual behavior

`background-size` property effect is lost

**Comment by jtommy** [comment]
Probably you are right, can you make a PR?
