### ISSUE TITLE
Expose o-steps__divider background color to variable

### ISSUE THREAD

**Issue by luisdnodrizat** [oruga-ui/oruga#451]
### Description
Expose o-steps__divider background color to variable:
--oruga-steps-divider-color

### Why Oruga need this feature
I can not change steps divider background color.
Variants not working.

**Comment by luisdnodrizat** [comment]
Temporal solution:

`<o-steps v-model="activeStep"
                        :animated="true"
                        :rounded="true"
                        :hasNavigation="false"
                        **:variant="'primary'"**>`

`.o-steps__nav-item--primary.o-steps__nav-item-active .o-steps__marker {
    background-color: var(--oruga-variant-invert-primary, #ffffff);
    border-color: var(--oruga-variant-primary, var(--YOUR_CUSTOM_COLOR));
    color: var(--oruga-variant-primary, var(--YOUR_CUSTOM_COLOR));
}
.o-steps__nav-item--primary.o-steps__nav-item-active .o-steps__divider {
    background: linear-gradient(to left, #dbdbdb 50%, var(--YOUR_CUSTOM_COLOR) 50%);
    background-size: 200% 100%;
}
.o-steps__nav-item--primary.o-steps__nav-item-previous .o-steps__marker {
    color: var(--oruga-variant-invert-primary, #ffffff);
    background-color: var(--oruga-variant-primary, var(--YOUR_CUSTOM_COLOR));
}
.o-steps__nav-item--primary.o-steps__nav-item-previous .o-steps__divider {
    background: linear-gradient(to left, #dbdbdb 50%, var(--YOUR_CUSTOM_COLOR) 50%);
    background-size: 200% 100%;
}`

**Comment by jtommy** [comment]
@luisdnodrizat Can you make a PR to add the variable?
