### ISSUE TITLE
Vue3: Dropdown error in console (breaks component)

### ISSUE THREAD

**Issue by bzd2000** [oruga-ui/oruga#46]
### Overview of the problem

**Oruga** version: [next]
**Vuejs** version: [3.0.1]
**OS/Browser**: chrome

### Description
The following error in console

```
dropdown.js?3f50:603 Uncaught (in promise) TypeError: this.$destroy is not a function
    at Proxy.created (dropdown.js?3f50:603)
    at callSyncHook (runtime-core.esm-bundler.js?5c40:5475)
    at applyOptions (runtime-core.esm-bundler.js?5c40:5428)
    at finishComponentSetup (runtime-core.esm-bundler.js?5c40:6050)
    at setupStatefulComponent (runtime-core.esm-bundler.js?5c40:5986)
    at setupComponent (runtime-core.esm-bundler.js?5c40:5926)
    at mountComponent (runtime-core.esm-bundler.js?5c40:4207)
    at processComponent (runtime-core.esm-bundler.js?5c40:4183)
    at patch (runtime-core.esm-bundler.js?5c40:3788)
    at mountChildren (runtime-core.esm-bundler.js?5c40:3996)
```

### Steps to reproduce

```
<template>
<div>
  <o-dropdown aria-role="list">
    <template v-slot:trigger>
    <o-button variant="primary"  >
      <span>Click me!</span>
      <o-icon icon="caret-down"></o-icon>
    </o-button>
    </template>

      <o-dropdown-item aria-role="listitem">Action</o-dropdown-item>
      <o-dropdown-item aria-role="listitem">Another action</o-dropdown-item>
      <o-dropdown-item aria-role="listitem">Something else</o-dropdown-item>
    </o-dropdown>
</div>

</template>

<script>
export default {}
</script>
```

**Comment by bzd2000** [comment]
If you want I could also update the docs with vue3 example
the dropdown example for dropdown doesn't work for vue2

**Comment by jtommy** [comment]
You can make a PR and remove destroy call

**Comment by Rezvitsky** [comment]
Hello! I apologize for disturbing, but can I ask this the only use case for dropdown or are there alternatives? I don't like this approach:

`<o-dropdown aria-role="list">
					<template v-slot:trigger>
						<o-button variant="primary"  >
							<span>Click me!</span>
							<o-icon icon="caret-down"></o-icon>
						</o-button>
					</template>

					<o-dropdown-item aria-role="listitem">Action</o-dropdown-item>
					<o-dropdown-item aria-role="listitem">Another action</o-dropdown-item>
					<o-dropdown-item aria-role="listitem">Something else</o-dropdown-item>
				</o-dropdown>`

**Comment by jtommy** [comment]
@Rezvitsky can you explain better?

**Comment by Rezvitsky** [comment]
See, I like the example as in the documentation, but for some reason it refuses to work: https://gist.github.com/08a7ba6d8609c5101ac0c4b6988ce6d8

And the example given by "bzd2000" is working but I don't want to use template

**Comment by jtommy** [comment]
Why don't you want to use template??

**Comment by Rezvitsky** [comment]
It will be funny, but my perfectionism doesn't allow it. I can of course leave it as it is.
