### ISSUE TITLE
Widths on o-table columns incorrectly applies to card mode (oruga-next)

### ISSUE THREAD

**Issue by Pluckerpluck** [oruga-ui/oruga#464]
### Overview of the problem

**Oruga** version: 0.5.9 (Or whatever is being used on the website)
**Vuejs** version: 3 (Only, this doesn't happen on the Vue 2 version))
**OS/Browser**: Firefox & Chrome

### Description

Using a "width" on any table column, as is done in the example for o-table, creates a problem in card mode. The width continues to apply, and thus the value isn't right aligned as it should be.

In reality, the width should be removed (i.e. 100%) when going into card mode, and restored in "full" mode.

![image](https://user-images.githubusercontent.com/175488/207086139-6a4d418a-c442-471e-83dd-258c4062bbb5.png)

### Expected Outcome

From the Vue 2 examples:

![image](https://user-images.githubusercontent.com/175488/207087199-275fb557-d0b1-42a1-9346-e9dbda40c8cd.png)

**Comment by jtommy** [comment]
fix https://github.com/oruga-ui/oruga/commit/9aaabf0fef3f651e08c38bd70b4c2cbe5a388de9
