### ISSUE TITLE
Table: tdAttrs not setting class for the 2nd page data when infinite scroll is used

### ISSUE THREAD

**Issue by vimalrajgit** [oruga-ui/oruga#465]
tdAttrs not setting class for the 2nd page data when infinite scroll is used

**Oruga** version: 0.5.9
**Vuejs** version: 3.2.40
**OS/Browser**: chrome

@jtommy recenty i updated my project to latest oruga version, i actually use infinite scroll which i had written on own but not the table pagination. When the first set of data is loaded in table the column td has custom class which i specified in tdAttrs but when the next set of data is loaded the tdAttrs class is not set to those 2nd set of data.

seems to be https://github.com/oruga-ui/oruga/commit/1a02e473f6964a2c012ce48e3c1c59db997814c4 this changes is causing the issue.

Need suggestions to add custom class to the td for remaining set of data.

**Comment by jtommy** [comment]
You are right, it uses index and colindex, my bad 😞

**Comment by jtommy** [comment]
@vimalrajgit can you share your code? I fixed it but I'm not sure about your problem

**Comment by vimalrajgit** [comment]
@jtommy i dont have access to provide the code base to test this issue, if i get the branch name i can check and let you know.

**Comment by jtommy** [comment]
@vimalrajgit just a reproduction using fake data it's enough

**Comment by vimalrajgit** [comment]
ok @jtommy once ready will share the code to you.

**Comment by vimalrajgit** [comment]
@jtommy please use https://github.com/vimalrajm/oruga-demo this project for debugging, As i mention in the issue td class is not adding for second page which i couldn't reproduce initially and then i found out using :backendFiltering="true" prop is not adding td class for starting page itself.
