### ISSUE TITLE
value and :value do not work with o-input

### ISSUE THREAD

**Issue by TAtherah** [oruga-ui/oruga#466]
### Overview of the problem
value and :value do not work with o-input
**Oruga** version: [0.5.9]
**Vuejs** version: [3.2.45]
**OS/Browser**:
Windows, and edge and chrome

### Steps to reproduce
you can see the issue in Oruga's documentation: https://oruga.io/components/Field.html
the first field in the page "Name" should display the value "Kevin Garvey". but it does not

**Comment by jtommy** [comment]
Mmm you should use `model-value`

**Comment by TAtherah** [comment]
Thanks Jtommy, it works.
But the standard and always used is "value". this is in my legacy code and it goes with the HTML components "<input/>".

**Comment by jtommy** [comment]
@TAtherah https://vuejs.org/guide/components/events.html#usage-with-v-model
