### ISSUE TITLE
cdn link typo

### ISSUE THREAD

**Issue by zhaolinlau** [oruga-ui/oruga#468]
![image](https://user-images.githubusercontent.com/68846168/209798763-a926553e-854c-4352-92ce-0beb14da8521.png)

should be
https://unpkg.com/@oruga-ui/oruga-next/dist/oruga.min.css
https://unpkg.com/@oruga-ui/oruga-next/dist/oruga.min.js

**Comment by jtommy** [comment]
Ok, can you make a PR to fix it?

**Comment by zhaolinlau** [comment]
> Ok, can you make a PR to fix it?

done
