### ISSUE TITLE
[question] Can the sidebar component be configured to open from the bottom on mobile?

### ISSUE THREAD

**Issue by idank** [oruga-ui/oruga#473]
This should be handy for somewhat wide sidebars that take most of the screen width on small screens. Here's how that'd look: https://merch.deno.com/ (by clicking the cart and resizing).

Can the various config knobs on the sidebar get this kind of behavior? Thanks!

**Comment by astagi** [comment]
Hi @idank seems there's no setting to make sidebar appearing from the bottom, I also think that is not a feature that could be related to sidebar, the demo you provide shows something more similar to a popup. @jtommy do you agree?

**Comment by jtommy** [comment]
Yes it looks a different component

**Comment by idank** [comment]
There are many components here that expose "mobile friendly" behavior, how is this different?

**Comment by mlmoravek** [comment]
@idank The sidebar now has a new `position` property that allows the sidebar to open from the bottom if the theme implements the necessary style.

Feel free to reopen if you have any further problems.
