### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by idank** [oruga-ui/oruga#474]
I'm using the Bulma theme with `$rtl: true` in my scss and `dir=rtl` on my `body` and it appears some components don't render quite right in RTL, specifically so far I've noticed Steps looks off:

<img width="376" alt="image" src="https://user-images.githubusercontent.com/1277636/213305240-343871cb-d98b-4062-ae84-3b6ae8d87420.png">

```
<o-steps v-model="store.activeStep" animated="true" rounded="true" has-navigation="false" label-position="bottom" 
  size="small" stepMarkerClass="mb-2" stepContentClass="pt-5" stepLinkLabelClass="has-text-weight-normal">
  
  <o-step-item step="1" label="Design" :clickable="true">
    <DesignStep @done="designStepDone" />
  </o-step-item>
  
  <o-step-item step="2" label="Material" :clickable="materialStepClickable">
    <MaterialStep @done="store.activeStep = 3" />
  </o-step-item>
  
  <o-step-item step="3" label="Quote" :clickable="store.selectedMaterialVariant != null">
    <QuoteStep />
  </o-step-item>
</o-steps>
```

How would I go about fixing this? Either locally or in Oruga itself.

**Comment by idank** [comment]
@jtommy any chance you could take a look and provide some guidance here? This is one of the main blockers for our launch.

**Comment by idank** [comment]
Another thing I noticed is the direction of the step content swipe animation should be flipped as well.

**Comment by jtommy** [comment]
We might manage it on Bulma repo 😉
