### ISSUE TITLE
Missing role="switch" attribute on <o-switch> component

### ISSUE THREAD

**Issue by didaquis** [oruga-ui/oruga#484]
### Overview of the problem

**Oruga** version: 0.5.10 
**Vuejs** version: 2.7
**OS/Browser**: all browsers

### Description

The component Switch does not contain the correct attribute role. Actually the role is "checkbox" but should be "switch". 

More info about differences between "checkbox" and "switch" can be read about here: 
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/switch_role 

More info: 
https://www.magentaa11y.com/checklist-web/toggle-switch/ 
https://www.w3.org/WAI/ARIA/apg/patterns/switch/ 
https://w3c.github.io/aria/#switch 

### Steps to reproduce

Just use the <o-switch> component: 

<img width="607" alt="Captura de pantalla 2023-02-09 a las 15 25 05" src="https://user-images.githubusercontent.com/6883041/217841365-3f12be41-3c90-45a1-8708-179fcd5cb95c.png">

### Expected behavior

The role of input should be "switch"

### Actual behavior

Currently the role of input is "checkbox"

**Comment by didaquis** [comment]
Related info: 

<img width="896" alt="Captura de pantalla 2023-02-13 a las 11 08 51" src="https://user-images.githubusercontent.com/6883041/218429699-2c958458-0aff-4986-998f-d9d95fe5df66.png">

Source: https://testing-library.com/docs/queries/byrole#queryfallbacks

**Comment by jtommy** [comment]
@didaquis you are right, can you make a PR?

**Comment by didaquis** [comment]
@jtommy 

I have already created a merge request.
When you have 5 minutes, take a look at it and give me your feedback.

**Comment by jtommy** [comment]
@didaquis thanks 👍
