### ISSUE TITLE
The is-checked class on the o-table row is missing when the user clicks on the checkbox in the table-row.

### ISSUE THREAD

**Issue by amirameeen** [oruga-ui/oruga#486]
### Overview of the problem

**Oruga** version: 0.5.10
**Vuejs** version: 3.2.x
**OS/Browser**: 3.2.45

### Description

When the users add checkable props on the o-table and check one of the rows, the is-checked class is missing.
You can check the documentation which tells you that if you click a checkbox in a the table row, the is-checked class will be added.

### Steps to reproduce

1. Create a page that consists of o-table.
2. Add the props especially add checkable props.
3. Open the inspect element and check the row class.
4. Try to check one of the rows.
![image](https://user-images.githubusercontent.com/13668864/218069191-0f2bb5ac-0911-4cd1-9a11-a57d7210469d.png)

### Expected behavior
The is-checked class should be there, based on the documentation.
![image](https://user-images.githubusercontent.com/13668864/218069387-0efd484c-210f-4049-bde6-846aa3b1fa2a.png)

### Actual behavior
The is-checked class is missing.

**Comment by lgedgar** [comment]
I had this same problem FYI but was able to accomplish by specifying the "class prop" a la

```html
<o-table tr-checked-class="is-checked">
```
