### ISSUE TITLE
JS Agnostic 

### ISSUE THREAD

**Issue by ais-one** [oruga-ui/oruga#49]
### Description

It is good that Oruga is CSS Framework agnostic. How about also making it abit more JS Framework agnostic? Using VanillaJS, HTML5 Custom Elements

### Why Oruga need this feature

Would make it available to even wider audience...

**Comment by jtommy** [comment]
@ais-one it's no a priority at the moment, I have to add all missing components. 
Surely it might complete the agnostic concept introduced by Oruga but it's a really huge work and I don't know if it's possible offer the same features using web components.
