### ISSUE TITLE
Programmatically Modal not working inside or outside setup

### ISSUE THREAD

**Issue by darkylmnx** [oruga-ui/oruga#492]
### Overview of the problem

**Oruga next** version: [0.5.10]
**Vuejs** version: [3.2.45]
**OS/Browser**: Chrome 108.0.5359.126

### Description

The programmatic modal is not working, and throwing an error:

> Cannot read properties of undefined (reading 'open')

I called it outside a component, and also inside (in setup), neither work.

### Steps to reproduce

Here's my code which is pretty simple.
**utils.js**
```js
import { useProgrammatic } from '@oruga-ui/oruga-next';
import BaseDialog from '@components/BaseDialog.vue';

export const alert = (props) => {
  const { oruga } = useProgrammatic();

  return oruga.modal.open({
    component: BaseDialog,
    props: {
      type: 'alert',
      ...props,
    },
    trapFocus: true,
  });
};
```

**App.vue**
```vue
<script setup>
import { alert } from './utils';

alert({
  title: ' ... ',
  text: ' ... ',
});
</script>
```

### Expected behavior

I expected it to work and show the modal with my custom component.

### Actual behavior
Error:
> Cannot read properties of undefined (reading 'open')

It seems `const { oruga } = useProgrammatic();` returns an empty object.

**Comment by jtommy** [comment]
@darkylmnx are you importing Oruga?

**Comment by darkylmnx** [comment]
@jtommy in my main.js I have this:
```js
import {
  Config,
  OButton,
  // ... other comps
} from '@oruga-ui/oruga-next';
import { bulmaConfig } from '@oruga-ui/theme-bulma';

const app = createApp( ... );
const customConfig = {
  ...bulmaConfig,
  iconPack: 'fas',
};

app.use(Config, customConfig)
    .component('OButton', OButton)
   .component( /* other comps */ );
```

Am I missing something ?

**Comment by jtommy** [comment]
And is there modal component? Maybe there is a bug without using full bundle

**Comment by darkylmnx** [comment]
Yes the modal comonent was loaded as well.
I tried loading the full bundle to see if it changes  something, and that seems to be the issue indeed.

Other weird issue, the modal content is always behind the modal backdrop, even in the docs actually.

**Comment by Pablolgn** [comment]
I have the same error, have you been able to fix it?

**Comment by Pablolgn** [comment]
I had similar use but i use usePrgramatic on a library, and i use full bundle.

**Comment by jtommy** [comment]
@darkylmnx @Pablolgn you have to import `Modal` and use it by `app.use(Modal)`. 

Backdrop or similar issue is a theme issue
