### ISSUE TITLE
Expose Pagination Size in o-table props

### ISSUE THREAD

**Issue by robertmarney** [oruga-ui/oruga#494]
User cannot set the pagination size via the table props.

**Comment by jtommy** [comment]
There is `perPage` prop

**Comment by robertmarney** [comment]
Hey @jtommy  - Apologies, I should have been more clear. 

In Buefy you exposed paginationSize which controlled the size of the buttons / height of the pagination buttons:

![image](https://user-images.githubusercontent.com/48888686/221598056-2de2cec6-b1c9-416c-8977-c9c401783e82.png)

 From what I gather, the table element does not this prop in Oruga:

![image](https://user-images.githubusercontent.com/48888686/221597848-232e0d13-9208-4a6d-9684-dd3b60f2dfb0.png)
