### ISSUE TITLE
Homepage Lightweight icon not showing

### ISSUE THREAD

**Issue by mlmoravek** [oruga-ui/oruga#495]
On the current front site of the homepage the icon on the card _Lightweight_ is not showing.

**Comment by jtommy** [comment]
It looks ok

<img width="361" alt="image" src="https://user-images.githubusercontent.com/8029488/222973717-3bb5df7b-f41e-4c90-bfea-b99d876de8cf.png">

**Comment by mlmoravek** [comment]
![image](https://user-images.githubusercontent.com/25961416/222975860-f6291cc8-1f81-4ef2-985c-dde7a799ce10.png)

Using Chrome browser
