### ISSUE TITLE
search in a table

### ISSUE THREAD

**Issue by danimog** [oruga-ui/oruga#499]
### Overview of the problem

**Oruga** version: 0.5.10
**Vuejs** version: 3
**OS/Browser**: Brave/Firefox

### Description

Order and search functions doesn't work properly in a column retrieved via sequelize in a CRUD app.
This column (that don't work correctly) is name composed.
I have a data in a table with this some fields: 
....
ID_Assegnato (an ID in the main table)
...
TB_Assegnati.Nominativo (linked by ID_Assegnato from other table)

the component table in oruga show correctly the values of TB_Assegnati.Nominativo but if I try to make searchable this col it doesn't work. 

### Expected behavior
Also column TB_Assegnati.Nominativo is searchable or order by

**Comment by mlmoravek** [comment]
@danimog Do you still have problems with this? Have you tried with Oruga 0.8.x? If so, can you provide more information to help us reproduce this bug?

**Comment by danimog** [comment]
Hi, I'll try ASAP. thanks!
