### ISSUE TITLE
Oruga UI for Vue Next: Deprecated Slot syntax

### ISSUE THREAD

**Issue by chukwumaokere** [oruga-ui/oruga#50]
### Overview of the problem

**Oruga** version: [0.2.2]
**Vuejs** version: [3.0.0]
**OS/Browser**: Brave/Chromium

### Description
When using the template from here: https://oruga.io/components/Steps.html#examples 
We get an error about v-slot and slot-scope being deprecated. When you remove the problematic code, or try to use new syntax, the icons on the buttons do not render. Not sure if this 

### Steps to reproduce

1. Use this package on any Vue 3.0.0 
2. Create a new view
3. Use the example code as a template.
### Actual behavior
![image](https://user-images.githubusercontent.com/16673873/96535540-a84ceb00-1257-11eb-8ec8-7441785760eb.png)

Problematic code: 
```vue
<template v-if="customNavigation" slot="navigation" slot-scope="{previous, next}">
        <o-button outlined variant="danger" icon-pack="fas" icon-left="backward" :disabled="previous.disabled" @click.prevent="previous.action">
          Previous
        </o-button>
        <o-button outlined variant="success" icon-pack="fas" icon-right="forward" :disabled="next.disabled" @click.prevent="next.action">
          Next
        </o-button>
      </template>
```

I reckon it should be rewritten as
```vue
<template v-if="customNavigation" v-slot:navigation #="{previous, next}">
        <o-button outlined variant="danger" icon-pack="fas" icon-left="backward" :disabled="previous.disabled" @click.prevent="previous.action">
          Previous
        </o-button>
        <o-button outlined variant="success" icon-pack="fas" icon-right="forward" :disabled="next.disabled" @click.prevent="next.action">
          Next
        </o-button>
      </template>
```
But I'm not sure that works for this.

Edit: Actually, it looks like the icons are a part of some library of icons "mdi" that are just not rendered properly. 
![image](https://user-images.githubusercontent.com/16673873/96535920-8738ca00-1258-11eb-91c0-14cc3cb9470b.png)

What library is this "mdi"? Material Design Icons? If so you sould probably add in the installation steps to include the MDI icons using CDN or importing them.
Edit 2: 
Icons work after linking to material design CDN 
![image](https://user-images.githubusercontent.com/16673873/96536092-e8609d80-1258-11eb-9f72-e072276cc1d3.png)

**Comment by jtommy** [comment]
The docs is running on Vue 2.x and same thing for example, but of course you can change it using Vue 3
