### ISSUE TITLE
Inputitems with allowNew=true and autocomplete selection via keyboard

### ISSUE THREAD

**Issue by ThomasTr** [oruga-ui/oruga#501]
Hey oruga team, having trouble implementing Inputitems:

### Overview of the problem

**Oruga** version: 0.5.10
**Vuejs** version: 3.2.45
**OS/Browser**: 
MacOS Ventura 13.2.1
Chrome 111.0.5563.64

### Description

When entering tags In Inputitems with allowNew=true and selecting from autocomplete via keyboard, the entered chars to search in autocomplete and the selected tags are added.

### Steps to reproduce

1. Navigate to Inputitems doc page: https://oruga.io/components/Inputitems.html
2. Switch "Allow New Items" on
3. Enter "T"
4. Move with arrow down to item "Tina"
5. Press Return

### Expected behavior

Only the tag "Tina" should be added and the characters used to search in autocomplete should be discarded.

### Actual behavior

The tags "T" and "Tina" are added.

Switch allowNew off is no option as new tags must be accepted.
When autocomplete result selected via mouse, the characters used to search in autocomplete are already discarded.

**Comment by emrysr** [comment]
@ThomasTr  - did you find a solution to this problem?  just came across the same issue while testing

**Comment by Francis-Carvalho** [comment]
Did you find a solution to this bug? I have this same problem, but this bug only appears to me when I activate Dark Theme (Dark mode in my project is activated by class, not by "media query mode")

**Comment by Francis-Carvalho** [comment]
Apparently, this is the solution for this bug: https://github.com/capt-nemo429/nautilus-wallet/commit/a14f1ba950c7cdd2e8508ea9a7f4adc0a132f3ce
