### ISSUE TITLE
Key Modifiers are not supported by OTable @click directive

### ISSUE THREAD

**Issue by svienot** [oruga-ui/oruga#510]
### Overview of the problem

**Oruga** version: [0.5.10]
**Vuejs** version: [3.2.47]
**OS/Browser**: MacOS / Chrome

### Description

OTable `@click` directive does not recognize the VueJS key modifiers such as `.meta`, `.ctrl`, `.exact`, etc....

A use case here is to determine whether the user did a simple click or a Cmd-click (or Ctrl-click) on a table row, in order to navigate to a detail view in the same tab or in a new tab.

### Steps to reproduce

```
  <o-table
      :data="rows"
      @click.exact="handleClick"
      @click.meta.exact="handleClickMeta"   />

 const handleClick = (row) => alert('click')
 const handleClickMeta = (row) => alert('click.meta')

```
### Expected behavior

- plain click should result in `handleClick` being called
- Cmd-click should result in `handleClickMeta` being called
- Alt-click should produce no effect

### Actual behavior

- plain click as well as click with any modifier all result in `handleClick` being called

**Comment by jtommy** [comment]
I don't know your need but you can use cell-click event https://github.com/oruga-ui/oruga/blob/26e90afa773b751fe7d229c45dc6f9923abe641e/packages/oruga-next/src/components/table/Table.vue#LL224C34-L224C34

**Comment by mshakeg** [comment]
Hey @jtommy

The use case requires each item/record in a table to behave like an HTML anchor element so that users can for example open an item in a new tab. Does you recommendation enable this?

**Comment by jtommy** [comment]
It should work without any problems, did you try it?

**Comment by mshakeg** [comment]
@jtommy no, I'm more the end user, the developer is @svienot , so he'd be right person to ask.

**Comment by svienot** [comment]
@jtommy:  I confirm I am now able to use  `@cell-click="handleClick" `
which allows me to get the event in handleClick()
and then to test whether (e.g.) event.metaKey is true.
 
Thanks for the tip !
