### ISSUE TITLE
Font awesome styles

### ISSUE THREAD

**Issue by idank** [oruga-ui/oruga#511]
Does the icon component allow using a different style than the one the app has been configured with? Say I have

```
app.use(Oruga, {
  iconPack: "fas",
  iconComponent: "vue-fontawesome",
  ...bulmaConfig,
});
```

How would I use an icon from `@fortawesome/free-regular-svg-icons`?

**Comment by jtommy** [comment]
Sure, you can config it as icon pack `far` and use it in `o-icon` but keep attention to default icons, maybe `far` set doesn't cover all. Anyway you can ovveride them!

**Comment by idank** [comment]
How would that look?

I have:

```
// main.ts
import { library } from "@fortawesome/fontawesome-svg-core";
import { faCheckCircle } from "@fortawesome/free-regular-svg-icons";
library.add(faCheckCircle);

app.use(Oruga, {
  iconPack: "fas",
  iconComponent: "vue-fontawesome",
  ...bulmaConfig,
});

// Comp.vue
<o-icon icon="check-circle" pack="far" />
```

But it's complaining that it can't find it: `Could not find one or more icon(s) {prefix: 'far', iconName: 'check-circle'}`.
