### ISSUE TITLE
Datepicker placeholder doesn't show up on mobile when input type is 'datetime-local'

### ISSUE THREAD

**Issue by re2005** [oruga-ui/oruga#515]
### Overview of the problem

**Oruga** version: [0.5.10]
**Vuejs** version: [3.2.47]
**OS/Browser**: Mobile

### Description

When using the datepicker on mobile, the `input` field has type `datetime-local` That specific type doesn't show the placeholder.

A suggestion fix would set it to type `text` and when user focus on it changes the type back to `datetime-local` with will be much better of course for the mobile experience

### Steps to reproduce

Use the component `<o-datetimepicker placeholder="Select date"/>` and check on mobile 

### Expected behavior

Placeholder to be shown

### Actual behavior

Not shown.

**Comment by jtommy** [comment]
It looks like a good trick, can you make a PR?
