### ISSUE TITLE
Using the Notification compontent programmatically when importing and registering it manually

### ISSUE THREAD

**Issue by End-S** [oruga-ui/oruga#518]
I'm struggling with an issue:
I'm importing `ONotification` in `main.ts` and registering is as a component, like so:

```TypeScript
import { ONotification } from "@oruga-ui/oruga-next";

const app = createApp(App);
app.component("ONotification", ONotification);
```

Inside a Pinia store I am using the notification component programmatically:

```TypeScript
import { useProgrammatic } from "@oruga-ui/oruga-next";

const { oruga } = useProgrammatic();
oruga.notification.open({
  type: "warning",
  variant: "warning",
  duration: 5000,
  message,
  position: "bottom",
  queue: true,
  closable: true,
});
``` 

However this is giving me the error: `TypeError: oruga.notification is undefined`. For some reason `oruga` in this case is just an empty object. 

I don't get this issue if I import the entire `Oruga` library in `main.ts` like this: `import Oruga from "@oruga-ui/oruga-next";` but then I miss out on the tree-shaking.

I don't think this is a bug, hence not raising it as one. I would much appreciate some pointers as to where I'm going wrong here.
Thank you.

**Comment by jtommy** [comment]
You have to import `Notification` that is a Vue plugin and use it using `app.use`.
It will add programmatic component too
