### ISSUE TITLE
o-steps goes mobile view only on resize, not on load

### ISSUE THREAD

**Issue by carlosmojopicon** [oruga-ui/oruga#529]
### Overview of the problem

**Oruga** version: 0.5.9
**Vuejs** version: 3.2.47
**OS/Browser**: Linux/Brave

### Description

o-steps component doesn't show mobile view on page load. It triggers o-steps--mobile class only when manually resizing window.

### Steps to reproduce

1. Set up a o-steps component with mobileBreakpoint prop set to "720px"
2. Load page in a mobile device or a desktop window less than 720px width

### Expected behavior

o-steps--mobile class should be present in o-steps wrapper 

`<div class="o-steps__wrapper o-steps--mobile"></div>`

### Actual behavior

o-steps--mobile class is not present until you manually resize window

`<div class="o-steps__wrapper"></div>`

**Comment by mlmoravek** [comment]
This issue appears to be fixed. Feel free to reopen if there are still problems.
