### ISSUE TITLE
monthRowClass is documented but never used

### ISSUE THREAD

**Issue by IlyaSemenov** [oruga-ui/oruga#530]
### Overview of the problem

**Oruga** version: 0.6.0 / also latest develop (a33ee8ec11b69df218c17f388b4202947d473164)

### Description

`monthRowClass` is documented but [apparently never used](https://github.com/search?q=repo%3Aoruga-ui%2Foruga%20monthRowClass&type=code), unless I'm missing something.

### Expected behavior

It should be removed from the documentation, or implemented, or TODO added.

### Actual behavior

https://github.com/oruga-ui/oruga/blob/f01f5917d58646b96b2d6268931357b1727b992d/packages/docs/components/Datepicker.md?plain=1#L764-L765

---

**EDIT**: Same applies to `monthCellInvisibleClass`.

**Comment by mlmoravek** [comment]
Thanks i will remove them from the docs!
