### ISSUE TITLE
Vue 3 Composition API Notifcation - Utility File

### ISSUE THREAD

**Issue by deotte** [oruga-ui/oruga#535]
### Overview of the problem

**Oruga** version: "^0.5.10"
**Vuejs** version: "^3.2.45"
**OS/Browser**: Chrome

### Description

I'm using a Vue 3 app with Vite, and the composition API. I'm able to do `oruga.notifcation.open()` inside of my `<script setup></script>` components, but not in utility files:

### Steps to reproduce

New codebase with any component. Using the Composition API. Create a utility class for oruga notifcations, and try to use it in a component:

```ts
// Toast.ts
import { useProgrammatic } from '@oruga-ui/oruga-next';

export function orugaToast(message: string, closable: boolean, variant?: string): void {
	const { oruga } = useProgrammatic;

	oruga.notification.open({
		message: message,
		closable: closable,
		variant: variant === undefined ? 'success' : variant,
	});
}
```

```ts
// Component.ts
import { orugaToast } from '@/utils/toast';

onMounted(() => {
   orugaToast('Hello', true);
});
```

### Expected behavior

It should be able to open a notification like normal.

### Actual behavior

`oruga.notification` isn't defined

![Screenshot of error](https://github.com/oruga-ui/oruga/assets/31936704/9de98375-a0ec-48e5-9459-0a0cf1cf5d9e)

**Comment by deotte** [comment]
Using https://github.com/oruga-ui/oruga/issues/256 for reference

**Comment by jtommy** [comment]
It's a function `useProgrammatic()`
