### ISSUE TITLE
How to sponsorship Oruga development?

### ISSUE THREAD

**Issue by yangwao** [oruga-ui/oruga#539]
### Description

As https://kodadot.xyz is migrating from Buefy to Oruga, I would like happy to sponsor from own pocket towards Oruga development!  
- https://github.com/kodadot/nft-gallery/issues/4640

### Why Oruga need this feature

I bet others would sponsor Oruga development and keep going this awesome work!

**Comment by jtommy** [comment]
You might send us a some KODA gadgets, the t-shirt is really nice 😉

**Comment by yangwao** [comment]
> You might send us a some KODA gadgets, the t-shirt is really nice

go to https://shop.kodadot.xyz and use coupon "bestcssframeworkisoruga" for $100 off 😉

share with the team, it has 10 redemptions and expires end of August! :)
