### ISSUE TITLE
table sticky-header overlaid by other components

### ISSUE THREAD

**Issue by raymond-digi** [oruga-ui/oruga#545]
### Overview of the problem

**Oruga** version: [0.6.0]
**Vuejs** version: [3.3.2]
**OS/Browser**: Windows, Chrome, Edge

### Description

component table with sticky-header, headers is always on top with regular text but not with other components (like o-checkbox and o-input).

### Steps to reproduce
<pre>
&lt;o-table :data="items" focusable sticky-header>
    &lt;o-table-column label="Active" #default="v">      
        &lt;o-checkbox v-model="v.row.Active" disabled />
    &lt;/o-table-column>
    &lt;o-table-column label="ID" #default="v">
        {{ v.row.Id }}
    &lt;/o-table-column>
    &lt;o-table-column label="Code" #default="v">
        &lt;o-input v-model="v.row.Code">&lt;/o-input> 
    &lt;/o-table-column>
&lt;/o-table>"
</pre>
### Expected behavior

headers should be always on top

### Actual behavior

components on top of headers

![oo-1](https://github.com/oruga-ui/oruga/assets/59209978/3df504f8-20f1-49dc-8725-f7c5c5fee720)

**Comment by mlmoravek** [comment]
Should be fixed by the themes.
