### ISSUE TITLE
Add paginaton li class

### ISSUE THREAD

**Issue by mlmoravek** [oruga-ui/oruga#546]
### Description
Currently we can't configure a class for the li element of the pagination component. 

Add something like `itemClass` attribute to the pagination component for adding configured classed to the li elements.

Like:
```<li v-for="page in pagesInRange" :key="page.number" :class="itemClass"> ```

But also for all other li elements in the pagination component.

### Why Oruga need this feature
Enhance the pagination component.

**Comment by jtommy** [comment]
@mlmoravek you might add, for example calling it "listItemClass"

**Comment by mlmoravek** [comment]
@jtommy I opened an PR. Let me know if i missed something.
