### ISSUE TITLE
o-table backend sort event not firing

### ISSUE THREAD

**Issue by ais-one** [oruga-ui/oruga#55]
### Overview of the problem

**Oruga** version: "@oruga-ui/oruga-next": "^0.2.2",
**Vuejs** version: 3.0.1
**OS/Browser**: windows

### Description

The sort event cannot be captured

### Steps to reproduce

```
<o-table
      :mobileCards="false"

      :data="data"

      paginated
      backend-pagination
      :perPage="7"
      :total="total"

      backend-sorting
      v-model:selected="selected"
      v-model:currentPage="currentPage"
      :paginationSimple="false"
      :paginationPosition="'bottom'"
      scrollable
      stickyHeader

      @sort="onSort"
      @select="selectRow"
      @page-change="pageChange"
>
```

### Expected behavior

The arrow icon on the column being sorted changes

and a console log message from function onSort() listening to @sort is seen when then sort order changes

this shows sort event has been fired.

### Actual behavior

I can see the arrow icon change but no console log message

For Vue2 it seems to be working properly

**Comment by ais-one** [comment]
I found something in table.js

in the checkSort function, newColumns, it is always 0

Below is output of

1. console.log(this.newColumns)

Proxy {}
[[Handler]]: Object
[[Target]]: Array(6)
[[IsRevoked]]: false

2. console.log(this.newColumns.length)

0

**Comment by jtommy** [comment]
Oh ok, I'll investigate about it

**Comment by ais-one** [comment]
the values of this.newColumns are not present during checkSort, but are populated later...

**Comment by ais-one** [comment]
I think it only works if you pass in columns as a property... e.g. <o-table :columns="columns">
