### ISSUE TITLE
checkbox-type in o-table

### ISSUE THREAD

**Issue by contabilidadonline23** [oruga-ui/oruga#554]
Hi,

I see that Buefy has the "checkbox-type" prop to set the color of the checkbox in a table. However, I see that in Oruga this property is not documented and doesn't work.

Is it possible to use this property in Oruga?

For example:

<o-table :data="data" checkable visible="false" checkbox-position="right" **checkbox-type="is-warning"**>

I am usign:

"@oruga-ui/oruga-next": "^0.6.0"
"@oruga-ui/theme-bulma": "^0.2.10"
"Vuejs": "^3.3.2"

Regards.

**Comment by mlmoravek** [comment]
Oruga does not currently support this, but it would be a nice improvement.
