### ISSUE TITLE
o-upload component does not emit an event in specific conditions

### ISSUE THREAD

**Issue by 100Daisy** [oruga-ui/oruga#558]
### Overview of the problem

**Oruga** version: 0.6.0
**Vuejs** version: 3.3.4
**OS/Browser**: Chrome

### Description

Oruga UI dropzone component does not emit an event when recently pushed file is uploaded again, there could be a scenario when user uploads a file, removes it and then uploads again. 

### Steps to reproduce

1 .Upload new file to drag and drop component
2, save it in parent component
3. delete from parent component
4. upload file again

### Expected behavior
dropzone should emit an @update:modelValue event

### Actual behavior
dropzone does not emit @update:modelValue

**Comment by jtommy** [comment]
Are you pushing the same file?
