### ISSUE TITLE
Support for unplugin-icons

### ISSUE THREAD

**Issue by amir20** [oruga-ui/oruga#559]
### Description

My project uses https://github.com/antfu/unplugin-icons which uses something like ` <mdi-alarm-off />` which is translated to SVG. When I started using Oruga, I didn't need any icons. But now I have tables and noticing missing icons. I am not sure how to configure or overwrite this behavior. 

Is there an easy way to do this? 

### Why Oruga need this feature

Not everybody uses css packs to do icons.

**Comment by jtommy** [comment]
You can use the pack as you prefer and to use it you have to write your icon component wrappers. 
There is an example in the docs!

**Comment by amir20** [comment]
Are you referring to "Custom icon component"?

```
 import Oruga from "@oruga-ui/oruga";
    app.use(Oruga, {
        iconComponent: "vue-fontawesome",
        iconPack: "fas"
    })
```

Or something else? 

If I got the documentation for right, that calls something like ` <font-awesome-icon icon="fa-solid fa-user-secret" />`. How do I provide my own function?

**Comment by amir20** [comment]
Got it. Thanks. Will see if I can get that to work.

**Comment by amir20** [comment]
It works now. Thanks. Here is what I did for anybody else interested. 

// OrugaIcon.vue 
```
<template>
  <div>
    <mdi:arrow-up v-if="icon[1] == 'arrow-up'" />
  </div>
</template>

<script lang="ts" setup>
const { icon } = defineProps<{ icon: string[] }>();
</script>

<style scoped></style>
```

And 

```
import { bulmaConfig } from "@oruga-ui/theme-bulma";
import OrugaIcon from "@/components/OrugaIcon.vue";
export const install = (app: App) => {
  app
    .component("oruga-icon", OrugaIcon)
    .use(Config, { ...bulmaConfig, iconComponent: "oruga-icon", iconPack: "" });
};
```
