### ISSUE TITLE
Feature: set o-input invalid based on validationMessage if useHtml5Validation=false

### ISSUE THREAD

**Issue by bzd2000** [oruga-ui/oruga#56]
### Description

set o-input invalid based on validationMessage if useHtml5Validation=false
If validationMessage is set (useHtml5Validation=false), then the input field will be set invalid (variant = danger and validationMessage will be shown under the input field

### Why Oruga need this feature

In order to set the o-input invalid when working with external validation plugin like vee-validate

```
<Field name="firstName" v-slot="{field, meta, errorMessage}" rules="required">
     <o-input :useHtml5Validation="false" v-bind="field" :modelValue="meta.initialValue" :validationMessage="errorMessage"> 
     </o-input>
</Field>
```

**Comment by jtommy** [comment]
The approach using an external validation is different.. take a look at https://codesandbox.io/embed/vee-validate-oruga-itp29?codemirror=1
