### ISSUE TITLE
Adding a button to each row?

### ISSUE THREAD

**Issue by calicoder77** [oruga-ui/oruga#560]
Good day folks, I'll start by saying great work on the project so far. Wondering if anyone has found a way to add a button for every row added to a table? I'm reading the docs for o-table and don't see an example of how to do this or if it is even possible?

Here's my code so far:

```
const tableData = [{id: '1', userName: 'Team-Eagle'}, {id: '2', userName: 'Team-DownUnder'}]
const tableColumns = ([ {field: 'id', label: 'ID'}, {field: 'userName', label: 'User Name'}])

<o-table :data='tableData'>
    <o-table-column v-for='column in tableColumns v-bind='column' :key='column' #default='{row}'> {{ row[column.field] }}</o-table-column>
</o-table>
```

Appreciate any tips / help. All the best!!!

**Comment by jtommy** [comment]
Just simply using multiple table-colunn instead of a loop, you can add s button in the column that you prefer
