### ISSUE TITLE
Can we set default value for o-select?

### ISSUE THREAD

**Issue by calicoder77** [oruga-ui/oruga#564]
Good day, I see that the pure `HTML Select` tag has an option for selected, that sets that option value as the default. Does `o-select` have this prop? How would I make the empty value default one if none are selected?

```
<script>
</script>

<template>
  <section>
    <o-field label="Pick one">
      <o-select placeholder="Select a player">
        <option value="empty"></option>
        <option value="p01">Player 01</option>
        <option value="p02">Player 02</option>
        <option value="p02">Player 03</option>
      </o-select>
    </o-field>
  </section>
</template>
```

Thanks again and keep up the amazing work on the library!

**Comment by blm768** [comment]
Typically, you'd just make your desired default value be the initial `v-model` binding:

```vue
<script setup>
  const value = ref('');
</script>

<template>
  <section>
    <o-field label="Pick one">
      <o-select placeholder="Select a player" v-model="value">
        <option value="empty"></option>
        <option value="p01">Player 01</option>
        <option value="p02">Player 02</option>
        <option value="p02">Player 03</option>
      </o-select>
    </o-field>
  </section>
</template>
```

**Comment by calicoder77** [comment]
> Typically, you'd just make your desired default value be the initial `v-model` binding:
> 
> ```
> <script setup>
>   const value = ref('empty');
> </script>
> 
> <template>
>   <section>
>     <o-field label="Pick one">
>       <o-select placeholder="Select a player" v-model="value">
>         <option value="empty"></option>
>         <option value="p01">Player 01</option>
>         <option value="p02">Player 02</option>
>         <option value="p02">Player 03</option>
>       </o-select>
>     </o-field>
>   </section>
> </template>
> ```

Perfect, that works. Thanks so much for the tip.
