### ISSUE TITLE
Responsive Carousel

### ISSUE THREAD

**Issue by ottz0** [oruga-ui/oruga#565]
### Description
There is only 1 prop with `<o-carousel :items-to-show="3">`

### Why Oruga need this feature
I need to only show 1 on a mobile device, 2 on a tablet and 3 on a desktop so there are no responsive settings

**Comment by mlmoravek** [comment]
You could create your own computed property based on the width of the screen and calculate the `items-to-show` property based on the width.

Could this be a solution for you?
