### ISSUE TITLE
Oruga Modal seems to not be destroyed after active is updated to false

### ISSUE THREAD

**Issue by Diogo-Coding** [oruga-ui/oruga#568]
### Overview of the problem

**Oruga** version: [0.6.0]
**Vuejs** version: [3.2.13]
**OS/Browser**: Windows/Chrome

### Description

Oruga component doesnt get destroyed after changing active value to false and component goes display: none

```
  <o-modal 
    v-model:active="toggleModalActive" 
    scroll="clip"
    width="40%"
  >
    <div class="modalContent">
      <MyComponent
      />
      <o-button @click="closeModal()">Close</o-button>
    </div>
  </o-modal>
```
  
  closeModal() function change value of toggleModalActive to false

### Expected behavior

Component to get destroyed

**Comment by bios64** [comment]
Can confirm this is happening to me too after an "npm update". The modal should close but, in a blink opens again.
Calling oruga.modal.closeAll() closes it but can never open again.
