### ISSUE TITLE
Oruga-ui 0.6.0 does not work in IE11

### ISSUE THREAD

**Issue by vivekdsilva** [oruga-ui/oruga#569]
### Overview of the problem

**Oruga** version: 0.6.0
**Vuejs** version: 2.7.14
**OS/Browser**: IE11

### Description

We are in the process of moving or project from Buefy to Oruga. Although your website states support for IE11, we get the error "SCRIPT1028: Expected identifier, string or number" when we load our code in IE. It seems to work fine on Edge, FF and Chrome

Opening the below Oruga website in IE11 throws multiple errors:
https://vue2.oruga.io/components/Button.html

### Steps to reproduce

1. Go to https://vue2.oruga.io/components/Button.html in IE 11
2. Even a simple `<o-button root-class="button protip__button" @click="openAction()">{{ $t('Open Action') }}</o-button>`

### Expected behavior

Example buttons should be rendered.

### Actual behavior

Instead of the buttons, we see multiple error in the console

**Comment by jtommy** [comment]
@vivekdsilva do you get it in your project too?

**Comment by vivekdsilva** [comment]
Yes, we see the same issue in our project too.On Sep 20, 2023 1:12 AM, Walter Tommasi ***@***.***> wrote:
@vivekdsilva do you get it in your project too?

**Comment by mlmoravek** [comment]
@jtommy Maybe we should remove the IE 11 support label?

**Comment by astagi** [comment]
@vivekdsilva sorry, we removed IE11 support as you can see in README

<img width="474" alt="image" src="https://github.com/oruga-ui/oruga/assets/537363/d3a4508e-665c-4a1c-b27c-fb60eb1c8600">

@mlmoravek yes we should remove IE11 support labels if any, thanks! :)
