### ISSUE TITLE
Remove console.log statement

### ISSUE THREAD

**Issue by WillemJann** [oruga-ui/oruga#573]
There is a debug statement that appears in the console when using `oruga.modal.closeAll()`. It is located in the following file:

https://github.com/oruga-ui/oruga/blob/4915c4dbcb1a6c2cd39bc7660d41916b330bc0cd/packages/oruga-next/src/components/modal/index.ts#L48

This statement should probably be removed in release code?

**Comment by jtommy** [comment]
@WillemJann can you make a PR?

**Comment by WillemJann** [comment]
Of course, I've created a PR :)
