### ISSUE TITLE
Incorrect centered class added to a column with the centered prop

### ISSUE THREAD

**Issue by kevincote** [oruga-ui/oruga#58]
### Description

Table column props "centered" does not put the correct class on the column.

### Steps to reproduce

Set a table column with the props "centered".

### Expected behavior

The CSS class defined in the code in the file oruga/packages/oruga/src/scss/components/_table.scss for centered column is **o-table-td-center**. This class is the one that should be added to the cell.

### Actual behavior

The CSS class **o-table-td-centered** is added to the cell. Since it's not defined, the column is not centered.

**Comment by jtommy** [comment]
Ok thanks, you can create on with the same name or add a new one.
I'll fix it
