### ISSUE TITLE
paginationSize prop is duplicated in Table.vue

### ISSUE THREAD

**Issue by luistrcastro** [oruga-ui/oruga#583]
### Overview of the problem

**oruga-ui/oruga-next**: 0.6.0,
**Vuejs** version: 3.2.9
**OS/Browser**: Win 10, Browser; Brave

### Description

paginationSize prop is duplicated in Table.vue

### Expected behavior

paginationSize to be applied to pagination

### Actual behavior

paginationSize is not being applied to pagination

![image](https://github.com/oruga-ui/oruga/assets/64997284/bd0ed0b9-5092-466d-9921-a3d9939b8df8)

![image](https://github.com/oruga-ui/oruga/assets/64997284/885f4eb1-e56c-48d0-ba28-b6d8162e964e)

- Also, size prop is inexistent in TablePagination.vue

![image](https://github.com/oruga-ui/oruga/assets/64997284/d912b8a7-5494-4516-8b0b-e75edbc27715)

**Comment by mlmoravek** [comment]
@luistrcastro 
I don't know what version of the code you looked at, but on develop paginationSize is not duplicated.

In TablePagination all incomming not defined attributes are passed down to the Pagination component. In the Pagination component the `size` prop is defined.
