### ISSUE TITLE
o-sidebar in nuxt 3 throws error!

### ISSUE THREAD

**Issue by fahdaddi** [oruga-ui/oruga#589]
when using oruga with nuxt 3, o-input is working fine but o-sidebar throws the followinf error:

Cannot read properties of null (reading 'isCE')

### Overview of the problem

**Oruga** version: 6
**Vuejs** version: 3
**OS/Browser**: google chrome

**Comment by mlmoravek** [comment]
@fahdaddi Could you check again with verion 0.8.x?
