### ISSUE TITLE
Pagination buttons are empty

### ISSUE THREAD

**Issue by gpp8p** [oruga-ui/oruga#59]
### Overview of the problem
Using the supplied example code for tables, the pagination  next and previous buttons are empty.  They work but no icon is displayed
**Oruga** version: [X.X.X]
**Vuejs** version: [X.X.X]
**OS/Browser**:

**Comment by jtommy** [comment]
Are you importing fontawesome or MDI ?

**Comment by gpp8p** [comment]
Just did and it fixed the problem.  You are the best!!!

Thanks for replying so quickly.


-George Pipkin
