### ISSUE TITLE
New documentation site not working with older values stored in the local storage.

### ISSUE THREAD

**Issue by messenjer** [oruga-ui/oruga#592]
### Overview of the problem

**Oruga** version: [0.7.0]
**Vuejs** version: [3.3.4]
**OS/Browser**: Mac/Chrome

### Description

I would like to report a bug in the latest version of the documentation that affects users who have older values stored in their local storage. 

![Screenshot 2023-09-21 at 10 31 39](https://github.com/oruga-ui/oruga/assets/80677/7022814b-2c40-47d1-aa27-f18e66dcff32)

![Screenshot 2023-09-21 at 10 18 14](https://github.com/oruga-ui/oruga/assets/80677/8e0e3c68-06ed-4ae8-9a58-d45c0733687a)

### Steps to reproduce

Here are the steps to reproduce the issue:

1.     Open the browser console.
2.     Enter the following command in the console:

```
localStorage.setItem("oruga.io_theme", "bulmacss");
```

3.  Reload the documentation page.

Upon reloading the documentation, an error occurs as follows:

> Uncaught (in promise) SyntaxError: Unexpected token 'b', "bulmacss" is not valid JSON

It appears that the issue is related to how the documentation handles values in local storage, specifically when there is an older value stored.

### Expected behavior

No error

### Actual behavior

Javascript error

**Comment by zhaolinlau** [comment]
same problem here

![image](https://github.com/oruga-ui/oruga/assets/68846168/08ff62bd-98a7-4ad3-aa7d-51f46a902504)

**Comment by roiLeo** [comment]
Fix for now `localStorage.removeItem('oruga.io_theme')`

**Comment by mlmoravek** [comment]
Thanks for the report. Fix is on the way.
