### ISSUE TITLE
@oruga-ui/next Typescript support

### ISSUE THREAD

**Issue by herkulano** [oruga-ui/oruga#60]
### Description
Support Typescript in `oruga-next`

Get the following error message using `"@oruga-ui/oruga-next": "^0.2.2"`

`Could not find a declaration file for module '@oruga-ui/oruga-next'.`

**Comment by astagi** [comment]
Hi @herkulano an initial Typescript support using the [shorthand ambient module](https://www.typescriptlang.org/docs/handbook/modules.html#shorthand-ambient-modules) will be added in the next Oruga's version, for now add the following to your `shims-vue.d.ts` to fix your issue

```ts
declare module '@oruga-ui/oruga-next';
```

Let me know if it works!

**Comment by herkulano** [comment]
@astagi thank you! it solves the issue with the error, but as expected there's no code completion for the components. Any plans on fully supporting TypeScript?

**Comment by astagi** [comment]
I made a PR for the shorthand ambient module, so you won't have to include module declaration inside shims-vue.d.ts! Anyway yes, there are plans to fully support TypeScript in future
