### ISSUE TITLE
Bug: Datepicker Crashes Browser

### ISSUE THREAD

**Issue by dylanson25** [oruga-ui/oruga#624]
### Overview of the problem

```
"@oruga-ui/oruga-next": "^0.6.0",
"@oruga-ui/theme-bulma": "^0.2.11",
"vue": "^3.3.4",
```

### Description

There is a bug in my Datepicker component and the documentation page. When navigating within the datepicker component using the arrow up/down keys on the days of the week, it causes the browser to crash.

### Steps to reproduce

https://github.com/oruga-ui/oruga/assets/54459436/15cbb742-be0d-40a3-8505-5b5702f3b4ba

#### The same problem can be replicated in the official documentation.
- https://oruga.io/components/Datetimepicker.html

https://github.com/oruga-ui/oruga/assets/54459436/4df6cf32-8d3e-44e5-91ee-c1508160b2c4

#### Oficial page
<img width="951" alt="Captura de Pantalla 2023-10-13 a la(s) 12 29 02" src="https://github.com/oruga-ui/oruga/assets/54459436/245516a4-cd3e-4949-8539-ea664a52783a">

#### My local 
<img width="744" alt="Captura de Pantalla 2023-10-13 a la(s) 12 08 33" src="https://github.com/oruga-ui/oruga/assets/54459436/c367154f-f945-4fd3-85bf-6faca233b887">

**Comment by jtommy** [comment]
@mlmoravek you are working on refactoring, can you take a look?

**Comment by mlmoravek** [comment]
@dylanson25 Thanks for reporting this bug. 
The bug comes from an endless while loop, even after the refactoring.

https://github.com/oruga-ui/oruga/blob/860d08386c5932d01d5738cddebfb44a10194cf7/packages/oruga-next/src/components/datepicker/DatepickerTableRow.vue#L160C1-L172C2

I will fix it.
