### ISSUE TITLE
Inputitems autocomplete adding items broken

### ISSUE THREAD

**Issue by myrsky-mapita** [oruga-ui/oruga#653]
### Overview of the problem

**Oruga** version: 0.7.0
**Vuejs** version: 2.7.15
**OS/Browser**: I'm using Chrome (but not limited to)

### Description

Adding new tags is broken when using the autocomplete option on the Inputitems component.

* When using `openOnFocus` and selecting an item from the list, the tag is added as plain text in the input, but not as a tag (visually nor in array).
  * Expected: item is added as a tag in UI and array
* When typing and selecting an item from the list, the search text is added as a tag and the selected item is added as text in the input.
  * Expected: selected item text is added as a tag and input resets to empty
* After having selected an item from the list and you want to add another one, again the searched text is added as a tag and the _previously_ selected item appears as search text in the input.
  * Expected: selected item text is added as a tag and input resets to empty
* Type error appears when selecting an item `TypeError: t.match is not a function`

### Steps to reproduce

This can be reproduced in the example of Oruga's docs when following the steps above: https://vue2.oruga.io/components/Inputitems.html#autocomplete

This issue doesn't seem to exist in the vue3 version of Oruga when checking that example in the new docs, and I understand if this won't be fixed anymore since vue2 version is deprecated, but I thought I'd still report it. 

Screen recording taken from documentation example:

https://github.com/oruga-ui/oruga/assets/144100956/a9175bd8-0d60-4e04-a4d6-533b8963a0c3

**Comment by mlmoravek** [comment]
@myrsky-mapita Thank you for reporting this, but we will no longer be fixing vue2 related issues. We have deprecated the oruga for vue2 package and will remove the package at a later date.
