### ISSUE TITLE
Cannot pass html attribute to button

### ISSUE THREAD

**Issue by AuthorProxy** [oruga-ui/oruga#655]
### Overview of the problem
**Oruga** version: [0.6.0]
**Vuejs** version: [3.2.47]
**OS/Browser**:

### Description
Cannot pass custom attribute to the element, it just ignores it on final html - for example:
`<o-button form="my-form" type="submit">Submit</o-button>`

**Comment by jtommy** [comment]
You have to use `nativeType` prop, maybe we can change it in the next breaking
