### ISSUE TITLE
O-icon: switch icons on button click?

### ISSUE THREAD

**Issue by calicoder77** [oruga-ui/oruga#661]
Good afternoon, wondering if anyone can offer some tips or suggestions on how to accomplish this? I'm looking to have 3 icons and when their respecting buttons are pressed, the icon changes to another icon. Is this possible at all?

```
<div">
    <o-button>
        <o-icon pack="fas" icon="check" />
        <span>Button 1</span>
    </o-button>
    <o-button>
        <o-icon pack="fas" icon="check" />
        <span>Button 2</span>
    </o-button>
    <o-button>
        <o-icon pack="fas" icon="check" />
        <span>Button 3</span>
    </o-button>
</div>

```
Much appreciated, thank you.

**Comment by mlmoravek** [comment]
You may be able to achieve what you want by using css. 
The button will have the `:active` css state when pressed.
You need to define both icons in the template and hide and show whichever you want on the parent `button:active` state.
Hope this helpes.

**Comment by calicoder77** [comment]
> You may be able to achieve what you want by using css. The button will have the `:active` css state when pressed. You need to define both icons in the template and hide and show whichever you want on the parent `button:active` state. Hope this helpes.

Great idea, I'll give it a try. Thank you
