### ISSUE TITLE
O-table example for selection doesn't work for Vue3

### ISSUE THREAD

**Issue by calicoder77** [oruga-ui/oruga#664]
Good day, I've been try to implement the example shown of the o-table for selections and it's not working for me. Is this for Vue2 only or is it compatible with Vue3? When I click on a row, the whole table gets a greenish border.

```
<section>
    <o-button
        variant="danger"
        :disabled="!selected"
        icon-left="times"
        @click="selected = null">
        <span>Clear selected</span>
    </o-button>

    <p><b>Selection:</b> {{ selected }}</p>

    <o-table v-model:selected="selected" :data="data" focusable>
        <o-table-column
            v-for="(column, idx) in columns"
            :key="idx"
            v-slot="{ row }"
            v-bind="column">
            {{ row[column.field] }}
        </o-table-column>
    </o-table>
</section>
```

Appreciate any tips or ideas, thanks

**Comment by mlmoravek** [comment]
@calicoder77 Can you give a more detailed example? I can't reproduce your problem. The docs page works as expected.

The border is part of a theme. Which theme are you using?
