### ISSUE TITLE
Carousel is broken

### ISSUE THREAD

**Issue by zhaolinlau** [oruga-ui/oruga#683]
### Overview of the problem

**Oruga** version: [0.8.1]
**Vuejs** version: [3.3.8]
**OS/Browser**: Windows 11/Firefox

### Description

I'm using nuxt 3 + bulma themed oruga, and the carousel looks broken

### Steps to reproduce

1. implement carousel component
2. add .png files to public/img/banners/
3. add the exact path to the :src
4. final codes will be as below:
```vue
<script setup>
const banners = ref([
	{
		src: "1.png",
	},
	{
		src: "2.png",
	},
	{
		src: "3.png",
	},
]);
</script>

<template>
	<o-carousel :repeat="true" :autoplay="true" :indicatorMode="hover" :pauseHover="true" :iconSize="`medium`"
		:indicatorStyle="`boxes`">
		<o-carousel-item v-for="(banner, i) in  banners" :key="i">
			<figure class="image">
				<NuxtImg :src="`/img/banners/` + banner.src" />
			</figure>
		</o-carousel-item>
	</o-carousel>
</template>
```

### Expected behavior

https://uxhmac.vercel.app/

![image](https://github.com/oruga-ui/oruga/assets/68846168/df97f675-1f42-4699-add9-9109093bb449)

### Actual behavior

https://uxhmac-ocjke5jaa-zhaolinlau.vercel.app/

![image](https://github.com/oruga-ui/oruga/assets/68846168/154c0255-4fff-48b6-886e-7dce9038c57e)

**Comment by messenjer** [comment]
Hello, it's related to this issue : https://github.com/oruga-ui/theme-bulma/issues/92
