### ISSUE TITLE
How to build locally the oruga library ?

### ISSUE THREAD

**Issue by messenjer** [oruga-ui/oruga#685]
Hello, 

I 'ld like to build oruga library on my local, but I couldn't do it.

```
sh: vue-tsc: command not found
```

I don't know, if I use the correct package manager, ... or run the script in the correct folder.

### Overview of the problem

**Oruga** version: 0.8.1
**Vuejs** version: 3.3
**OS/Browser**: Mac Os X
** Node : 20.10.0
** Npm : 10.2.3

### Steps to reproduce

```sh
git clone git@github.com:oruga-ui/oruga.git 
npm install
npm run bootstrap

> root@0.8.0 bootstrap
> lerna bootstrap

lerna notice cli v6.4.1
lerna info Bootstrapping 2 packages
lerna info Symlinking packages and binaries
lerna success Bootstrapped 2 packages
```

```sh
npm run build:lib:oruga-next

> root@0.8.0 build:lib:oruga-next
> lerna run build:lib --parallel --scope @oruga-ui/oruga-next

lerna notice cli v6.4.1
lerna notice filter including "@oruga-ui/oruga-next"
lerna info filter [ '@oruga-ui/oruga-next' ]

> @oruga-ui/oruga-next:"build:lib"

> @oruga-ui/oruga-next@0.8.0 build:lib
> rimraf dist && npm run test:ts && npm run build:vue
> @oruga-ui/oruga-next@0.8.0 test:ts
> vue-tsc --noEmit --skipLibCheck
sh: vue-tsc: command not found

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  Lerna (powered by Nx)   Ran target build:lib for project @oruga-ui/oruga-next (513ms)

    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
```

### Expected behavior

I would like to build Oruga in local

**Comment by mlmoravek** [comment]
@messenjer 
Have you installed the dependencies from the root package as well as the oruga-next sub package ?

**Comment by messenjer** [comment]
Thanks, it works.

I thought we only had to run npm install at the root as there is Lerna in the project. Perhaps we should configure monorepo and use the concept of workspaces, I've never configured Lerna before.

There is information here: https://lerna.js.org/docs/getting-started

**Comment by mlmoravek** [comment]
Now that we have removed Oruga for vue2 from the repo, I would like to refactor the repository back to a monorepo. 

But this is not a high priority.
