### ISSUE TITLE
autocomplete in v-for

### ISSUE THREAD

**Issue by noebisoft** [oruga-ui/oruga#688]
### Overview of the problem

**Oruga** version: [0.8.1]
**Vuejs** version: [3.3.4]
**OS/Browser**: Chrome

### Description

If i have o-autocomplete in a v-for loop and lets say 3 are visible on page load, the fist time i trigger autosuggest in one of the three components, the suggest dropdown is visible under **all three** instead only the current one I am typing in.

If i select one option in the dropdown, the problem is solved until the next page reload. But in the DOM it seems that all three dropdowns are still refreshed, but only the one in which I am typing in is visible.

### Example

  <o-field grouped group-multiline>

      <o-field v-for="(usage,index) in $store.state.editedParameter.parameter.used_for" :key="'usage_'+parameterId+'_'+index">
        <o-autocomplete
            rounded
            v-model="$store.state.editedParameter.parameter.used_for[index]"
            size="small"
            :data="suggests"
            placeholder="Usage..."
            :confirmKeys="[]"
            v-on:keyup.enter="addUsage(index)"
            @input="getUsedForSuggest"
            @select="option => $store.state.editedParameter.parameter.used_for[index] = option"
            :id="'auto_complete_'+parameterId+'_'+index"
        >
          <template #empty>No results found</template>
        </o-autocomplete>

        <p class="control">
          <span class="button is-small fa fa-minus-circle" v-on:click="remove(index)" title="Remove from list"></span>
        </p>
      </o-field>

  </o-field>

**Comment by mlmoravek** [comment]
@noebisoft Could you make a fully reproducible example using JSFiddle or StackBlitz or something else?

**Comment by noebisoft** [comment]
Hello,

can you provide a template for Vue3 and Oruga in any of these environments?

StackBlitz, Codesandbox... i get it nowhere running.

Thanks

**Comment by mlmoravek** [comment]
@noebisoft I could get Oruga working in Codesandbox

https://codesandbox.io/p/devbox/oruga-m6hnct

**Comment by noebisoft** [comment]
Great. Thanks a lot. I hope this link works:

https://codesandbox.io/p/devbox/oruga-forked-43zs4n

Just put the cursor at the end in any of the 3 autocomplete inputs und remove characters.

BTW: the empty slot is not functional as well.

**Comment by mlmoravek** [comment]
@noebisoft Could you check if something similar happens when you have 3 dropdown components instead of autocomplete components? Because autocomplete now uses dropdown below (new in 0.8). So we can check if it is a dropdown issue or an autocomplete issue.

**Comment by noebisoft** [comment]
I added dropdowns to the codesandbox.
Unless i use the same active variable (see last two butttons), one dropwdown closes all other. The are not independent from the other.

But the autocompletes should be independent, what the are not. If you change one, the items in div.dropdown-content are changed for all autocompletes which have a value. If an autocomplete has no value, nothing happens.

I removed the initial value from the second autocomplete in the codesandbox example for demonstration.

**Comment by mlmoravek** [comment]
So I had some time to look at your example. 
I think I could solve your problem by using different :data values.

```
let suggests = ref([[],[],[]]);

function getUsedForSuggest(query, index) {
  suggests.value[index] = usedForList.filter((item) => {
    if (!item) return;
    return item.toString().toLowerCase().indexOf(query.toLowerCase()) > -1;
  });
}
```

```
  <o-field v-for="(usage, index) in [1, 2, 3]" :key="'usage_' + index">
      <o-autocomplete
        v-model="acVal[index]"
        :data="suggests[index]"
        @input="(v) => getUsedForSuggest(v, index)"
      >
      </o-autocomplete>
    </o-field>
```

@noebisoft  Does this fix your problem for you?

**Comment by noebisoft** [comment]
Yes it does. Thanks a lot for your support.

Happy new year.
