### ISSUE TITLE
Incorrect Volar types

### ISSUE THREAD

**Issue by 0ttik** [oruga-ui/oruga#703]
As a follow-up of #694.

After `npm install @oruga-ui/oruga-next` I've got the following source code in my node_modules:
<img width="1346" alt="image" src="https://github.com/oruga-ui/oruga/assets/2836734/d292b426-d142-45ed-b8fd-ac1609496e53">
<img width="1346" alt="image" src="https://github.com/oruga-ui/oruga/assets/2836734/1858a0cf-d1ff-4514-9c3b-849ca0d53958">

As a consequence, it does not work correctly and suggest faulty autofills. 

@mlmoravek, tagging you as the author of the initial implementation. Thank you.

**Comment by 0ttik** [comment]
Oh, you seem to have already fixed it, so this should be closed after https://github.com/oruga-ui/oruga/pull/702/files is released.

**Comment by mlmoravek** [comment]
Hey @0ttik, thanks for the engagement. Yes, I'm aware of this problem. Will be fixed in the next release :)
