### ISSUE TITLE
Tree-shaked Config is not working anymore

### ISSUE THREAD

**Issue by 121593** [oruga-ui/oruga#705]
### Overview of the problem

**Oruga** version: 0.8.2
**Vuejs** version: 3.3.13

### Description

Documentation states :

> If you use individual imports you can customize each compoment using the Config plugin.

And shows the following example :
```
import { OAutocomplete, OSidebar, Config } from '@oruga-ui/oruga-next';
[...]
```

It is working with version `0.7.0`, but fails in `0.8.2`

### Steps to reproduce

1. Use the documentation code with version 0.7.0 and see that it works
2. Upgrade to 0.8.2 and see the compilation (with Webpack if that matters) failing with the error above

### Expected behavior

Either that the code from the documentation work, or that the documentation show code that works.

### Actual behavior

Compilation fails with  `Module '"@oruga-ui/oruga-next"' has no exported member 'Config'`

**Comment by mlmoravek** [comment]
The progammatic interface changed a bit. 

Try this to access the config plugin while adding the whole oruga plugin: 
```
import { useOruga } from '@oruga-ui/oruga-next';
const config = useOruga().config;
```

However, if you want to set it up yourself, try: 
``` 
import { ConfigProgrammatic } from '@oruga-ui/oruga-next';
const options = {.....};
ConfigProgrammatic.setOptions(options);
```

Does this work for you?


Are there any misleading descriptions in the documentation? A clearer description is welcome :)

**Comment by 121593** [comment]
`ConfigProgrammatic` makes it works as expected ! Thanks for the guidance.

Yes the documentation would deserve an update. I'll submit a PR.
