### ISSUE TITLE
Autocomplete : `menuClass` class prop is gone

### ISSUE THREAD

**Issue by 121593** [oruga-ui/oruga#708]
### Description

Autocomplete component used to provide the `menuClass` class prop. It got removed in https://github.com/oruga-ui/oruga/pull/652 while adding the (nice) teleport feature.

This class prop was quite useful so I just wanted to make sure this change was required.

**Comment by mlmoravek** [comment]
@121593 Hey, the autocomplete component now uses the dropdown component internally.
