### ISSUE TITLE
Table: Page change event in table always sending value 1

### ISSUE THREAD

**Issue by Nemesis19** [oruga-ui/oruga#712]
oruga: 0.8.1 (I cannot upgrade to 0.8.2 due to many bugs already issued)
vue: 3.3

the page-change event in table always sends value 1 even if I'm clicking on 2-3-4 page or clicking on right-left arrows.

```
<o-table
			striped
			backend-pagination
			:paginated="paginated"
			:data="data"
			:total="page.total"
			:current-page="page.current"
			:per-page="page.perPage"
			:order="'left'"
			@page-change="onPageChange">
```

Please fix it asap. Thanks! 🙏

**Comment by mlmoravek** [comment]
@Nemesis19 I appreciate you opening bug issues :) 
The refactoring from the options api to the script setup composition api was quite a big think. I tried and tested as much as I could, but I had to touch almost every line of code in the project. I hope you excuse me for the unfounded bugs and I welcome you to open an issue if you find any!

**Comment by Nemesis19** [comment]
Thanks for your kind reply. Unfortunately the many bugs I opened are making me think to downgrade to 0.7.0 cause they are making unusable my projects where I'm actively using Oruga.

Thanks for you effort, I'm converting a private project from vue2 to vue3 and I know the burden this thing carry on.

**Comment by mlmoravek** [comment]
You are welcome to open pull requests for bugs you find. This helps us a lot and makes it more likely that the bug will be fixed as soon as possible. 
However, by opening an issue, I will try to help you with a workaround as much as possible.

**Comment by mlmoravek** [comment]
@Nemesis19 Could you provide a fully reproducible example on https://codesandbox.io/ or any other sharing platform?

**Comment by Nemesis19** [comment]
I'm using the same example as the doc

https://www.pastery.net/kxwbqk/

please be aware that the console log inside the onPageChange function reports a different page than the one clicked visually in the template.

- template click 2, p is 1
- template click 100, p is 5

**Comment by mlmoravek** [comment]
@Nemesis19 I found the bug for the `page-change` event. Emitting a computed value right after if get changed, it somehow emits the old value. I also see this behaviour with the new `defineModel` macro. It's quite counterintuitive.

Could you be a bit more clear where the docs are misleading and what we can do to solve this?

The `page-change` event handler don't has to be an arrow function, is a normal [Vue event](https://vuejs.org/guide/essentials/event-handling).

**Comment by mlmoravek** [comment]
@Nemesis19 I think this is solved now for sure :D Could you confirm this?

**Comment by Nemesis19** [comment]
I'm sorry but due to the critical bugs ongoing lately with tables and autocompletes I downgraded to 0.7.0 which was the last perfectly working version.
