### ISSUE TITLE
Using icons with `o-input` changed behaviour, looks broken now 

### ISSUE THREAD

**Issue by FlorianLoch** [oruga-ui/oruga#728]
### Overview of the problem

**Oruga** version: 0.8.2
**Vuejs** version: 3.3.7
**OS/Browser**:

### Description

Icons are not placed correctly. 

Please see the screenshot I have taken from the official documentation.

<img width="817" alt="image" src="https://github.com/oruga-ui/oruga/assets/5587805/3ce025f6-1820-40c4-85c3-6698be19e594">

### Steps to reproduce

Simply use `o-input` with `icon-right` attribute, like shown in the docs: https://oruga.io/components/Input.html#icons

### Expected behavior

Icon should be in the box, as it is with `^0.7.0`.

### Actual behavior

See picture above.

**Comment by mlmoravek** [comment]
FlorianLoch Which theme have you selected? The Bulma theme is not yet supported in the new version. See https://github.com/oruga-ui/theme-bulma/issues/92.

However, the oruga and bootstrap themes look good to me.

**Comment by FlorianLoch** [comment]
Yes, I am using the `bulma` theme. 

Sorry, my bad - I checked the issues here, but didn't think about checking the `theme-bulma` repo.

But good to know that is already known, so I guess I will just wait with bumping the version a little.
