### ISSUE TITLE
TagInput with defined maxitems throws error

### ISSUE THREAD

**Issue by myrsky-mapita** [oruga-ui/oruga#729]
### Overview of the problem

**Oruga** version: 0.8.2
**Vuejs** version: 3.3.11 (also in latest 3.4.7, but there are more problems there so I'm still using 3.3.11)
**OS/Browser**: Chrome

### Description

When using `TagInput` with `maxitems` defined, an error is thrown when max amount of items is reached:

```
Uncaught TypeError: Cannot read properties of null (reading 'getAttribute')
    at ReactiveEffect.fn (useInputHandler.ts:66:16)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at get value [as value] (reactivity.esm-bundler.js:1142:33)
    at checkHtml5Validity (useInputHandler.ts:138:22)
    at onBlur (useInputHandler.ts:102:28)
    at handleOnBlur (Taginput.vue:402:5)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:17)
    at emit (runtime-core.esm-bundler.js:672:5)
    at runtime-core.esm-bundler.js:7520:45
```
(There are also Vue warnings about `OAutocomplete` and `OInput`)

### Steps to reproduce

1. Create component with `<o-taginput :maxitems="2" v-model="myModel"/>` (can be any amount of maxitems), for example

```
<script>
export default {
    data() {
        return {
            valueModel: []
        }
    },
}
</script>

<template>
    <o-field>
        <o-taginput :maxitems="2" v-model="valueModel"/>
    </o-field>
</template>
```

3. Enter the max amount of items
4. Error appears

This can be reproduced on the documentation page https://oruga.io/components/Taginput.html

<img width="1410" alt="Screenshot 2024-01-09 at 15 17 29" src="https://github.com/oruga-ui/oruga/assets/144100956/290fafbe-d53e-4b43-a45b-39b0a443d1e6">

**Comment by mlmoravek** [comment]
Seems fixed by https://github.com/oruga-ui/oruga/pull/747/files

However, I am making the autocomplete component under the taginput only hide not unmount when maxitems is reached by https://github.com/oruga-ui/oruga/pull/754.
