### ISSUE TITLE
It looks like the documentation site isn't correctly building 

### ISSUE THREAD

**Issue by realimpat** [oruga-ui/oruga#745]
see screenshots:

![Screenshot 2024-01-25 at 1 19 08 PM](https://github.com/oruga-ui/oruga/assets/34801063/b4c79b4e-feac-4a5b-a7d1-76e71be87ba7)
![Screenshot 2024-01-25 at 1 19 47 PM](https://github.com/oruga-ui/oruga/assets/34801063/15acba91-b66c-428f-ac88-f9ebfa51ff2d)

Nothing is being blocked in my network tab and nothing is creating warnings or errors in the console. Chrome on macOS.

**Comment by mlmoravek** [comment]
@realimpat Which theme have you selected? It looks like you have selected the oruga base theme. Maybe you want to select the oruga full theme.
