### ISSUE TITLE
Possible mistake in docs

### ISSUE THREAD

**Issue by Nemesis19** [oruga-ui/oruga#751]
**Oruga** version: 0.8.2

The `duration` prop doesn't get listed in Notification props, but in Notification Notice Component.

However I'm using oruga notification as follows:
```
oruga.notification.open({
			...config
		});
```

by passing a config like che class that follows and that includes the duration. The prop works perfectly fine:

```
export class ConfigNotification {
	duration?: number;
	message?: string;
	position?: string;
	icon?: string;
	closable?: boolean;
	animation?: string;
	variant?: DialogType;

	constructor(message?: string) {
		this.duration = 3000; // 3 seconds
		this.message = message ?? 'Elemento salvato con successo';
		this.position = 'bottom';
		this.icon = 'toast-success';
		this.closable = true;
		this.animation = 'fadeInUp';
		this.variant = DialogType.SUCCESS;
	}
}
```

is the doc missing the prop?

**Comment by mlmoravek** [comment]
@Nemesis19 No, the docs are correct. The programmatic interface uses the `NotificationNotice` component, which is a wrapper around the normal `Notification` component. 
Only the programmatic NotificationNotice component has the auto-close feature where the `duration`prop is used. 

Does this helps?

**Comment by Nemesis19** [comment]
I understand now, the wrapper uses the notification prop to make everything work with the original notification object props. Thanks
