### ISSUE TITLE
Can please add defineExpose for table and autocomplete

### ISSUE THREAD

**Issue by okrymus** [oruga-ui/oruga#755]
I cannot access the components methods/ variables from a parent.

For table, sometimes the sorting arrow not get updated if the sort changed by parent
Can you add expose currentSortColumn and isAsc?

For autocomplete, sometimes i need to setSelected from parent. 
Can you also add expose setSelected method?

Thank you!

**Comment by mlmoravek** [comment]
Hey @okrymus, I will check which methods need to be exposed and which functionality can be triggered by props.

**Comment by okrymus** [comment]
@mlmoravek thank you!

**Comment by mlmoravek** [comment]
@okrymus I checked your request. 
If you have any problems with the table component not get updated, please open a detailed issue, this might be a bug.

If you wan't to update the selected value from autocomplete component, you can use a two-way binded v-model value.
