### ISSUE TITLE
Upload with prop `multiple` does not bind value into v-model

### ISSUE THREAD

**Issue by masyoudi** [oruga-ui/oruga#759]
### Overview of the problem

**Oruga** version: [0.8.2]
**Vuejs** version: [3.3.7]
**OS/Browser**: Linux/Chrome 121.0.6167.139 (64-bit)
**OS/Browser**: Linux/Firefox 122.0 (64-bit)

### Description

Value does not bind into `v-model`

### Steps to reproduce

Simply use `o-upload` with `multiple` props, like shown in the docs: https://oruga-ui.com/components/Upload.html#drag

![image](https://github.com/oruga-ui/oruga/assets/24524417/430ea848-725c-4936-8979-7611e0f5dfbf)

### Expected behavior

Value should  bind into v-model

### Actual behavior

Value does not bind into v-model

**Comment by wxxxcxx** [comment]
I have the same problom. 

The console show warning

```
useInputHandler.ts:73 Underlaying Oruga input component not found
```
