### ISSUE TITLE
Doc, scroll to top in Table page when clicking pagination numbers

### ISSUE THREAD

**Issue by Nemesis19** [oruga-ui/oruga#778]
Please visit the url: https://oruga-ui.com/components/Table.html#async

click on any page number, you get a scroll to top effect in page, really annoying.

I'm using latest Chrome version (121)

**Comment by mlmoravek** [comment]
I encountered this problem already. It comes from using the `a` tag without any `href` attribut inside the component. I already changed some like this in the datepicker components to `button`. 

However, good determination I will fix this too :)
