### ISSUE TITLE
ODatetimepicker not working when :min-datetime is updated

### ISSUE THREAD

**Issue by summersamara** [oruga-ui/oruga#784]
### Overview of the problem

**Oruga** version: [0.8.3]
**Vuejs** version: [3.4.16]
**OS/Browser**: Linux Ubuntu/Firfefox 122.0.1 (64-bit)

### Description

When `minDatetime` value is updated, ODatetimepicker stops working.

### Steps to reproduce

1. Using the example code for **Datetimepicker Min/Max Datetime** from oruga docs (https://oruga-ui.com/components/Datetimepicker.html):

```
<section>
    <o-field grouped>
        <o-field label="Min Datetime">
            <o-datetimepicker
                v-model="minDatetime"
                placeholder="Click to select..."
                icon="calendar"
                editable />
        </o-field>
        <o-field label="Max Datetime">
            <o-datetimepicker
                v-model="maxDatetime"
                placeholder="Click to select..."
                icon="calendar"
                editable />
        </o-field>
    </o-field>
    <o-field label="Select datetime">
        <o-datetimepicker
            rounded
            placeholder="Click to select..."
            icon="calendar"
            :min-datetime="minDatetime"
            :max-datetime="maxDatetime" />
    </o-field>
</section>

```

```
import { ref } from "vue";

const minDatetime = ref(null);
const maxDatetime = ref(null);

```
2. Select a Min. Datetime
3. The ODatetimepicker component that uses `:min-datetime` doesn't work anymore. 

### Expected behavior

After `:min-datetime` is updated, ODatetimepicker works properly and the dates before the updated `:min-datetime` value are disabled in the picker.

### Actual behavior

The ODatetimepicker component crashes after `:min-datetime` is updated.

**Comment by mlmoravek** [comment]
@summersamara Thanks for sharing this bug! 
The bug occurs because the `v-model` value is a computed property and the getter is always the `modelValue` property. So by not providing a v-model property, the `modelValue` is always `undefined` and will not be updated by the `"update:modelValue"` event. 

I will fix this.

However, as a workaround, you can simply add a v-model ref value to make it work.

**Comment by summersamara** [comment]
> @summersamara Thanks for sharing this bug! The bug occurs because the `v-model` value is a computed property and the getter is always the `modelValue` property. So by not providing a v-model property, the `modelValue` is always `undefined` and will not be updated by the `"update:modelValue"` event.
> 
> I will fix this.
> 
> However, as a workaround, you can simply add a v-model ref value to make it work.

Thanks for the quick response!
Unfortunately, the workaround doesn't seem to work: I tried adding a `v-model` ref but I'm ending up with the same issue.

**Comment by mlmoravek** [comment]
@summersamara Oh yeah, you are right, I only tested it on the development branch, not the main branch (which is the released version). My workaround unfortunately does not work on the release. 
However, you can expect this bug to be fixed in the next release :)
