### ISSUE TITLE
o-datepicker donot work in nuxt module

### ISSUE THREAD

**Issue by shahriar350** [oruga-ui/oruga#79]
I just going to use this UI in my next project but date picker does not work. but other components are working well.
![1](https://user-images.githubusercontent.com/44544213/106593413-fa9de780-657a-11eb-8b67-8ad856fc41c2.PNG)
![2](https://user-images.githubusercontent.com/44544213/106593423-fd004180-657a-11eb-98ae-8896f1d5edce.PNG)
![3](https://user-images.githubusercontent.com/44544213/106593427-fe316e80-657a-11eb-8583-8d324dc6ab6f.PNG)

I trying to solve this problem. So I try to use this as plugins. it works but it shows as without CSS but I copy-paste all code from your website.

**Comment by jtommy** [comment]
@shahriar350 what version are you using ? I think you're not using the last version `0.3.0`

**Comment by shahriar350** [comment]
> @shahriar350 what version are you using? I think you're not using the last version `0.3.0`

I am using 0.2.2. I just installed new nuxt js with Oruga ui. Nuxt automatically install V.0.2.2

**Comment by jtommy** [comment]
@shahriar350 we added datepicker since `0.3.0`

**Comment by shahriar350** [comment]
> @shahriar350 we added datepicker since `0.3.0`, please upgrade it ;)

after upgrading..
![image](https://user-images.githubusercontent.com/44544213/106631324-dbb54a80-65a6-11eb-9339-723d3809c01c.png)

is nuxt module makes any problem?

**Comment by jtommy** [comment]
Oruga lite CSS is now the default, you have to import `oruga.css`

**Comment by shahriar350** [comment]
> Oruga lite CSS is now the default, you have to import `oruga.css`

![image](https://user-images.githubusercontent.com/44544213/106631897-64cc8180-65a7-11eb-8ff8-2d860f410fa4.png)
If i need to use import oruga.css then, i have to use this UI as a plugin. Is there any solution to use this in a module?

**Comment by jtommy** [comment]
We forgot to update the nuxt plugin 😞 
Waiting the fix you might create a plugin as described in the readme

**Comment by shahriar350** [comment]
> We forgot to update the nuxt plugin 😞
> Waiting the fix you might create a plugin as described in the readme

![image](https://user-images.githubusercontent.com/44544213/106632677-38fdcb80-65a8-11eb-8a5d-20f571e9b9b4.png)
I fix this problem in @oruga-ui/oruga/nuxt/index.js to comment the whole CSS and keep this one.
Now works fine. Is this the right way to use?

**Comment by shahriar350** [comment]
![image](https://user-images.githubusercontent.com/44544213/106635154-b4607c80-65aa-11eb-9508-4d600089e4b0.png)
![image](https://user-images.githubusercontent.com/44544213/106635199-bd514e00-65aa-11eb-9a0c-6eef5d849895.png)
Is my css works? Your website's UI looks great but here, the design is changed

**Comment by jtommy** [comment]
Please take a look at docs, the website uses oruga-full-vars.css.

**Comment by jtommy** [comment]
@shahriar350 we've just released 0.3.1, so you can use nuxt module

**Comment by astagi** [comment]
@shahriar350 sorry I made a mistake referencing this issue in my older commit. Anyway release `0.3.1` and `0.3.2` are available on npm with some minfix, including this one!

```sh
npm i @oruga-ui/oruga@0.3.2
```

**Comment by shahriar350** [comment]
thanks brother .
