### ISSUE TITLE
Add input customisation class for autocomplete component

### ISSUE THREAD

**Issue by KevinNTH** [oruga-ui/oruga#8]
### Description

Autocomplete component provides these following classes to extend / override the component: 
- root-class
- menu-class
- expanded-class
- item-class

It should include `input-class`.

### Why Oruga need this feature

We need to be able to control the size of the input.
![image](https://user-images.githubusercontent.com/1632391/88275260-5e4a7c80-ccdd-11ea-84e1-ace31c0d0842.png)

More over, then using with icon, we need to be able to set x-padding to the input.

**Comment by jtommy** [comment]
Good point! 
I had in mind to add a new prop `input-classes` (object) that it contains all input props about classes. 
For example: 
```
:input-classes="{
  rootClass: '..',
  inputClass: '...',
  roundedClass: '..' 
}"
```

What do you think ?

**Comment by KevinNTH** [comment]
I think it's a nice idea but I believe having a local `input-class` that override the global one should be better. It will allow to handle specific cases for each component. For now I just try autocomplete one so I can see a need for this component specifically. Wdyt?

**Comment by jtommy** [comment]
But you have to think that `o-autocomplete` uses `o-input` so you might need all input component (icon, wrapper container, ...)

**Comment by KevinNTH** [comment]
In that case, it makes sense!
