### ISSUE TITLE
Add multiple autocomplete (tagsinput)

### ISSUE THREAD

**Issue by shahriar350** [oruga-ui/oruga#80]
When multiple select true, to select multiple options we need to use _ctrl_ but it can better interface and In our real-life application, we need to select multiple options but here data can be vast. So here we need to use filter to search target option.
You can add this searching option in the search bar which can be a better option

**Comment by jtommy** [comment]
It's the native behaviour, you might use tagsinput

**Comment by jtommy** [comment]
It's the native behaviour, probably you might use tagsinput when it will be ready 😃

**Comment by shahriar350** [comment]
> It's the native behaviour, probably you might use tagsinput when it will be ready 😃

thank you. I like this ui because this is a very clean ui and essential pack.

**Comment by jtommy** [comment]
Close https://github.com/oruga-ui/oruga/pull/91
