### ISSUE TITLE
Incorrect passwordVisibleIcon

### ISSUE THREAD

**Issue by zhaolinlau** [oruga-ui/oruga#800]
### Overview of the problem

**Oruga** version: [0.8.3]
**Vuejs** version: [3.4.19]
**OS/Browser**: Windows 11, Firefox

### Description

Currently, the `eye` icon will be shown when the password is invisible
![image](https://github.com/oruga-ui/oruga/assets/68846168/69f73e35-c6c3-4294-993c-41346710ce45)

Currently, the `eye-off` icon will be shown when the password is visible
![image](https://github.com/oruga-ui/oruga/assets/68846168/caf521ef-14e6-42b5-b7ee-28f06d313b31)

### Steps to reproduce

1. add a password input <o-input type="password" passwordReveal />
2. add passwordReveal prop
3. type something
4. the `eye` icon will be shown when the password is invisible

### Expected behavior

`eye-off` icon will be shown when the password is invisible and `eye` icon will be shown when the password is visible.

### Actual behavior

it shows `eye-off` icon when the password is visible and `eye` icon when the password is invisible.

**Comment by mlmoravek** [comment]
The example in the docs looks fine to me...

**Comment by zhaolinlau** [comment]
I'm gonna close this issue because this issue only happen in theme-bulma
