### ISSUE TITLE
Datepicker, Datetimepicker & Timepicker got same error `Cannot read properties of undefined (reading 'focus')`

### ISSUE THREAD

**Issue by masyoudi** [oruga-ui/oruga#809]
### Overview of the problem

**Oruga** version: [0.8.4]
**Vuejs** version: [3.4.18]
**OS/Browser**: Linux/Chrome 122.0.6261.69 (64-bit)

### Description

Datepicker, Datetimepicker & Timepicker throw error `Cannot read properties of undefined (reading 'focus')`

### Steps to reproduce

1. Use Oruga documentation at
    - [Datepicker](https://oruga-ui.com/components/Datepicker.html)
    - [Datetimepicker](https://oruga-ui.com/components/Datetimepicker.html)
    - [Timepicker](https://oruga-ui.com/components/Timepicker.html)
2. The input doesn't show
3.  Open devtools
![image](https://github.com/oruga-ui/oruga/assets/24524417/50248350-d78f-4ce4-9d7f-919555fe3b13)

### Expected behavior

The component shouldn't throw an error.

**Comment by mlmoravek** [comment]
Ohh thats totally my bad :/ Thanks for discovering that issue!
