### ISSUE TITLE
OModal: Props passed to OModal are not reflected when dynamically changed.

### ISSUE THREAD

**Issue by mk-startialab** [oruga-ui/oruga#826]
### Overview of the problem

**Oruga** version: [0.8.5]
**Vuejs** version: [3.4.20]
**OS/Browser**:
Windows 10 / Chrome 122.0.6261.95 (64bit)

### Description

Props passed to OModal are not reflected when dynamically changed.

### Steps to reproduce

See this StackBlitz:
https://stackblitz.com/edit/vitejs-vite-spyfnj
(Click "To OModal problem")

### Expected behavior

Props passed to OModal are reflected when dynamically changed.

### Actual behavior

Props passed to OModal are not reflected when dynamically changed.
(definitely for width and rootClass.)

**Comment by mlmoravek** [comment]
@mk-startialab Thank you for pointing this out!

Firstly: Surely the `width` property can be changed to be reactive.

Second: I think that the `class` properties not being reactive is a bigger issue. It looks like no `class` property for any component is reflected when dynamically changed.
Was this reactive before 0.8?

**Comment by mk-startialab** [comment]
@mlmoravek 
Hmm... you are right, I think there are no `class` properties reflected reactively, even prior to version 0.8.

And I understand that it is a very big issue, but still I would like at least the `rootClass` to be the only one that changes reactively.
There are workarounds, such as using wrapped div tags, but in order for the style of the component to change reactively, it would be simpler as a component if the `rootClass` could change reactively if possible.
(However, if `rootClass` can change reactively, we can expect requests to do the same for other classes, and as I mentioned above, there are workarounds, so my opinion is merely "It would be more organized if that were the case.")

**Comment by mk-startialab** [comment]
@mlmoravek Thanks a lot, and I understand.

> For now, as a workaround, you can add a :key property with the same value as your :rootClass property to force a rerender of the component every time your rootClass changes.
Oh, it's a good information! I'll give it a try.

**Comment by mk-startialab** [comment]
Close.

**Comment by mk-startialab** [comment]
@mlmoravek 

> For now, as a workaround, you can add a :key property with the same value as your :rootClass property to force a rerender of the component every time your rootClass changes.

The workaround worked great.
Thank you so much!
