### ISSUE TITLE
Typescript error :  Type 'HTMLElement | null' is not assignable to type 'string | HTMLElement | undefined'.

### ISSUE THREAD

**Issue by messenjer** [oruga-ui/oruga#828]
### Overview of the problem

**Oruga** version: 0.8.5
**Vuejs** version:  3.4.19
**OS/Browser**:

### Description

When I upgrade to oruga 0.8, I have a typescript error.

### Steps to reproduce

src/pages/MyPage.vue:260:49 - error TS2322: Type 'HTMLElement | null' is not assignable to type 'string | HTMLElement | undefined'.

260   const loadingComponent = oruga.loading.open({ container: eltRef.value });

### Expected behavior

As in the documentation, you must be able to have container === null

https://github.com/oruga-ui/oruga/blob/9693d7c63246eb0d6fab791f272b6d9574dab253/packages/docs/.vitepress/theme/examples/loading/programmatically.vue#L16

```diff
function openLoading() {
    const loadingComponent = oruga.loading.open({
        fullPage: isFullPage.value,
+        container: isFullPage.value ? null : elementRef.value,
    });
    setTimeout(() => loadingComponent.close(), 3 * 1000);
}
```

### Actual behavior

error TS2322: Type 'HTMLElement | null' is not assignable to type 'string | HTMLElement | undefined'.

**Comment by messenjer** [comment]
Sorry, I didn't see that you'd changed your comment, after I replied. I've got the error in my project, I'll look into making a reproduction.

**Comment by mlmoravek** [comment]
@messenjer Try deleting the `node_modules` folder, the `package-lock.json`, reinstalling all dependencies and then restarting your ide. This solves the `any` as type problem for me.
And also try to update vue-tsc and and the [volar extension](https://marketplace.visualstudio.com/items?itemName=Vue.volar).

However, i will consider adding `null` to the `container` prop type.
