### ISSUE TITLE
Error TS2688: Cannot find type definition file for '@oruga-ui/oruga-next/volar'.

### ISSUE THREAD

**Issue by messenjer** [oruga-ui/oruga#839]
### Overview of the problem

**Oruga** version: [X.X.X]
**Vuejs** version: [X.X.X]
**OS/Browser**:

### Description

When I add the type definition for volar in the tsconfig.ts like in the documentation https://oruga-ui.com/documentation/#volar-support

> If you are using Volar, you can specify global component types by configuring compilerOptions.types in tsconfig.json.
> 
> ```
> js
> // tsconfig.json
> {
>   "compilerOptions": {
>     // ...
>     "types": ["@oruga-ui/oruga-next/volar"]
>   }
> }
> ```

I have this error : Cannot find type definition file for '@oruga-ui/oruga-next/volar'.

### Steps to reproduce

1. Go to https://stackblitz.com/edit/vitejs-vite-dnqnu1?file=tsconfig.json 
2. Type in the terminal : npm run type-check
3. See the error 

```
❯ npm run type-check

> vite-vue-typescript-starter@0.0.0 type-check
> vue-tsc

error TS2688: Cannot find type definition file for '@oruga-ui/oruga-next/volar'.
  The file is in the program because:
    Entry point of type library '@oruga-ui/oruga-next/volar' specified in compilerOptions

  tsconfig.json:22:15
    22     "types": ["@oruga-ui/oruga-next/volar"]
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    File is entry point of type library specified here.

Found 1 error.
```

### Expected behavior

File `volar.d.ts` should be found

### Solution

If add the file in the export section of the `oruga-ui/oruga-ext/package.json` it works.

```diff
  "exports": {
    ".": {
      "types": "./dist/types/index.d.ts",
      "import": "./dist/esm/index.mjs",
      "require": "./dist/cjs/index.js"
    },
+    "./volar": {
+      "types": "./volar.d.ts"
+    },
    "./*": "./*"
  },
```

**Comment by mlmoravek** [comment]
I will try it. 

However, for me adding this works `"types": ["@oruga-ui/oruga-next/volar.d.ts"]`.

**Comment by messenjer** [comment]
Thanks.

I just looked at what they were doing elsewhere in other libraries.
* https://github.com/intlify/bundle-tools/blob/main/packages/unplugin-vue-i18n/package.json#L67 

I don't know what the best practice is, in general, you don't mention the .d.ts, as in the documentation
* https://www.typescriptlang.org/tsconfig#types

**Comment by mlmoravek** [comment]
@messenjer I finally got some time to upgrade from 0.8.3 to a newer version and I discovered a strange problem...

In oruga 0.8.3 everything works fine for me, but since 0.8.4 the imported component type is always `any`.  Somehow the component type definition got lost...
Have you noticed this problem?
