### ISSUE TITLE
Add a WYSIWYG text editor.

### ISSUE THREAD

**Issue by shahriar350** [oruga-ui/oruga#85]
A text editor is important. There are so many editors in vue but all are heavy or lightweights are not so efficient.
Text editor maybe content all like GitHub text editor and image may convert base64/upload option and importantly a table. 
I see some editor like Vue2Editor but there is no support for the table.

**Comment by jtommy** [comment]
I discussed about it with @astagi and probably we are going to develop it (low priority at the moment).
We are not sure if add it as "pro" components anyway.

**Comment by jtommy** [comment]
I agree with @rubjo and the linked project looks really good 😉
