### ISSUE TITLE
Icons are not displayed in Oruga-next version with custom Iconpack [0.3.3]

### ISSUE THREAD

**Issue by NilsBWinter** [oruga-ui/oruga#89]
### Overview of the problem

**Oruga** version: [0.3.3]
**Vuejs** version: [3.0.0]
**OS/Browser**:

### Description

Oruga uses default instead of custom Iconpack (working in Oruga version : 0.3.2)

A Custom Iconpack (mdi-Icons) is used.
The Icons are registered like that:

```
app.use(Oruga, {
	iconComponent: 'icon-mdi',
	iconPack: 'mdijs',
	customIconPacks: {
		mdijs: {
			iconPrefix: 'mdi-',
		},
	},
});
app.component('icon-mdi', iconMdi);
```

in the Vue component the icons are used like this:

`<o-icon icon="map-marker"></o-icon>`

### Steps to reproduce

1. use Oruga Version 0.3.2
2. create a "o-icon" Tag
3. Icons are working
4. upgrade to Oruga Version: 0.3.3
5. Icons are not working anymore

### Expected behavior

Icons from default are being loaded and not from the custom Iconpack.

### Actual behavior

Icons from Iconpack are being laoded.

**Comment by jtommy** [comment]
Thanks for the feedback, we'll investigate about it.
In the meanwhile can you share a codesandbox in order to reproduce it

**Comment by jtommy** [comment]
Close https://github.com/oruga-ui/oruga/commit/dd5f8838db0551acec3779b439199145319cb5ee
