### ISSUE TITLE
Expanded prop not working on o-input

### ISSUE THREAD

**Issue by lucraraujo** [oruga-ui/oruga#923]
### Overview of the problem

**Oruga** version: 0.8.9
**Vuejs** version: 3.4.27
**OS/Browser**: Windows 11. Edge and Firefox

### Description

When creating a o-input inside a o-field and applying a the expanded prop to the o-input, the class is not added to the control div.

### Steps to reproduce

Create a o-input inside an o-field;
Add the "expanded" props to the o-input components;
Observe in the browser inspector that the expanded attributes are not applied.

### Expected behavior

The "expanded" attributes are not being applied;

### Actual behavior

The "expanded" attributes are applied.

**Comment by mlmoravek** [comment]
@lucraraujo Sorry, I can't reproduce this. It works for me...

**Comment by lucraraujo** [comment]
It works now!
I believe I was dealing with some cache from older versions or something like this....
