### ISSUE TITLE
table thDetailedClass not working

### ISSUE THREAD

**Issue by andy-Owl** [oruga-ui/oruga#93]
Hello,

the table th detailed class is not working for me.

<o-table v-if="activeTable"
....
            detailed
            th-detailed-class="o-table__th"
/>

outcome is

<th width="40px"></th>

without any class

Any thoughts?

Cheers

**Comment by jtommy** [comment]
You are right, the prop is missing

**Comment by astagi** [comment]
@andy-Owl I changed label from `bug` to `question` because we can't reproduce the issue, could you provide a codesandbox or some code in order to reproduce it? Thank you!
