### ISSUE TITLE
datetimepicker: Editing directly the datetime does not always update the calendar view

### ISSUE THREAD

**Issue by Massedil** [oruga-ui/oruga#940]
### Overview of the problem

Oruga version: 0.8.10
Vuejs version: 3.4.20
OS/Browser: Tried on Firefox 126

### Description

If a user edit manually the date in the `<input type='text' [...]>` component of the datetimepicker (so without using the calendar component), the new date is not always well updated in the calendar view.

### Steps to reproduce

1. Go on https://oruga-ui.com/components/Datetimepicker.html
2. In one of the date example, change manually in the `input` field the month and day of the date (here from `03/06/2024 18:00` to `04/05/2024 18:00`)

### Expected behavior

The calendar displays the 04/05/2024 date, so with the May month.

### Actual behavior

The calendar wrongly displays the 03/06/2024 date, so with the June month.

![image](https://github.com/oruga-ui/oruga/assets/20357783/e48156cf-f189-4686-a816-2b5e434a8cc9)

**Comment by Massedil** [comment]
Same problem if you choose to change the year : the `select` year list is not updated.

It seems to works fine for the time and the day change.

And also, if you put something wrong (`03/06/2024 00:00wrong`) and leave the control, it stays.

If you put `03/06/2024 0wrong0:00`, it correctly clears the input.

**Comment by mlmoravek** [comment]
The 3.6.2024 with the green border is the current date. The selected date should be completely filled with green using the oruga theme.

To be clear, the date is changed and selected correctly? Only the view doesn't change to the new month/year when the date is changed?

**Comment by mlmoravek** [comment]
And the other older issue #922 is fixed correctly?

**Comment by Massedil** [comment]
> The 3.6.2024 with the green border is the current date.

Yes !

> The selected date should be completely filled with green using the oruga theme.

Yes, I'm ok with that too !

> To be clear, the date is changed and selected correctly?

If the date is valid, yes. The bug #922 is correctly fixed.

If the date is invalid, I don't really test what happens. But it is confusing for the user.

> Only the view doesn't change to the new month/year when the date is changed?

Yes ! And if there is an error, sometimes the `input` is correctly cleared, sometimes not ! So what happens if you submit the form is confusing for the user.

**Comment by Massedil** [comment]
Your change works fine here : 
https://deploy-preview-941--oruga-documentation-preview.netlify.app/components/Datetimepicker.html

But with 0.8.11, there is no Datetimepicker component on your website (Firefox 126) :
https://oruga-ui.com/components/Datetimepicker.html

On dev console, I can see errors (`ReferenceError: can't access lexical declaration 'N' before initialization`)

@mlmoravek Is it normal ?

**Comment by mlmoravek** [comment]
@Massedil Ohh fu**, something gone wrong -.- I'm sorry for that...
Is it only the docs, or also when you use the 0.8.11 version on your project?

**Comment by Massedil** [comment]
> Is it only the docs, or also when you use the 0.8.11 version on your project?

Given the state of the official doc, I have not yet tried on the project.
