### ISSUE TITLE
Modal not showing

### ISSUE THREAD

**Issue by cyberfly** [oruga-ui/oruga#95]
On version 0.3.4, and I was using TailwindCSS on my project. No configuration, basically just install Oruga to test it

I was following Open Modal Clip Scroll

https://oruga.io/components/Modal.html#examples

But the modal is not showing. Nothing happen

When inspect the vue dev tools, the o-modal active already true

![image](https://user-images.githubusercontent.com/1756170/108797885-4c102400-75c7-11eb-9cad-82e367e043ab.png)

**Comment by jtommy** [comment]
Are you importing Oruga CSS?

**Comment by cyberfly** [comment]
@jtommy sorry its oruga for Vue 2.

**Comment by jtommy** [comment]
Can you reproduce on codepen or similar?

**Comment by astagi** [comment]
@cyberfly any update on this?

**Comment by cyberfly** [comment]
@jtommy is there any codepen template for Oruga UI that I can quickly spin off?

@astagi I revisit the modal after 2 weeks, and looks like the Modal only works if the `isCardModalActive` is set to true by default.  

```

<button type="button" @click="isCardModalActive = true">
        Open modal (clip scroll)
      </button>

<o-modal :active.sync="isCardModalActive" :width="640" scroll="clip">
      <p>
        laoreet et metus. Aenean placerat turpis nec tincidunt tempus.
      </p>
    </o-modal>

```

```
data() {
    return {
      search_data: {},
      total: 0,
      loading: false,
      current_user: {},
      isCardModalActive: true
    };
  },
```

**Comment by jtommy** [comment]
@cyberfly yes, active prop must be true
