### ISSUE TITLE
Datetimepicker throw error `ReferenceError: Cannot access 'N' before initialization`

### ISSUE THREAD

**Issue by masyoudi** [oruga-ui/oruga#950]
### Overview of the problem

**Oruga** version: [0.8.11]
**Vuejs** version: [3.4.21]
**OS/Browser**: Linux/Chrome 125.0.6422.141 (64-bit)

### Description

Datetimepicker throw error `ReferenceError: Cannot access 'N' before initialization`

### Steps to reproduce

1. Use Oruga documentation at [Datetimepicker](https://oruga-ui.com/components/Datetimepicker.html)
2. The input doesn't show
3.  Open devtools
![image](https://github.com/oruga-ui/oruga/assets/24524417/9441ba38-d9f5-4c9a-bbce-5c996dba00d3)

### Expected behavior

The component shouldn't throw an error.

### Actual behavior

The component throw an error.

**Comment by mlmoravek** [comment]
Thanks @masyoudi 
Issue is already known, and fix is on the way https://github.com/oruga-ui/oruga/pull/948 :)
