### ISSUE TITLE
Datetimepicker "reference error" 

### ISSUE THREAD

**Issue by digital-codes** [oruga-ui/oruga#987]
### Overview of the problem

**Oruga** version: [0.8.11]
**Vuejs** version: [3.4.29]
**OS/Browser**: Fedora 39, Firefox 126.0

### Description

Any instance of datetimepicker throws error:

Uncaught (in promise) ReferenceError: can't access lexical declaration 'isMobileNative' before initialization
...
in ... node_modules/@oruga-ui/oruga-next/src/components/datetimepicker/Datetimepicker.vue)

### Steps to reproduce
Custom project with Oruga 0.8.11
Or go to 
https://oruga-ui.com/components/Datetimepicker.html

No widgets. Error message like above. Well, it says ReferenceError: can't access lexical declaration 'N' before initialization and a different line number because the site doesn't run in dev mode

Did not occur on .8.10 and before ...

**Comment by mlmoravek** [comment]
duplicate #950
