### ISSUE TITLE
datetimepicker: Editing directly the datetime with valid (or wrong) value does not always update the calendar view

### ISSUE THREAD

**Issue by Massedil** [oruga-ui/oruga#992]
### Overview of the problem

**Oruga** version: 0.8.12
**Vuejs** version: 3.4.20
**OS/Browser**: Tried on Firefox 127

### Steps to reproduce

1. Go on https://oruga-ui.com/components/Datetimepicker.html
2. In one of the date example, change manually in the `input` field : "21/06/2023"

### Expected behavior

Best : The calendar is updated with the date to "21/06/2023" and the time to "00:00".
At leat : The `input` is cleared

### Actual behavior

The `input` is not cleared and the user wrongly think everything is ok.

![image](https://github.com/oruga-ui/oruga/assets/20357783/48344dae-1002-4e4a-aded-730ca0656afc)
![image](https://github.com/oruga-ui/oruga/assets/20357783/9fc5c8e1-9dce-48ed-b79d-81e684f87630)

### Behaviour with wrong values

1. Go on https://oruga-ui.com/components/Datetimepicker.html
2. In one of the date example, write manually in the `input` field : "21/06/wrong"

Actual : input stays with the wrong value 

![image](https://github.com/oruga-ui/oruga/assets/20357783/13e54cbc-a7a1-4f03-9b5c-2dfdfaf29fd7)
![image](https://github.com/oruga-ui/oruga/assets/20357783/824d6581-677f-412e-8ab1-aa4f5994b5f9)

Expected : input is cleared

### Expected to solve all problems 

When user leave the input, the input value is always verified, if it can be casted to a valid datetime, the value is updated to this valid datetime and the calendar is updated accordingly. If the value is wrong, then the input is cleared and the calendar reset.

**Comment by mlmoravek** [comment]
@Massedil, could you check if everythink is working as expected on this PR deployment? 
https://deploy-preview-1026--oruga-documentation-preview.netlify.app/

**Comment by Massedil** [comment]
> @Massedil, could you check if everythink is working as expected on this PR deployment?

https://deploy-preview-1026--oruga-documentation-preview.netlify.app/components/Datetimepicker.html

For me, in Firefox 128, no datetimepicker is visible. Is it ok for you ?

![image](https://github.com/user-attachments/assets/8e7ee80d-05ad-460d-8db5-b26e225b7034)

**Comment by mlmoravek** [comment]
@Massedil try to change the theme to the oruga theme. 
The bulma theme isn't quite ready for alpha v0.9.

**Comment by Massedil** [comment]
> @Massedil try to change the theme to the oruga theme.

With the oruga theme, calendar is well displayed, thanks for the hint !

I use French format here (DD/MM/YYYY) : 
- If I put "01/05/1990", I got "05/01/1990 00:00" instead of "01/05/1990 00:00"
- "25/01/1990" clears the input field. Expected : "25/01/1990 00:00".

![image](https://github.com/user-attachments/assets/a874262c-a664-43de-8298-2a7f96001677)

- Enabling "Enable seconds" does not add seconds to the actual date in the input field. Actual : "01/05/1990 00:00", expected : "01/05/1990 00:00:00"

- Changing "Hour format" from "12" to "24" does not update the date in the input field

This is what I can quickly see. Let me know I you want me to check again.

**Comment by mlmoravek** [comment]
Hey @Massedil, I fixed the formatted input, it now updates when the dateformat specific props like `locale` change. 
To enter a date in a specific locale format, you have to select the locale. 
I also fixed the `enableSeconds` prop.

Let me know if you find any more bugs or unexpected behaviour.

Btw, the PR where the deployed version comes from is here if you want to checkhout the changes:
https://github.com/oruga-ui/oruga/pull/1026

**Comment by Massedil** [comment]
Sorry for my reply time, I had no access to a PC since 2 weeks.

It will probably be the same for next 2 weeks.

What I see lokking from here :
https://deploy-preview-1026--oruga-documentation-preview.netlify.app/components/Datetimepicker.html

When changing locale, date is cleared or reinit to now.
---

a. Select a datetime (for example `07/08/2024 17:56`)
b. Change locale from `   ` to `fr-CA`
c. Date is now `2024-07-08 17 h 56`, expected : `2024-08-07 17 h 56`

a. Select a datetime (for example `31/08/2024 17:58`)
b. Change locale from `   ` to `fr-CA`
c. Date is now empty ! Expected : `2024-08-31 17 h 56`
d. Now change locale to `   `
e. The datetime field disapears ! Expected : it stays !

![image](https://github.com/user-attachments/assets/23d99d80-747b-4961-b9d7-ed8fc2a5af33)

25/01/1990
---

> To enter a date in a specific locale format, you have to select the locale.

a. Select `fr-FR`
b. Paste `25/01/1990` in the input field
c. Input field is cleared. Expected : `25/01/1990 00:00`

01/05/1990
---

Locale is empty and untouched (nothing selected).

- if I put `01/05/1990`, I got : `05/01/1990 18:04`
- if I use the calendar, select year `1990`, month `mai`, I click on `1`, I got `01/05/1990 00:00`

Expected : 
- if I put `01/05/1990`, I got : `01/05/1990 18:04`, like if I use the calendar

![image](https://github.com/user-attachments/assets/e8f679f2-1d59-42fd-a259-c54a714e2240)

enableSeconds
---

> I also fixed the enableSeconds prop

Yes, it works !

**Comment by mlmoravek** [comment]
Hi @Massedil, 

Changing local after initialisation isn't a use case I would assume. I think when setting no local a `new Date()` is built by the user system local. 

The input is parsed using the `Date` object. You have to set your own parser to have a specific behaviour. We can't write a parser for every time format.
